### PR TITLE
fix: Some RegExpRouter bugs

### PR DESCRIPTION
**Pull request by usualoma**

### CODE REVIEW

**Comment by usualoma** [comment]
I am adding a few tests now. Please wait a moment 🙇

**Comment by usualoma** [comment]
@yusukebe 

Add some tests at 61b4b4a.

Please review.

I will add more later.

**Review by yusukebe — COMMENTED** [review]
Looks good!

**Comment by usualoma** [comment]
Oh, sorry, this is the end of the work on this PR.
If it looks good, please merge!

**Comment by usualoma** [comment]
Thank you!

There is nothing more I plan to do before v1.2.0.

**Pull request merged**
