### PR TITLE
feat(utils): add named http codes

### PR DESCRIPTION
**Pull request by qoomon**
### Author should do the followings, if applicable

- [x] Add tests
- [x] Run tests
- [ ] `bun denoify` to generate files for Deno

### CODE REVIEW

**Comment by watany-dev** [comment]
In my personal opinion, this does not seem very necessary. The reason-phrase has been ignored since HTTP/2 and would only increase the size.

**Comment by qoomon** [comment]
I agree the phrases do not add a lot of value, however still I think the named status adds a lot of readability.

**Comment by yusukebe** [comment]
Hi @qoomon 

Thank you for the PR.

We had the same feature but removed it in this PR: https://github.com/honojs/hono/pull/1037.

I'm still thinking it's unnecessary for the same reason.

**Comment by qoomon** [comment]
Eventually I agree and understand.

**Comment by yusukebe** [comment]
Thanks!

**Pull request closed without merging**
