### PR TITLE
Update cookie.ts to include CHIPS support.

### PR DESCRIPTION
**Pull request by Manouchehri**
https://developer.mozilla.org/en-US/docs/Web/Privacy/Partitioned_cookies

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @Manouchehri!

Thank you for the PR. It looks good. I would like you to do two things:

1. Add some tests to `utils/cookie.test.ts` and `middleware/cookie/index.test.ts`.
2. Run `yarn denoify`.

**Comment by yusukebe** [comment]
Hi @Manouchehri 

Could you address the above two points?

**Comment by CyberFlameGO** [comment]
This was superseded and can be closed now :)

**Comment by yusukebe** [comment]
Thanks both!

**Pull request closed without merging**
