### PR TITLE
docs(jsdoc): add JSDoc for Middleware

### LINKED ISSUE #1338: JSDoc
### What is the feature you are proposing?

We haven't written JSDoc for the Hono code. I used to think that maintaining JSDoc would be troublesome, especially since we also have a website. However, now that the API is mostly stable, it's a good time to start. We don't need to write extensively in JSDoc, but including the basics would be beneficial.

### PR DESCRIPTION
**Pull request by yusukebe**
In this PR, let's write the JSDoc for all builtin Middleware.  Only Middleware is addressed here; other documentation than Middleware is done in other PRs. Example #2677.

Will fix #1338

---

- [x] [Basic Auth Middleware](https://hono.dev/middleware/builtin/basic-auth) https://github.com/honojs/hono/pull/2680/commits/3ba73862283b2c1e859782f67a9b77326b6659e6
- [x] [Bearer Authentication](https://hono.dev/middleware/builtin/bearer-auth)
- [x] [Body Limit](https://hono.dev/middleware/builtin/body-limit)
- [x] [Cache](https://hono.dev/middleware/builtin/cache)
- [x] [Compress](https://hono.dev/middleware/builtin/compress)
- [x] [CORS](https://hono.dev/middleware/builtin/cors)
- [x] [CSRF Protection](https://hono.dev/middleware/builtin/csrf)
- [x] [ETag](https://hono.dev/middleware/builtin/etag)
- [x] [JSX Renderer](https://hono.dev/middleware/builtin/jsx-renderer)
- [x] [JWT](https://hono.dev/middleware/builtin/jwt)
- [x] [Logger](https://hono.dev/middleware/builtin/logger)
- [x] [Method Override](https://hono.dev/middleware/builtin/method-override)
- [x] [Pretty JSON](https://hono.dev/middleware/builtin/pretty-json)
- [x] [Secure Headers](https://hono.dev/middleware/builtin/secure-headers)
- [x] [Timing](https://hono.dev/middleware/builtin/timing)
- [x] [Trailing Slash](https://hono.dev/middleware/builtin/trailing-slash)

### CODE REVIEW

**Comment by goisaki** [comment]
I will join this PR!
My progress will be shown here:

## Added
* [x]  [Bearer Authentication](https://hono.dev/middleware/builtin/bearer-auth) [`goisaki:feat/add-jsdoc@b7b5823`](https://github.com/honojs/hono/commit/b7b582331d3e3cbeb583192a114fcbbfba39baaa)
* [x]  [Body Limit](https://hono.dev/middleware/builtin/body-limit) [`goisaki:feat/add-jsdoc@81365f6`](https://github.com/honojs/hono/commit/81365f60c84eb49e6d447e25249c626639d3c012)
* [x]  [Cache](https://hono.dev/middleware/builtin/cache) [`goisaki:feat/add-jsdoc@19eaf99`](https://github.com/honojs/hono/commit/19eaf996535f2d80721413a86cdcaa7465ab7a06)

## Not added
* [ ]  [Compress](https://hono.dev/middleware/builtin/compress)
* [ ]  [CORS](https://hono.dev/middleware/builtin/cors)
* [ ]  [CSRF Protection](https://hono.dev/middleware/builtin/csrf)
* [ ]  [ETag](https://hono.dev/middleware/builtin/etag)
* [ ]  [JSX Renderer](https://hono.dev/middleware/builtin/jsx-renderer)
* [ ]  [JWT](https://hono.dev/middleware/builtin/jwt)
* [ ]  [Logger](https://hono.dev/middleware/builtin/logger)
* [ ]  [Method Override](https://hono.dev/middleware/builtin/method-override)
* [ ]  [Pretty JSON](https://hono.dev/middleware/builtin/pretty-json)
* [ ]  [Secure Headers](https://hono.dev/middleware/builtin/secure-headers)
* [ ]  [Timing](https://hono.dev/middleware/builtin/timing)
* [ ]  [Trailing Slash](https://hono.dev/middleware/builtin/trailing-slash)

## In progress

**Comment by yusukebe** [comment]
Hi @goisaki 

Great! It will be super helpful.

Could you create the PR based on this [jsdoc-middleware](https://github.com/honojs/hono/tree/docs/jsdoc-middleware) by each middleware?

**Comment by fzn0x** [comment]
Thanks! lets add this TSDoc! 🔥

**Comment by goisaki** [comment]
BOO!
Check these out.
Hono Pull 2680

**Comment by yusukebe** [comment]
@goisaki Okay!

**Comment by goisaki** [comment]
Now I realize that I made too many PRs at once. Apologies to @yusukebe for making it a tough job to review.
These are all the PRs:

- [ ] #2685 
- [ ] #2691 
- [ ] #2692 
- [ ] #2697 
- [ ] #2698
- [ ] #2699 
- [ ] #2702 
- [ ] #2703 
- [ ] #2704 
- [ ] #2705 
- [ ] #2706 
- [ ] #2708 
- [ ] #2709

**Comment by yusukebe** [comment]
Hey @goisaki !

All done! I will now merge it into the `next`. I will leave the commit without squash. Thank you very much!

**Pull request merged**
