### PR TITLE
feat(dev): add `showRoutes()` utility method instead of `app.showRoutes()`

### PR DESCRIPTION
**Pull request by usualoma**
### Author should do the followings, if applicable

- [ ] Add tests
- [ ] Run tests
- [ ] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by usualoma** [comment]
Which is a good argument to start with.

* Add 'hono/dev` in this "hono" repository
* Make it an independent repository
  * Since this is a development tool, we don't have to be concerned about zero dependencies; we can add npm modules to dependencies

**Comment by yusukebe** [comment]
I believe integrating this into the "hono" repository is a good idea. It would be beneficial to develop `hono/dev` as a [helper](https://hono.dev/guides/helpers).

I often use the `showRoutes()` method, and I think many other developers do too. While using an external npm package can be effective, it might not be necessary to have it outside the "hono" repo.

Regarding npm packages, are there any specific ones you think would be useful? Honestly, I'm not a old Node.js user, so I'm not entirely sure which package we can use :)

**Comment by yusukebe** [comment]
Or the point is what methods/features will be added in the future. We need to decide whether to include them in the core, depending on that consideration.

**Comment by usualoma** [comment]
@yusukebe  Thanks for your comment.

To be honest, I don't know much about the npm modules either.

I thought there might be an npm that could write these things in one line. That would be cool. But it might be better, just more dependencies and more things to worry about.
https://github.com/honojs/hono/pull/1697/files#diff-34d76a96faa930c4b9909c055beb422e601e2267f72ce12d6f15a1c2cc6ea914R21

It comes down to this point.

> Or the point is what methods/features will be added in the future. We need to decide whether to include them in the core, depending on that consideration.

But as you pointed out, "implement as a helper" seems appropriate for answering the current request.

**Comment by usualoma** [comment]
This PR is closed because it will be reimplemented under helper.

**Pull request closed without merging**
