### PR TITLE
Introduce `inspectRoutes()` and `showRoutes()`

### PR DESCRIPTION
**Pull request by usualoma**
Introduce `showRoutes()` and `captureRouteStackTrace()`.

If it were only "simple to externalize showRoutes()," it might be too much functionality, but this is how I implemented it for now.

As for the file name and line number with routing added would be of little use in a small application, but I am trying to add something valuable to the development. (The line numbers shift a bit in Bun. Node.js does not output the line numbers because it minifies them before executing them, while Deno outputs the correct information.)

### How it works?

```ts
import { captureRouteStackTrace, showRoutes } from './src/helper/dev'
import { createMiddleware } from './src/helper/factory'
import { Hono } from './src/hono'
import { basicAuth } from './src/middleware/basic-auth'
import { logger } from './src/middleware/logger'

const app = new Hono()

if (process.env.HONO_ENV === 'development') {
  captureRouteStackTrace(app)
}

app.use('*', logger())
app.get('/', basicAuth({ username: 'foo', password: 'bar' }), (c) => c.text('hi'))
app.get(
  '/mw',
  createMiddleware((c, next) => next()),
  (c) => c.text('hi')
)

if (process.env.HONO_ENV === 'development') {
  showRoutes(
    app,
    process.argv[2] === '--show-list' ? { includeMiddleware: true, showList: true } : undefined
  )
}

export default app
```

```
% HONO_ENV=development bun run app.ts # default
GET       /
GET       /mw
% HONO_ENV=development bun run app.ts --show-list
ALL       /*
             logger        /Users/taku/src/github.com/honojs/hono/app.ts:13:0
GET       /    
             basicAuth     /Users/taku/src/github.com/honojs/hono/app.ts:14:0
             [handler]     /Users/taku/src/github.com/honojs/hono/app.ts:14:0
GET       /mw  
             [middleware]  /Users/taku/src/github.com/honojs/hono/app.ts:21:2
             [handler]     /Users/taku/src/github.com/honojs/hono/app.ts:21:2
```

or

```ts
import { captureRouteStackTrace, showRoutes } from './src/helper/dev'
import { createMiddleware } from './src/helper/factory'
import { Hono } from './src/hono'
import { basicAuth } from './src/middleware/basic-auth'
import { logger } from './src/middleware/logger'

const app = new Hono()

app.use('*', logger())
app.get('/', basicAuth({ username: 'foo', password: 'bar' }), (c) => c.text('hi'))
app.get(
  '/mw',
  createMiddleware((c, next) => next()),
  (c) => c.text('hi')
)

if (process.env.HONO_ENV === 'development') {
  app.get('/show-routes', (c) => {
    let html = '<table><tr><th>Method</th><th>Path</th></tr>'
    showRoutes(app, {
      writer: ({ method, path }) => {
        html += `<tr><td>${method}</td><td>${path}</td></tr>`
      },
    })
    html += '</table>'
    return c.html(html)
  })
}

export default app
```

```
% curl http://localhost:3000/show-routes
<table><tr><th>Method</th><th>Path</th></tr><tr><td>GET</td><td>/</td></tr><tr><td>GET</td><td>/mw</td></tr><tr><td>GET</td><td>/show-routes</td></tr></table>
```

### Author should do the followings, if applicable

- [ ] Add tests
- [ ] Run tests
- [ ] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by usualoma** [comment]
Hi @yusukebe!
Would you please give your opinion?

**Comment by yusukebe** [comment]
@usualoma 

Woooow, capturing the line from the Error stack trace! Haha cool idea! It's "too much" as you said, but I like it. And using a named function in built-in or 3rd-party middleware to get the middleware name is good.

> Node.js does not output the line numbers because it minifies them before executing them

This matter might be resolved if it supports adding sourcemap #1712. 

And we can refer to this project: https://github.com/azu/express-router-dependency-graph

Overall, it almost looks good. Let's move forward with this.

**Comment by yusukebe** [comment]
I can't imagine the specific use-cases right now, but the JSON output function which that project has is interesting.

**Comment by usualoma** [comment]
Hi @yusukebe!

Thanks for your comment.
I learned about https://github.com/azu/express-router-dependency-graph; that's helpful.

Ah, it would be more convenient if it were provided in CLI. The following code is not beautiful (not terrible).

```
if (process.env.HONO_ENV === 'development') {
  captureRouteStackTrace(app)
}
```

The "app.ts" contains only the production code, and if you run the following in CLI, `captureRouteStackTrace` will run internally, and you will get the following output, which may be what we need.

```
$ hono-inspect-routes --show-list app.ts
ALL       /*
             logger        /Users/taku/src/github.com/honojs/hono/app.ts:13:0
GET       /    
             basicAuth     /Users/taku/src/github.com/honojs/hono/app.ts:14:0
             [handler]     /Users/taku/src/github.com/honojs/hono/app.ts:14:0
GET       /mw  
             [middleware]  /Users/taku/src/github.com/honojs/hono/app.ts:21:2
             [handler]     /Users/taku/src/github.com/honojs/hono/app.ts:21:2
```

It would be better to add `--format=json` so that the output is in JSON format.

**Comment by usualoma** [comment]
Hi @yusukebe!

I thought about it for a while, but I will complete `showRoutes()` as a helper, as a very simple function in this PR.

I think `captureRouteStackTrace()` is an interesting idea, but the call `captureRouteStackTrace(app)` just doesn't seem pretty, so I'd like to think about it more calmly.

I added `inspectRoutes(app)` as an alternative for users who want to get output in JSON format.

How about this as a PR for solving #676?

**Comment by yusukebe** [comment]
Hi @usualoma 

Sorry for the late reply. I am sick in bed. Will comment when I'm better.

**Comment by usualoma** [comment]
@yusukebe 
Take care and don't worry about the PR.

**Comment by usualoma** [comment]
@yusukebe 
> So, we might need to rethink how we display many items.

Hmmm sure, this is hard to understand. But so far no good ideas have come to mind.

I think you are right about the "verbose" option, so I changed it in dde76a8.

We will consider improving the "verbose" display when there are many items later, but how about merging with this content first?

**Comment by yusukebe** [comment]
@yusukebe 

> We will consider improving the "verbose" display when there are many items later, but how about merging with this content first?

Totally agree! I will merge this into "next" and release it first.

**Pull request merged**
