### PR TITLE
fix(adaptor): Access to custom request context on AWS Lambda Adaptor 

### PR DESCRIPTION
**Pull request by watany-dev**
fixed: https://github.com/honojs/hono/issues/1197

We have revised the approach by opting to retrieve it as c.env, rather than the method of the function we were discussing.

usage:

```typescript
import { handle, getLambdaContext } from 'hono/aws-lambda'
import type { ApiGatewayRequestContext } from 'hono/aws-lambda'
import { Hono } from 'hono'

type Bindings = {
  requestContext: ApiGatewayRequestContext 
}

app.get('/custom-context/apigw', (c) => {
  const lambdaContext = c.env.requestContext
  return c.json(lambdaContext)
})

```

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @watany-dev !

> We have revised the approach by opting to retrieve it as `c.env`.

That's a good idea! I implemented the [Netlify Adapter in the same way](https://hono.dev/getting-started/netlify#context):

```ts
import { Hono } from 'https://deno.land/x/hono/mod.ts'
import { prettyJSON } from 'https://deno.land/x/hono/middleware.ts'

import { handle } from 'https://deno.land/x/hono/adapter/netlify/mod.ts'
import type { Env } from 'https://deno.land/x/hono/adapter/netlify/mod.ts'

const app = new Hono<Env>()

app.get('/country', prettyJSON(), (c) =>
  c.json({
    'You are in': c.env.context.geo.country?.name,
  })
)
```

I'll review this PR in detail later.

**Comment by yusukebe** [comment]
Hi @watany-dev,

LGTM! But there's one thing. Could you run `yarn lint --fix ./runtime_tests/lambda`? The styles are broken in the test files.

**Comment by watany-dev** [comment]
@yusukebe 
Sorry, I've fixed the code under the `runtime_test` directory.

**Comment by yusukebe** [comment]
@watany-dev 

Ah, sorry one more thing. Could you run `yarn prettier --write runtime_tests/lambda` too?

**Comment by watany-dev** [comment]
@yusukebe fixed!

**Comment by yusukebe** [comment]
@watany-dev Cool! Super thanks!

I'll merge this now.

**Pull request merged**
