### PR TITLE
fix(client): do not suggest unnecenssary route path

### PR DESCRIPTION
**Pull request by EdamAme-x**
Closes https://github.com/honojs/hono/issues/3122
### The author should do the following, if applicable

- [ ] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code
- [ ] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

**Comment by EdamAme-x** [comment]
hi @yusukebe 
this pr contains the following two changes.

## 1.  Not includes never
This issue is involved only when the middleware is chained by `.use`.
When we mark `*` with middleware, the `Schema` value contains never.
```ts
{
  "*": never
} & {...}
```
This will also be suggested by hono client as a route.   
This is a serious UX concern.  
However, this PR does not solve the problem of overriding the handler's schema in the middleware path when defining middleware and handler in the same path.

(Instead of using `&` when creating Schema, I can suggest creating and using the type `mergeSchema`.
I have already built this type.)

## 2. Change Generics of createHandler/createMiddleware
Previously, Path was marked as any by default, so if you did not explicitly mark Path as `any`, it was marked as never when any was on Schema.

So I marked at `""`
image
It is working now.

**Comment by EdamAme-x** [comment]
Maybe the two changes should be in different PRs.
If desired I will do so.

**Comment by EdamAme-x** [comment]
hi @yusukebe 
This PR was half resolved by https://github.com/honojs/hono/pull/3128
but I think "1" is not resolved

**Comment by yusukebe** [comment]
@EdamAme-x 

That is another issue.

**Comment by EdamAme-x** [comment]
ok @yusukebe 
I'll create new issue

**Comment by yusukebe** [comment]
@EdamAme-x 

Don't do that. I'll do it.

**Pull request closed without merging**
