### PR TITLE
docs: change to shell highlight

### PR DESCRIPTION
**Pull request by EdamAme-x**
hightlight for shell code

```shell
cd /hono
```

### CODE REVIEW

**Comment by yusukebe** [comment]
What about using `console`.

**Comment by EdamAme-x** [comment]
```shell
cd /a
bun install
```

```console
cd /a
bun install
```

nice suggestion!

**Comment by EdamAme-x** [comment]
Astro is using ````bash` (as shell).
what do you think? @yusukebe

**Comment by yusukebe** [comment]
@EdamAme-x 

Ahh, `console` is not good. Then, I also `bash` is better.

**Comment by EdamAme-x** [comment]
ok. I ready to be

**Review by yusukebe — APPROVED** [review]
LGTM!

**Pull request merged**
