### PR TITLE
refactor(jsx): Tidyup the types to be exported

### PR DESCRIPTION
**Pull request by usualoma**
Tidyup and organize the type definitions exported from hono/jsx in src/jsx/types.ts.

I don't think this will affect most users, but it could be a breaking change for a small percentage of users, so I think this should be included in a major version upgrade (v4).

### New exported type

* PropsWithChildren #2142

### Changed types

* Remove "children" from FC #2142
* JSXNode
    * The previous "class as a value" import is no longer available, and only "type" import is now available.
        * `import { JSXNode } from 'hono/jsx'` is no longer available, only `import type { JSXNode } from 'hono/jsx'` is available.

### No longer be exported

Until now, the types used internally were over-exported. With this PR change, types needed only internally should not be exported.

* Props
* JSXFragmentNode
* jsxFn

### Author should do the followings, if applicable

- [x] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by usualoma** [comment]
I am trying to figure out how to solve the following problem
https://github.com/honojs/hono/actions/runs/7776848588/job/21204467952?pr=2151

**Comment by yusukebe** [comment]
@usualoma 

Maybe this issue: https://github.com/garronej/denoify/issues/124

**Comment by usualoma** [comment]
@yusukebe Oh, thank you. I understand.
I think `export *` would work here, so I changed it temporarily with 874ca99.
Please review.

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@usualoma 

I think it is perfect except for the `denofy` matter. We can update that once `denoify` is fixed.

Thank you for your hard work.

**Pull request merged**
