### PR TITLE
fix(jsx/dom): fix `memo` for DOM renderer

### PR DESCRIPTION
**Pull request by usualoma**
#3473
#3567

The `jsx/dom` memoization was generally behaving incorrectly, so I'm fixing it.

### 12ee8293ccb06dc3e0ae41116ebc412d925d3bac

In the past, the code used the same approach as for `toString(),` “holding memoized data in JavaScript memory,” but when rendering to the DOM, I found that memoization could be achieved by “not re-evaluate components” in the renderer, so the processing within the renderer was changed accordingly.

Also, looking at the code generated by React Compiler, it seemed that React expected the ReactNode object generated by `jsx()` to be cached and reused, and to be memoized, so I made it behave in the same way. I applied this branch to the code at https://github.com/sor4chi/explore-react-compiler-with-hono-jsx and confirmed that it was memoized.

### 38a3c7e5438c08b9036c3988e8932c2457bfb7b6 / 3b45b574d08890c8ead9bc8d8a093d4f6909b782

I changed the implementation of `memo` so that memoization is done using a new mechanism.

### The author should do the following, if applicable

- [x] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @usualoma 

Looks good to me!

@sor4chi Are you interested in reviewing this PR? If so, please!

**Comment by yusukebe** [comment]
I'll merge this now, though @sor4chi does not review it yet. Thanks!

Fixes #3473
Fixes #3567

**Comment by sor4chi** [comment]
I was too busy to see it, sorry...
Good test of react-compiler. I could confirm that it is working correctly for me too!

**Comment by usualoma** [comment]
@sor4chi Thanks for the review!

**Pull request merged**
