### PR TITLE
refactor: cloudflare workers' serve-static module

### PR DESCRIPTION
**Pull request by sor4chi**
### Author should do the followings, if applicable

- [x] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

fixes of #1865

### CODE REVIEW

**Comment by sor4chi** [comment]
Hi, @yusukebe

Could you please review this one too?
I forgot `onNotFound` in the serve-static module and refactored around it.

**Comment by yusukebe** [comment]
How about this?

Since the `options.namespace` is not `deleted`, the actual value could come in, but since it has a type, I think we can go with this.

```ts
const module = <E extends Env = Env>(
  options: Omit<ServeStaticOptions<E>, 'namespace'> = { root: '' }
) => {
  options.manifest ??= manifest
  return serveStatic<E>(options)
}
```

**Comment by sor4chi** [comment]
@yusukebe exactly, thank you!

**Comment by yusukebe** [comment]
@sor4chi 

Okay! Land it.

**Pull request merged**
