### PR TITLE
feat(context): c.redirect support punycode and URL object

### PR DESCRIPTION
**Pull request by EdamAme-x**
### The author should do the following, if applicable

- [x] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code

### CODE REVIEW

**Comment by EdamAme-x** [comment]
based by https://github.com/honojs/hono/pull/2799

**Comment by yusukebe** [comment]
Hi @EdamAme-x 

Thank you for the PR.

Supporting `URL` seems good. But what if it does not create a URL object when it's a `string`?

```diff
diff --git a/src/context.ts b/src/context.ts
index ff4299f..41dee41 100644
--- a/src/context.ts
+++ b/src/context.ts
@@ -558,11 +558,6 @@ export class Context<
   redirect = (location: string | URL, status: RedirectStatusCode = 302): Response => {
     if (location instanceof URL) {
       location = location.href
-    } else {
-      try {
-        const cachedURL = new URL(location)
-        location = cachedURL.href
-      } catch (_e) {} // Do nothing
     }
     this.#headers ??= new Headers()
     this.#headers.set('Location', location)
```

With this implementation, the performance degradation is less if the argument is `string`.

@usualoma Any thoughts?

**Comment by EdamAme-x** [comment]
thanks @yusukebe .
If it is passed as "string", it would eliminate performance problems if it could be branched out into whether it is a URL or just a path.

**Comment by EdamAme-x** [comment]
There is a way to simply check if the "://" is included, what do you think?

**Comment by EdamAme-x** [comment]
However, this still reduces performance in cases such as "https://hono.dev".
Is a delay of 20 μs within the range that can be overlooked?

**Comment by EdamAme-x** [comment]
I noticed that I can determine if punycode should be used when using regex.

**Comment by yusukebe** [comment]
@EdamAme-x 

If the user wants to use Punycode, the user can use a URL object instead of `string`. So, I think we don't have to support it when it's `string`.

> Is a delay of 20 μs within the range that can be overlooked?

Indeed, it's a short time, but in some cases, the `redirect` is used heavily. We want to avoid creating `URL` as much as possible.

**Comment by EdamAme-x** [comment]
> @EdamAme-x
> 
> If the user wants to use Punycode, the user can use a URL object instead of `string`. So, I think we don't have to support it when it's `string`.
> 
> > Is a delay of 20 μs within the range that can be overlooked?
> 
> Indeed, it's a short time, but in some cases, the `redirect` is used heavily. We want to avoid creating `URL` as much as possible.

I agree. I'll write document this

**Pull request closed without merging**
