### PR TITLE
chore: format a forgotten file.

### PR DESCRIPTION
**Pull request by EdamAme-x**
### Author should do the followings, if applicable

- [ ] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by EdamAme-x** [comment]
why
When I ran it locally, there was a warning here, but ci points out the opposite.

**Comment by EdamAme-x** [comment]
image
in local

**Comment by EdamAme-x** [comment]
image


@yusukebe 
hi
I get a warning on the format locally, but when I modify it, I get the opposite on the github actions.
Can you confirm this in your environment?

**Comment by EdamAme-x** [comment]
image

image

Format check is passed by npm, bun, yarn

**Comment by yusukebe** [comment]
This PR is not necessary.

If it is not formatted and linted, CI will fail and it will not be merged, so the v4/main branch's code should be formatted now.

**Comment by EdamAme-x** [comment]
ok

**Pull request closed without merging**
