### PR TITLE
test(vitest): replace `jest` with `vitest`

### LINKED ISSUE #1390: Use Vitest
It's fast.

### PR DESCRIPTION
**Pull request by ThatOneBro**
### Author should do the followings, if applicable

- [x] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

## What this PR does
Replaces `jest` with `vitest` and cleans up dependencies. 

~~I did notice one failing test in `lagon` suite, but I think it's unrelated to this PR.~~ EDIT: Tests not failing on CI, so seems ok.

Closes #1390.

## TODO

EDIT: One last test failing on `Fastly Compute@Edge`...
- [x] Get last test running on `Fastly`

### CODE REVIEW

**Comment by ThatOneBro** [comment]
Currently the `fastly` suite is failing on the test that is supposed to throw `crypto.subtle.importKey in undefined` but is instead throwing `crypto is not defined`... I found I got this same error locally when I was testing in node v18, but on v19 the test passes...

Node v18:
Screen Shot 2023-09-03 at 10 39 37 PM

Node v19:
Screen Shot 2023-09-03 at 10 39 51 PM

**Comment by yusukebe** [comment]
@ThatOneBro 

Great work! I've tested this in my local machine, it's fast!

I'll take a look about the Fastly issue. Thanks!

**Comment by yusukebe** [comment]
Hi @ThatOneBro,

I think reproducing the runtime environment is important. As of now, we've successfully emulated the Fastly environment with `jest-preset-fastly-js-compute`. Considering this, how about we remain the Jest test for Fastly? Of course, we replace other tests with Vitest. This might be a better solution, while we're currently juggling two testing engines: Jest and Vitest.

What do you think about this?

**Comment by ThatOneBro** [comment]
Hey @yusukebe, that makes sense to me. I'll make that change tonight so we can merge this. Keeping `jest` for `Fastly` until there is a `vitest` alternative can work

**Comment by yusukebe** [comment]
@ThatOneBro 

Thanks!

**Comment by ThatOneBro** [comment]
No problem, @yusukebe! I added `jest` back for the `fastly` tests and looks like everything works now! Let me know if there is anything I missed, otherwise feel free to merge!

**Comment by yusukebe** [comment]
Hi @ThatOneBro !

Perfect! Let's go with it. Thanks Derrick!

**Pull request merged**
