### PR TITLE
feat(lambda-edge): pass the `context` and `callback` as env

### LINKED ISSUE #1225: Lambda-edge is unable to continue with the original request
I executed this CDK to set up the environment. 

## CDK(v2.87.0)

```ts:le/lib/le-stack.ts
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { NodejsFunction } from 'aws-cdk-lib/aws-lambda-nodejs';
import * as apigw from 'aws-cdk-lib/aws-apigateway';

export class EdgeStack extends cdk.Stack {
  public readonly edgeFn: lambda.Function;

  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    const edgeFn = new NodejsFunction(this, 'lambda@edge', {
      entry: 'lambda/index_le.ts',  
      handler: 'handler', 
      runtime: lambda.Runtime.NODEJS_18_X,
    });

    const originFn = new NodejsFunction(this, 'lambda', {
      entry: 'lambda/index.ts',  
      handler: 'handler', 
      runtime: lambda.Runtime.NODEJS_18_X,
    });
    const originApi = new apigw.LambdaRestApi(this, 'myapi', {
      handler: originFn,
    });


    new cloudfront.Distribution(this, 'myDist', {
      defaultBehavior: {
        origin: new origins.RestApiOrigin(originApi),
        edgeLambdas: [
          {
            functionVersion: edgeFn.currentVersion,
            eventType: cloudfront.LambdaEdgeEventType.VIEWER_REQUEST,
          }
        ],
      },
    });
  }
}
```

```ts:le/bin/le.ts
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import { EdgeStack } from '../lib/le-stack';

const app = new cdk.App();

const edgeStack = new EdgeStack(app, 'Le2Stack', {
  env: {region: "us-east-1"},
});

```

## Origin(API Gateway + Lambda)

```ts:ls/lambda/index.ts
import { Hono } from 'hono'
import { handle } from 'hono/aws-lambda'
import { html } from 'hono/html'

const app = new Hono()


app.get('/', (c) => c.html(
    html`<!DOCTYPE html>
      <h1>Hello Hono!</h1>`
  )
 )
export const handler = handle(app)
```

---

When I implemented the request viewer like this, I received a 502 error. 

‘‘‘ts
import { Hono } from 'hono'
import { handle } from 'hono/lambda-edge'
import { basicAuth } from 'hono/basic-auth'

const app = new Hono()

app.get('*', basicAuth({
    username: 'yourname',
    password: 'yoursecret',
  }), async (c) => {
  const response = await fetch(c.req.url)
  return response
})

export const handler = handle(app)
```

Even when I implemented it in this way, it did not work. 

```ts
import { Hono } from 'hono'
import { handle } from 'hono/lambda-edge'
import { basicAuth } from 'hono/basic-auth'

const app = new Hono()


app.get('*', basicAuth({
    username: 'yourname',
    password: 'yoursecret',
  }), async (c) => {
    const response = await fetch(c.req.url)

    return new Response(response.body, {
      status: response.status,
      headers: response.headers
    })})

export const handler = handle(app)
```

I think the implementation of other Adaptors or Cloudflare services could serve as a reference.

### PR DESCRIPTION
**Pull request by yusukebe**
This PR allows the Lambda@Edge Adapter to pass the `callback` method, `context`, and `request` object to handlers as `env` variables. This means it can continue request processing if basic authentication has been verified.

```ts
import { Callback, CloudFrontRequest, handle } from 'hono/lambda-edge'

type Bindings = {
  callback: Callback
  request: CloudFrontRequest
}

const app = new Hono<{ Bindings: Bindings }>()

app.get(
  '*',
  basicAuth({
    username: 'a',
    password: 'b'
  })
)

app.get('/index.html', async (c, next) => {
  await next()
  c.env.callback(null, c.env.request)
})

export const handler = handle(app)
```

There's a limitation issue where you cannot add headers such as a specific header value to an origin response. You can only pass through.

Fix #1225

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @watany-dev !

This PR may fix your issue #1225. Could you try to run the snippets with it?

**Comment by watany-dev** [comment]
@yusukebe Of course, yes.

**Comment by watany-dev** [comment]
@yusukebe 
Thank you. Wow, it worked so smoothly in just one go!
https://d3u4hocme10ycl.cloudfront.net/

**Comment by yusukebe** [comment]
@watany-dev 

Awesome!

**Pull request merged**
