### PR TITLE
WIP: feat(jsx/dom): version 0.2

### PR DESCRIPTION
**Pull request by usualoma**
The source code is bigger than I expected, but I think this will work Suspense and ErrorBoundary. Even if you don't use the `use` hook, async components will work.

```ts
/** @jsxRuntime automatic @jsxImportSource ./src/jsx */
import { Suspense, ErrorBoundary } from './src/jsx'
import { render } from './src/jsx/dom'
import { useState, use } from './src/jsx/hooks'

const Component = () => {
  return <div>0</div>
}

const AsyncComponent = async () => {
  const num = await new Promise((resolve) => setTimeout(() => resolve(1), 1000))
  return <div>{num}</div>
}

const promise = new Promise((resolve) => setTimeout(() => resolve(2), 2000))
const UseComponent = () => {
  const num = use(promise)
  return <div>{num}</div>
}

const SyncErrorComponent = () => {
  throw new Error('error')
}

const AsyncErrorComponent = async () => {
  await new Promise((resolve) => setTimeout(() => resolve(1), 3000))
  throw new Error('async error')
}

export const App = () => {
  const [count, setCount] = useState(0)
  return (
    <div>
      <div>
        <h1>Count: {count}</h1>

        <button onClick={() => setCount(count + 1)}>+1</button>

        <div>
          <div>
            <h3>Component</h3>
            <Component />
          </div>
        </div>

        <div>
          <Suspense fallback={<div>Loading AsyncComponent ...</div>}>
            <div>
              <h3>AsyncComponent</h3>
              <AsyncComponent />
            </div>
          </Suspense>
        </div>

        <div>
          <Suspense fallback={<div>Loading UseComponent ...</div>}>
            <div>
              <h3>UseComponent</h3>
              <UseComponent />
            </div>
          </Suspense>
        </div>

        <div>
          <ErrorBoundary fallback={<div>error</div>}>
            <h3>no error</h3>
            <div>3</div>
          </ErrorBoundary>
        </div>

        <div>
          <ErrorBoundary
            fallback={
              <div>
                <h3>SyncErrorComponent</h3>
                <div>Got an error</div>
              </div>
            }
          >
            <div>
              <h3>SyncErrorComponent</h3>
              <SyncErrorComponent />
            </div>
          </ErrorBoundary>
        </div>

        <div>
          <ErrorBoundary
            fallback={
              <>
                <h3>AsyncErrorComponent</h3>
                <div>Got an async error</div>
              </>
            }
          >
            <Suspense fallback={<div>Loading AsyncErrorComponent ...</div>}>
              <div>
                <h3>AsyncErrorComponent</h3>
                <AsyncErrorComponent />
              </div>
            </Suspense>
          </ErrorBoundary>
        </div>
      </div>
    </div>
  )
}

render(<App />, document.getElementById('root'))
```

### Author should do the followings, if applicable

- [ ] Add tests
- [ ] Run tests
- [ ] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by yusukebe** [comment]
Hey @usualoma !

Sorry for the late reply. I've checked. `AsyncComponent` and `Suspense` are working. And, the following four bugs have also been fixed. Awesome!

Fixes #1944
Fixes #1941
Fixes #1942
Fixes #1943

Is this PR ready for the merge? If so, please leave off Draft. I'll review and merge.

**Comment by usualoma** [comment]
@yusukebe 

Sorry I didn't add anything here either, this code is toooo dirty and unmaintainable, so I'm rewriting it in a version that creates a virtual tree.

I'll make another PR later, give me a minute.

**Comment by yusukebe** [comment]
@usualoma 

Okay!

**Comment by usualoma** [comment]
Created #1981

**Comment by usualoma** [comment]
I think this PR has done its job. Good night.

**Pull request closed without merging**
