### PR TITLE
feat(context): add Context-Type types to `c.header`

### PR DESCRIPTION
**Pull request by nakasyou**
I added a Content-Type type helper to `c.header`.
I'm sure you can type mime-types easily than before.
IMG_3631
### The author should do the following, if applicable

- [ ] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code
- [x] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

**Comment by yusukebe** [comment]
@nakasyou 

Great feature! I'll review this later.

**Comment by yusukebe** [comment]
Hi @nakasyou 

I propose the following changes.

```diff
diff --git a/src/context.ts b/src/context.ts
index 2a03cebb..9e1345e4 100644
--- a/src/context.ts
+++ b/src/context.ts
@@ -20,7 +20,10 @@ import type {
 } from './utils/types'
 import type { BaseMime } from './utils/mime'

-type HeaderRecord = Record<ResponseHeader, string | string[]> | Record<string, string | string[]>
+type HeaderRecord =
+  | Record<ResponseHeader, string | string[]>
+  | Record<'Content-Type', BaseMime>
+  | Record<string, string | string[]>

 /**
  * Data type can be a string, ArrayBuffer, or ReadableStream.
@@ -314,6 +317,7 @@ type ResponseHeadersInit =
   | [string, string][]
   | Record<string, string>
   | Record<ResponseHeader, string>
+  | Record<'Content-Type', BaseMime>
   | Headers

 interface ResponseInit {
diff --git a/src/utils/mime.ts b/src/utils/mime.ts
index d9a54cc4..f6df4853 100644
--- a/src/utils/mime.ts
+++ b/src/utils/mime.ts
@@ -79,7 +79,6 @@ export type BaseMime =
   | 'video/3gpp2'
   | 'model/gltf+json'
   | 'model/gltf-binary'
-  | (string & {})

 const baseMimes: Record<string, BaseMime> = {
   aac: 'audio/aac',
```

With this PR, it can infer other patterns, not only the `c.header()` pattern. And the last line `| (string & {})` in `utils/mime.ts` is not necessary, I think. It should be strict.

**Comment by nakasyou** [comment]
@yusukebe OK, I changed it.

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@nakasyou 

Good! I'll release the new patch version that includes this feature. Thank you for your great idea!

**Pull request merged**
