### PR TITLE
fix(devDependencies): Fix the problem of missing glob package

### PR DESCRIPTION
**Pull request by xx1124961758**
Resolved the issue of the glob package being unlocated due to its phantom dependency status during dependency installation via pnpm.

### Author should do the followings, if applicable

- [ ] Add tests
- [ ] Run tests
- [ ] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @xx1124961758 

Sorry, I don't understand what exactly is the problem. We recommend using bun or yarn instead of pnpm for this project. So, the pnpm issue is out of scope.

**Comment by xx1124961758** [comment]
> Hi @xx1124961758
> 
> Sorry, I don't understand what exactly is the problem. We recommend using bun or yarn instead of pnpm for the development. So, the pnpm issue is out of scope.

In the project, the glob package was used but was not explicitly declared in the package.json file.

**Comment by yusukebe** [comment]
@xx1124961758 

Thanks, I see. Could you run `bun install`?

**Comment by xx1124961758** [comment]
> @xx1124961758
> 
> Thanks, I see. Could you run `bun install`?

yes, it's ok with 'bun install'

**Comment by yusukebe** [comment]
Hi @xx1124961758 

It wasn't working, so I fixed it myself. Thanks!

**Pull request merged**
