### PR TITLE
feat(validator): introduce nested validation

### PR DESCRIPTION
**Pull request by yusukebe**
This PR introduces "nested validation" for Validator Middleware.

In this PR, we can validate nested JSON structured data using `v.array()` and `v.object()` functions. After much thought and consideration, the result is this API.

For example, there is a nested object like below:

```ts
const data = {
  posts: [
    {
      id: 123,
      title: 'JavaScript',
      tags: ['Workers', 'Deno', 'Bun'],
    },
  ],
  pager: {
    prev: true,
    next: false,
  },
}
```

It will be validated with `v.array()` and `v.object()`:

```ts
app.post(
  '/posts',
  validator((v) => ({
    posts: v.array('posts', (v) => ({
      id: v.json('id').asNumber().isRequired(),
      title: v.json('title'),
      tags: v.json('tags').asArray(),
    })),
    pager: v.object('pager', (v) => ({
      prev: v.json('prev').asBoolean(),
      next: v.json('next').asBoolean(),
    })),
  })),
  (c) => {
    return c.text('Valid!')
  }
)
```

And it also has types:

SS

Isn't it cool? I want to know your opinion.

## Implementation

It has become a little bit complex. There may be something missing or wrong points in this implementation. If you notice any, please review them.

The code for `JSONPathCopy` is based on @ThatOneBro's  and @usualoma 's code.

https://github.com/honojs/hono/pull/508/files#diff-91414c404fd51d6fb8e47ba511fd1a5c410e5fe3e732254f0f6d621175fcd647

This PR related: #584

### CODE REVIEW

**Comment by yusukebe** [comment]
The tests were passed on my environment, but these failed on the CI. I know it's about copying objects. I'll investigate to solve it.

**Comment by ThatOneBro** [comment]
Looks good to me so far! I will look again tomorrow to make sure everything makes sense, but from first glances it looks great. I was able to use nested arrays successfully on CFW 👍

**Comment by usualoma** [comment]
Awesome job!
I agree with these changes!

### Minor issues

I don't think we are testing `asArray` here. Do we need to correct the name of the test?

https://github.com/honojs/hono/pull/592/files#diff-69cfe3c04c26baba3e5078f8d04c7434c55883045ab8bb255a27f09383330f5fR406

**Comment by yusukebe** [comment]
> I don't think we are testing asArray here. Do we need to correct the name of the test?

I forgot to remove them! Thank you!

And, this test fails on the CI, do you know the solution?
https://github.com/honojs/hono/actions/runs/3216097795/jobs/5257654578#step:7:292

It does not fail on my environment. I think this is a problem related to copying objects, but I don't know how to fix it.

**Comment by ThatOneBro** [comment]
> It does not fail on my environment. I think this is a problem related to copying objects, but I don't know how to fix it.

I just tested it in a Docker container, it seems it may be an issue with Ubuntu or Linux in general. On my Mac, the tests do not fail. I will continue looking into it more, hopefully we can figure it out easily.

**Comment by ThatOneBro** [comment]
I created a PR (#598) for this feature branch that should fix the CI issues, it introduces an immutable version of the mergeObjects.

**Comment by yusukebe** [comment]
Hi @ThatOneBro !

Wow cooooool! Tests have been passed. Thank you very much!

I'll merge this PR to the main branch later.

**Pull request merged**
