### PR TITLE
chore(utils): Move cf module

### PR DESCRIPTION
**Pull request by watany-dev**
I've been wondering about this for a while, so I checked `utils/cloudflare` and realized that it would be better to put it as ` adapter/cloudflare-workers`. 

If sharing with pages etc. is in the roadmap, this Refactor is not needed. 

### Author should do the followings, if applicable

- [ ] Add tests
- [x] Run tests
- [ ] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @watany-dev 

This refactoring is good! It is used only for Cloudflare Workers; Pages does not use it. So we can go with it. Can you fix the error? Then, I'll merge it.

**Comment by watany-dev** [comment]
@yusukebe 
Appreciate the review. Yes, I have fixed it, including the lint check.

**Review by yusukebe — COMMENTED** [review]
@watany-dev 

Sorry! One more thing.

I think the file name `utils.ts` is better than `cloudflare.ts`. So how about renaming `cloudflare.ts` to `utils.ts` and `cloudflare.test.ts`?

**Comment by watany-dev** [comment]
@yusukebe 
I tried Rename. Is this OK?

**Review by yusukebe — APPROVED** [review]

**Comment by yusukebe** [comment]
Okay! Let's go with it!

**Pull request merged**
