### PR TITLE
feat(types): improve JSONParsed

### PR DESCRIPTION
**Pull request by m-shaka**
I've improved `JSONParsed` in order to follow the spec of `JSON.stringify` as much as possible.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description

Here is major improvement:
- support tuple type
- handle undefined, symbol, and function type correctly(in array or object). For example
  - convert undefined to null in an array
  - drop keys whose value is undefined 

You can see some actual behaviour in [TS playground](https://www.typescriptlang.org/play/?#code/MYewdgziA2CmB00QHMAUByAZgVzMALgJbgBc6ANAAQBSAygPIBy8E+AToWMoZgJ6qoAlJQC8APkoBvAL6DhAenmVcAE1iZOsFQChQkGAiRp0EXgFsARjDJU6TFu07c+qWuavR4mEG1QAiCD85BSVVdU0dPSg4RBQMU0sYSgBrWF4AbRALACtYAgBdChoGZlYOLh5+SUp0t0TPb18AoPySSgBGWRDKPxk-XXBowzj0MI0wLUycvPxC2xKHcucqygBDNrGIyi7KRR6+gf0Yo3j3JIA3VehsWCncgqK7UscKl2r1yjqPLx9-QMEdntetJ+lEDLFjDg8ERwJRLtdbll7rNHgsyk5Kqh3m0hKIJDJAUpgaDBuCTqMwGpxpNVmw2KteHNivZ0a9+OlNhMVPk5LsiekwNhoNB8iSjsNjAkPOlafTGaiWS9lqhamcGr9moIed0-AKhSKxUMIRgoQRiGAZXSGUynosMS50rjxFJpNq+T09cLRYcjeSJqwtJR8CAngrnktMZJg08ccJnVigyGSrG8R1tsJCfsQUA)

### The author should do the following, if applicable

- [x] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code
- [ ] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @m-shaka 

Awesome! Following the spec of `JSON.stringify` is great.

One thing we have to consider is performance. This change will introduce performance degradation, especially in RPC.

Try to create an app that has many routes with this script:

```ts
import { writeFile } from 'fs'

const count = 200

const generateRoutes = (count: number) => {
  const imports = `
import { Hono } from 'hono';
import { z } from 'zod';
import { zValidator } from '@hono/zod-validator';
`

  const schema = `
const schema = z.object({
  q: z.string()
})\n
`

  let routes = imports + schema + 'export const app = new Hono()\n'
  for (let i = 1; i <= count; i++) {
    routes += `  .get('/route${i}/:id', zValidator('query', schema), (c) => {
    return c.json({
      query: c.req.valid('query'),
      id: c.req.param('id'),
      ok: true
    })
  })\n`
  }
  return routes
}

const routes = generateRoutes(count)

writeFile('app.ts', routes, (err) => {
  if (err) throw err
  console.log(`${count} routes have been written to app.ts`)
})
```

Load this app in another script with `hc`:

```ts
import { app } from './app'
import { hc } from 'hono/client'

const client = hc<typeof app>('/')
```

If with current version `4.4.10`, it can handle over 200 routes in my IDE:

CleanShot 2024-07-04 at 15 07 06@2x

But with this PR, it will throw the error:

CleanShot 2024-07-04 at 15 07 41@2x

Performance issues are often reported in this project, so we must address them. We want a good idea to support both the following specs and better performance. We may be able to ignore this matter and refactor other points (like `hc`) to ensure good performance for RPC. However, we don't want to decrease the performance as much as possible with these JSON things.

@m-shaka @NamesMT Any thoughts?

**Comment by yusukebe** [comment]
Ah, the script includes a validator, so it's better to use this script:

```ts
import { writeFile } from 'fs'

const count = 200

const generateRoutes = (count: number) => {
  let routes = `import { Hono } from 'hono'
  export const app = new Hono()`
  for (let i = 1; i <= count; i++) {
    routes += `  .get('/route${i}/:id', (c) => {
    return c.json({
      ok: true
    })
  })\n`
  }
  return routes
}

const routes = generateRoutes(count)

writeFile('app.ts', routes, (err) => {
  if (err) throw err
  console.log(`${count} routes have been written to app.ts`)
})
```

**Comment by m-shaka** [comment]
Oh, I'll have a look later 👀

**Comment by m-shaka** [comment]
@yusukebe  While I've changed the behaviour of optional keys, it seems to work now.
Now `a?: string` gonna be converted to `a: string | undefined`, but I don't think it's a problem in practical use

**Comment by yusukebe** [comment]
@m-shaka Thanks! I'll check it later.

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@m-shaka 

Great! There is little or no performance degradation. Looks good! I wonder if we should merge this into the current `main` or the `next` branch(for the next minor release, `v4.5`). I'll merge later. Thanks!

**Comment by yusukebe** [comment]
Hi @m-shaka 

This is a `feat` but does not introduce a new future for users. So, I'll merge this now into the `main` and include it in a patch release. Thanks!

**Pull request merged**
