### PR TITLE
feat(logger): support `NO_COLOR`

### PR DESCRIPTION
**Pull request by ryuapp**
Related: https://github.com/honojs/hono/pull/2007
This PR adds `utils/colors.ts`.

We have to support `NO_COLOR`.

### Author should do the followings, if applicable

- [x] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by yusukebe** [comment]
@ryuapp 

This is great. I'll review the details later. This will be introduced in the next "minor"  version.

**Review by yusukebe — APPROVED** [review]
Looks good to me!

**Comment by yusukebe** [comment]
Hi @ryuapp !

Thanks. I'll merge this into the "next" branch for the `v4.1.0`. It will be released maybe soon!

**Comment by StuartMoncrieff** [comment]
Can we please add this to the Hono docs at (https://hono.dev/docs/middleware/builtin/logger)?

```markdown
# Tip

To disable _status code coloring_, you can set a "NO_COLOR" environment variable. This is described at (https://no-color.org/).
```

**Comment by yusukebe** [comment]
Hi @StuartMoncrieff 

Adding this to the docs is a good idea. If so, we have to write the caution that it does not work on environments such as Cloudflare, which does not support `NO_COLOR`: related to #3752 #3751

@StuartMoncrieff Can you create a PR for it on [honojs/website](https://github.com/honojs/website)? That will be helpful.

**Comment by StuartMoncrieff** [comment]
Thanks @yusukebe! I have created a pull request: <https://github.com/honojs/website/pull/553>.

**Pull request merged**
