### PR TITLE
fix(cloudflare-pages): fix type incompatibility

### LINKED ISSUE #833: Cloudflare Pages adapter is incompatible with newer workerd's `PagesFunction` type
With the following `tsconfig.json` and `index.ts`, TypeScript produces a compile error.

```json5
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "lib": ["esnext"],
    "moduleResolution": "node",
    // note the compatibility date (I need to set this in order to get the correct type for FormData).
    // if I omit the date, the error disappears.
    "types": ["@cloudflare/workers-types/2022-08-04"],
    "noEmit": true
  }
}
```

```typescript
import { Hono } from "hono";
import { handle } from "hono/cloudflare-pages";

const app = new Hono();
app.get("/hello", (c) => c.text("Hello from Hono!"));

export const onRequest: PagesFunction = handle(app);
```

The error message is:

```console
index.ts:7:14 - error TS2322: Type '(eventContext: EventContext<{}, string, {}>) => Response | Promise<Response>' is not assignable to type 'PagesFunction<unknown, any, Record<string, unknown>>'.
  Types of parameters 'eventContext' and 'context' are incompatible.
    Type 'EventContext<unknown, any, Record<string, unknown>>' is not assignable to type 'EventContext<{}, string, {}>'.
      The types of 'request.fetcher.fetch' are incompatible between these types.
        Type '(input: RequestInfo, init?: RequestInit<RequestInitCfProperties>) => Promise<Response>' is not assignable to type '(input: import("/Users/ynkt/tmp/repro-hono/node_modules/@cloudflare/workers-types/index").RequestInfo, init?: import("/Users/ynkt/tmp/repro-hono/node_modules/@cloudflare/workers-types/index").RequestInit<import("/Users/ynkt/tmp/repro-hono/node_modules/@cloudflare/workers-types/index").RequestInitCfProperties>) => Pr...'.
          Types of parameters 'input' and 'input' are incompatible.
            Type 'import("/Users/ynkt/tmp/repro-hono/node_modules/@cloudflare/workers-types/index").RequestInfo' is not assignable to type 'RequestInfo'.
              Type 'Request<unknown>' is not assignable to type 'RequestInfo'.
                Type 'import("/Users/ynkt/tmp/repro-hono/node_modules/@cloudflare/workers-types/index").Request<unknown>' is not assignable to type 'Request<unknown>'.
                  The types of 'fetcher.fetch' are incompatible between these types.
                    Type '(input: import("/Users/ynkt/tmp/repro-hono/node_modules/@cloudflare/workers-types/index").RequestInfo, init?: import("/Users/ynkt/tmp/repro-hono/node_modules/@cloudflare/workers-types/index").RequestInit<import("/Users/ynkt/tmp/repro-hono/node_modules/@cloudflare/workers-types/index").RequestInitCfProperties>) => Pr...' is not assignable to type '(input: RequestInfo, init?: RequestInit<RequestInitCfProperties>) => Promise<Response>'.
                      Types of parameters 'init' and 'init' are incompatible.
                        Type 'RequestInit<RequestInitCfProperties>' is not assignable to type 'import("/Users/ynkt/tmp/repro-hono/node_modules/@cloudflare/workers-types/index").RequestInit<import("/Users/ynkt/tmp/repro-hono/node_modules/@cloudflare/workers-types/index").RequestInitCfProperties>'.
                          Types of property 'body' are incompatible.
                            Type 'BodyInit' is not assignable to type 'import("/Users/ynkt/tmp/repro-hono/node_modules/@cloudflare/workers-types/index").BodyInit'.
                              Type 'FormData' is not assignable to type 'BodyInit'.
                                Type 'FormData' is not assignable to type 'import("/Users/ynkt/tmp/repro-hono/node_modules/@cloudflare/workers-types/index").FormData'.
                                  The types returned by 'get(...)' are incompatible between these types.
                                    Type 'string | File' is not assignable to type 'string'.
                                      Type 'File' is not assignable to type 'string'.

7 export const onRequest: PagesFunction = handle(app);
               ~~~~~~~~~
```
I don't have time to investigate further right now (time to go to bed here lol), but will look into this tomorrow's night.

### PR DESCRIPTION
**Pull request by yusukebe**
This will fix #833

### CODE REVIEW

**Comment by yudai-nkt** [comment]
Thanks for the fix, it works with both newer compatibility date and old one! I'm not sure if defining `EventContext` on Hono's side rather than `import`ing it from `@cloudflare/workers-types`, but we can revisit this if another problem occurs in the future. Let's go this way for the time being.

**Comment by yudai-nkt** [comment]
FWIW, the oldest compatibility date that causes the error is 2022-01-31, but I haven't yet figured out which part of the change is the reason.

<details>
    <summary>See the diff</summary>

```diff
===================================================================
--- 2021-11-03
+++ 2022-01-31
@@ -449,31 +449,21 @@
   blobs?: ((ArrayBuffer | string) | null)[];
 }
 declare class Event {
   constructor(type: string, init?: EventInit);
-  /** Returns the type of event, e.g. "click", "hashchange", or "submit". */
-  readonly type: string;
-  /** Returns the event's phase, which is one of NONE, CAPTURING_PHASE, AT_TARGET, and BUBBLING_PHASE. */
-  readonly eventPhase: number;
-  /** Returns true or false depending on how event was initialized. True if event invokes listeners past a ShadowRoot node that is the root of its target, and false otherwise. */
-  readonly composed: boolean;
-  /** Returns true or false depending on how event was initialized. True if event goes through its target's ancestors in reverse tree order, and false otherwise. */
-  readonly bubbles: boolean;
-  /** Returns true or false depending on how event was initialized. Its return value does not always carry meaning, but true can indicate that part of the operation during which event was dispatched, can be canceled by invoking the preventDefault() method. */
-  readonly cancelable: boolean;
-  /** Returns true if preventDefault() was invoked successfully to indicate cancelation, and false otherwise. */
-  readonly defaultPrevented: boolean;
-  /** @deprecated */
-  readonly returnValue: boolean;
-  /** Returns the object whose event listener's callback is currently being invoked. */
-  readonly currentTarget?: EventTarget;
-  /** @deprecated */
-  readonly srcElement?: EventTarget;
-  /** Returns the event's timestamp as the number of milliseconds measured relative to the time origin. */
-  readonly timeStamp: number;
-  /** Returns true if event was dispatched by the user agent, and false otherwise. */
-  readonly isTrusted: boolean;
-  cancelBubble: boolean;
+  get type(): string;
+  get eventPhase(): number;
+  get composed(): boolean;
+  get bubbles(): boolean;
+  get cancelable(): boolean;
+  get defaultPrevented(): boolean;
+  get returnValue(): boolean;
+  get currentTarget(): EventTarget | undefined;
+  get srcElement(): EventTarget | undefined;
+  get timeStamp(): number;
+  get isTrusted(): boolean;
+  get cancelBubble(): boolean;
+  set cancelBubble(value: boolean);
   stopImmediatePropagation(): void;
   preventDefault(): void;
   stopPropagation(): void;
   composedPath(): EventTarget[];
@@ -525,18 +515,16 @@
   handleEvent: (event: Event) => any | undefined;
 }
 declare class AbortController {
   constructor();
-  /** Returns the AbortSignal object associated with this object. */
-  readonly signal: AbortSignal;
+  get signal(): AbortSignal;
   abort(reason?: any): void;
 }
 declare abstract class AbortSignal extends EventTarget {
   static abort(reason?: any): AbortSignal;
   static timeout(delay: number): AbortSignal;
-  /** Returns true if this AbortSignal's AbortController has signaled to abort, and false otherwise. */
-  readonly aborted: boolean;
-  readonly reason: any;
+  get aborted(): boolean;
+  get reason(): any;
   throwIfAborted(): void;
 }
 declare interface Scheduler {
   wait(delay: number, maybeOptions?: SchedulerWaitOptions): Promise<void>;
@@ -551,10 +539,10 @@
   constructor(
     bits?: ((ArrayBuffer | ArrayBufferView) | string | Blob)[],
     options?: BlobOptions
   );
-  readonly size: number;
-  readonly type: string;
+  get size(): number;
+  get type(): string;
   slice(start?: number, end?: number, type?: string): Blob;
   arrayBuffer(): Promise<ArrayBuffer>;
   text(): Promise<string>;
   stream(): ReadableStream;
@@ -567,10 +555,10 @@
     bits: ((ArrayBuffer | ArrayBufferView) | string | Blob)[] | undefined,
     name: string,
     options?: FileOptions
   );
-  readonly name: string;
-  readonly lastModified: number;
+  get name(): string;
+  get lastModified(): number;
 }
 declare interface FileOptions {
   type?: string;
   lastModified?: number;
@@ -590,10 +578,9 @@
 declare interface CacheQueryOptions {
   ignoreMethod?: boolean;
 }
 declare abstract class Crypto {
-  /** Available only in secure contexts. */
-  readonly subtle: SubtleCrypto;
+  get subtle(): SubtleCrypto;
   getRandomValues<
     T extends
       | Int8Array
       | Uint8Array
@@ -791,25 +778,25 @@
 declare class DigestStream extends WritableStream<
   ArrayBuffer | ArrayBufferView
 > {
   constructor(algorithm: string | SubtleCryptoHashAlgorithm);
-  readonly digest: Promise<ArrayBuffer>;
+  get digest(): Promise<ArrayBuffer>;
 }
 declare class TextDecoder {
   constructor(decoder?: string, options?: TextDecoderConstructorOptions);
   decode(
     input?: ArrayBuffer | ArrayBufferView,
     options?: TextDecoderDecodeOptions
   ): string;
-  readonly encoding: string;
-  readonly fatal: boolean;
-  readonly ignoreBOM: boolean;
+  get encoding(): string;
+  get fatal(): boolean;
+  get ignoreBOM(): boolean;
 }
 declare class TextEncoder {
   constructor();
   encode(input?: string): Uint8Array;
   encodeInto(input: string, buffer: Uint8Array): TextEncoderEncodeIntoResult;
-  readonly encoding: string;
+  get encoding(): string;
 }
 declare interface TextDecoderConstructorOptions {
   fatal: boolean;
   ignoreBOM: boolean;
@@ -952,10 +939,10 @@
   | Blob
   | URLSearchParams
   | FormData;
 declare abstract class Body {
-  readonly body: ReadableStream | null;
-  readonly bodyUsed: boolean;
+  get body(): ReadableStream | null;
+  get bodyUsed(): boolean;
   arrayBuffer(): Promise<ArrayBuffer>;
   text(): Promise<string>;
   json<T>(): Promise<T>;
   formData(): Promise<FormData>;
@@ -965,16 +952,16 @@
   constructor(body?: BodyInit | null, init?: ResponseInit);
   static redirect(url: string, status?: number): Response;
   static json(any: any, maybeInit?: ResponseInit | Response): Response;
   clone(): Response;
-  readonly status: number;
-  readonly statusText: string;
-  readonly headers: Headers;
-  readonly ok: boolean;
-  readonly redirected: boolean;
-  readonly url: string;
-  readonly webSocket: WebSocket | null;
-  readonly cf?: any;
+  get status(): number;
+  get statusText(): string;
+  get headers(): Headers;
+  get ok(): boolean;
+  get redirected(): boolean;
+  get url(): string;
+  get webSocket(): WebSocket | null;
+  get cf(): any | undefined;
 }
 declare interface ResponseInit {
   status?: number;
   statusText?: string;
@@ -986,20 +973,15 @@
 declare type RequestInfo = Request | string | URL;
 declare class Request<CfHostMetadata = unknown> extends Body {
   constructor(input: RequestInfo, init?: RequestInit);
   clone(): Request<CfHostMetadata>;
-  /** Returns request's HTTP method, which is "GET" by default. */
-  readonly method: string;
-  /** Returns the URL of request as a string. */
-  readonly url: string;
-  /** Returns a Headers object consisting of the headers associated with request. Note that headers added in the network layer by the user agent will not be accounted for in this object, e.g., the "Host" header. */
-  readonly headers: Headers;
-  /** Returns the redirect mode associated with request, which is a string indicating how redirects for the request will be handled during fetching. A request will follow redirects by default. */
-  readonly redirect: string;
-  readonly fetcher: Fetcher | null;
-  /** Returns the signal associated with request, which is an AbortSignal object indicating whether or not request has been aborted, and its abort event handler. */
-  readonly signal: AbortSignal;
-  readonly cf?: IncomingRequestCfProperties<CfHostMetadata>;
+  get method(): string;
+  get url(): string;
+  get headers(): Headers;
+  get redirect(): string;
+  get fetcher(): Fetcher | null;
+  get signal(): AbortSignal;
+  get cf(): IncomingRequestCfProperties<CfHostMetadata> | undefined;
 }
 declare interface RequestInit<
   CfType = IncomingRequestCfProperties | RequestInitCfProperties
 > {
@@ -1365,9 +1347,9 @@
       value?: undefined;
     };
 /** This Streams API interface represents a readable stream of byte data. The Fetch API offers a concrete instance of a ReadableStream through the body property of a Response object. */
 declare interface ReadableStream<R = any> {
-  readonly locked: boolean;
+  get locked(): boolean;
   cancel(reason?: any): Promise<void>;
   getReader(): ReadableStreamDefaultReader<R>;
   getReader(options: ReadableStreamGetReaderOptions): ReadableStreamBYOBReader;
   pipeThrough<T>(
@@ -1396,16 +1378,16 @@
   ): ReadableStream<R>;
 };
 declare class ReadableStreamDefaultReader<R = any> {
   constructor(stream: ReadableStream);
-  readonly closed: Promise<void>;
+  get closed(): Promise<void>;
   cancel(reason?: any): Promise<void>;
   read(): Promise<ReadableStreamReadResult<R>>;
   releaseLock(): void;
 }
 declare class ReadableStreamBYOBReader {
   constructor(stream: ReadableStream);
-  readonly closed: Promise<void>;
+  get closed(): Promise<void>;
   cancel(reason?: any): Promise<void>;
   read<T extends ArrayBufferView>(
     view: T
   ): Promise<ReadableStreamReadResult<T>>;
@@ -1461,18 +1443,18 @@
   constructor(
     underlyingSink?: UnderlyingSink,
     queuingStrategy?: QueuingStrategy
   );
-  readonly locked: boolean;
+  get locked(): boolean;
   abort(reason?: any): Promise<void>;
   close(): Promise<void>;
   getWriter(): WritableStreamDefaultWriter<W>;
 }
 declare class WritableStreamDefaultWriter<W = any> {
   constructor(stream: WritableStream);
-  readonly closed: Promise<void>;
-  readonly ready: Promise<void>;
-  readonly desiredSize: number | null;
+  get closed(): Promise<void>;
+  get ready(): Promise<void>;
+  get desiredSize(): number | null;
   abort(reason?: any): Promise<void>;
   close(): Promise<void>;
   write(chunk?: W): Promise<void>;
   releaseLock(): void;
@@ -1482,10 +1464,10 @@
     transformer?: Transformer<I, O>,
     writableStrategy?: QueuingStrategy<I>,
     readableStrategy?: QueuingStrategy<O>
   );
-  readonly readable: ReadableStream<O>;
-  readonly writable: WritableStream<I>;
+  get readable(): ReadableStream<O>;
+  get writable(): WritableStream<I>;
 }
 declare class FixedLengthStream extends IdentityTransformStream {
   constructor(expectedLength: number | bigint);
 }
@@ -1601,20 +1583,30 @@
   fromTrace(item: TraceItem): TraceMetrics;
 }
 declare class URL {
   constructor(url: string | URL, base?: string | URL);
-  href: string;
-  readonly origin: string;
-  protocol: string;
-  username: string;
-  password: string;
-  host: string;
-  hostname: string;
-  port: string;
-  pathname: string;
-  search: string;
-  readonly searchParams: URLSearchParams;
-  hash: string;
+  get href(): string;
+  set href(value: string);
+  get origin(): string;
+  get protocol(): string;
+  set protocol(value: string);
+  get username(): string;
+  set username(value: string);
+  get password(): string;
+  set password(value: string);
+  get host(): string;
+  set host(value: string);
+  get hostname(): string;
+  set hostname(value: string);
+  get port(): string;
+  set port(value: string);
+  get pathname(): string;
+  set pathname(value: string);
+  get search(): string;
+  set search(value: string);
+  get searchParams(): URLSearchParams;
+  get hash(): string;
+  set hash(value: string);
   toString(): string;
   toJSON(): string;
 }
 declare class URLSearchParams {
@@ -1732,16 +1724,12 @@
   static readonly READY_STATE_CONNECTING: number;
   static readonly READY_STATE_OPEN: number;
   static readonly READY_STATE_CLOSING: number;
   static readonly READY_STATE_CLOSED: number;
-  /** Returns the state of the WebSocket object's connection. It can have the values described below. */
-  readonly readyState: number;
-  /** Returns the URL that was used to establish the WebSocket connection. */
-  readonly url: string | null;
-  /** Returns the subprotocol selected by the server, if any. It can be used in conjunction with the array form of the constructor's second argument to perform subprotocol negotiation. */
-  readonly protocol: string | null;
-  /** Returns the extensions selected by the server, if any. */
-  readonly extensions: string | null;
+  get readyState(): number;
+  get url(): string | null;
+  get protocol(): string | null;
+  get extensions(): string | null;
 }
 declare const WebSocketPair: {
   new (): {
     0: WebSocket;
```

</details>

**Comment by yudai-nkt** [comment]
Wait, the following patch to `handler.d.ts` (I mean, manually editing node_modules) also removes the error.

```diff
+ /// <reference types="@cloudflare/workers-types" />
- import type { EventContext } from '@cloudflare/workers-types';
  import type { Hono } from '../../hono';
  import type { Env } from '../../types';
  export declare const handle: <E extends Env>(app: Hono<E, import("../../types").Route, {}, {}>) => (eventContext: EventContext<{}, string, {}>) => Response | Promise<Response>;
```

This seems to be the canonical solution in the sense that this uses a type definition in `@cloudflare/workers-types`. However, I don't know the difference between `import`ing types and triple-slash directive.

**Comment by yusukebe** [comment]
The things related to Types are tricky:(

> I'm not sure if defining EventContext on Hono's side rather than importing it from @cloudflare/workers-types,

Using `EventContext` imported from `@cloudflare/workers-types` as you did, I got an error, so I solved it by defining a minimal and compatible EventContext on Hono side. I think the way I did looks good, but I will look into it tomorrow to see if there are any side effects. And also about triple-slash.

**Comment by yudai-nkt** [comment]
I noticed the part you quoted wasn't a complete sentence, but I guess you understand my intention (now fixed in the original comment).

> I will look into it tomorrow to see if there are any side effects. And also about triple-slash.

Sorry for troubling you, but much appreciated!

**Comment by yusukebe** [comment]
Hi @yudai-nkt !

It seems to be better to use "triple-slash". With my implementation writing `EventContext` in Hono side, that will be `any` in pages functions:

SS

But, with tripe-slash, it will be `EventContext` correctly:

SS

You are right, we should use the `@cloudflare/workers-types` type. I think triple-slash is appropriate in this case since using `import` will cause a mismatch in the Request type.

**Comment by yusukebe** [comment]
Ah, CI failed. Looks like triple-slash is polluting the `Request` and other APIs.

**Comment by yusukebe** [comment]
Hi @stefanmaric !

Do you know of any good solutions?

**Comment by yudai-nkt** [comment]
> With my implementation writing `EventContext` in Hono side, that will be `any` in pages functions:

This was a good catch, but sad to see CI fails. 😢

I thought #733 removed prototype pollution, so the result is kinda surprising.

**Comment by yudai-nkt** [comment]
By the way, `yarn test` seems to run tests in `deno_dist`, `test_bun`, `test_lagon`, `test_node`, `test_fastly`, and `test_deno` and fails. Is this intended?

**Comment by yusukebe** [comment]
OK, no response from stefan, but I'll merge it.

@stefanmaric If you have any feedback later, create the issue, let us know!

**Pull request merged**
