### PR TITLE
Refactoring base64 logic for JWT

### PR DESCRIPTION
**Pull request by Code-Hex**
- Import base64 logic from https://github.com/Code-Hex/firebase-auth-cloudflare-workers/blob/main/src/base64.ts
- Decoding speed will be faster almost 2x
- Accept to encode RFC 3548 examples
- This PR is created at YAPC::Japan::Kyoto 2023 🔥

### CODE REVIEW

**Comment by Code-Hex** [comment]
I fix them 🙏

**Comment by Code-Hex** [comment]
@yusukebe I passed all tests in middleware

```
 PASS  src/middleware/etag/index.test.ts
 PASS  src/middleware/bearer-auth/index.test.ts
 PASS  src/middleware/pretty-json/index.test.ts
 PASS  src/middleware/cors/index.test.ts
 PASS  src/middleware/basic-auth/index.test.ts
 PASS  src/middleware/compress/index.test.ts
 PASS  src/middleware/html/index.test.ts
 PASS  src/middleware/cache/index.test.ts
 PASS  src/middleware/powered-by/index.test.ts
 PASS  src/middleware/jsx/index.test.tsx
 PASS  src/middleware/jwt/index.test.ts
 PASS  src/middleware/logger/index.test.ts
```

**Comment by yusukebe** [comment]
Hi @Code-Hex !

Looks good to me!

@akiym Can you review it?:)

**Review by akiym — APPROVED** [review]
LGTM, but I just see this PR's changes :)

**Comment by yusukebe** [comment]
Thanks @akiym !

I'll add you as a co-author for this PR.

**Pull request merged**
