### PR TITLE
denied return void from async handler and return context from next

### PR DESCRIPTION
**Pull request by zohayrslileh**
### Author should do the followings, if applicable

- [ ] Add tests
- [ ] Run tests
- [ ] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by yusukebe** [comment]
@zohayrslileh 

I don't know what your intention was with this, but it is not the spec, so I'm closing it.

**Comment by zohayrslileh** [comment]
As you can see here for typescript everything is correct, but it will not work because return is void
image

When calling next, the return is void according to the types, but in reality it is a context object
image

thanks

**Comment by yusukebe** [comment]
Hi @zohayrslileh 

> As you can see here for typescript everything is correct, but it will not work because return is void

You are correct; I want to make it show an error if the Response is not returned in a **handler**. However, since it is the `MiddlewareHandler,` it should allow `void.`

> When calling next, the return is void according to the types, but in reality it is a context object

Indeed. However, I don't expect to use the returned context object, so I'm making it `void`.

**Comment by zohayrslileh** [comment]
Okay, I understand that, but if the next function return context object. The middleware will not return a void under any circumstances

Because middleware accepts void only for the next function

**Comment by yusukebe** [comment]
@zohayrslileh 

Thanks for understanding and your advice. Everyone has different ideas about the types. I won't change it now, but I may change the return type next, as you suggest.

**Pull request closed without merging**
