### PR TITLE
feat(adapter/alibaba-cloud-fc3): add alibaba cloud function compute 3.0 adapater support

### PR DESCRIPTION
**Pull request by rwv**
### The author should do the following, if applicable

- [x] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code
- [x] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

## Docs

https://www.alibabacloud.com/help/en/functioncompute/fc-3-0/

## Tests
* Unit test at `src/adapter/aliyun-fc3/handler.test.ts`
* Verified basic functionality with real-world testing on GitHub Actions. https://github.com/rwv/hono/actions/runs/11718662874

### Differences with Hono's Getting Started with Aliyun Function Compute

The primary difference between this adapter and the setup described in [Hono's official documentation](https://hono.dev/docs/getting-started/ali-function-compute) lies in the deployment method for Alibaba Cloud Function Compute (FC).

- **Debian Docker Container (Hono Documentation):** The official guide provides a setup using a Debian-based Docker container to deploy Hono applications on Aliyun FC. This approach involves creating a custom Docker environment that packages and runs the application, offering flexibility with OS-level configurations.

- **Native Node.js Environment (This Adapter):** In contrast, this adapter uses Alibaba Cloud's Node.js runtime environment directly, similar to AWS Lambda. It leverages Alibaba Cloud FC's built-in Node.js support, bypassing the need for a custom Docker container. This approach simplifies deployment by focusing on function code rather than container management, making it faster to set up and closer in experience to other serverless platforms like AWS Lambda.

### CODE REVIEW

**Comment by rwv** [comment]
The renaming and runtime test are complete. Could you please review and let me know if there’s anything else that needs to be adjusted? Thanks!

**Comment by yusukebe** [comment]
Hi @rwv 

It's hard to decide if we should accept this PR because it's possible that no one can maintain this adapter. At least, I don't know much about Aliyun Function Compute. You may be able to maintain it, but that may not be possible in the future, and it will be hard for me to maintain it.

**Comment by rwv** [comment]
Hi,

Thank you for considering this PR. I understand the concern regarding long-term maintenance, especially since Aliyun Function Compute might not be widely familiar to the core team. I’d be glad to help maintain this adapter for as long as possible. Additionally, I’ve achieved 100% test coverage on this adapter, which should help with ensuring stability and making future maintenance easier. I can also provide documentation and implementation details to further support the team. If there are any specific concerns or suggestions, please let me know, and I’d be happy to address them.

**Comment by rwv** [comment]
I maintain the Alibaba Cloud FC3 adapter in a separate repository: [rwv/hono-alibaba-cloud-fc3-adapter](https://github.com/rwv/hono-alibaba-cloud-fc3-adapter). Perhaps we could mention this in the documentation as an external resource, so users have access without adding maintenance overhead to the core repository.

Let me know your thoughts!

**Comment by yusukebe** [comment]
@rwv 

Thanks! Is it a good idea to update this doc? https://hono.dev/docs/getting-started/ali-function-compute

**Comment by rwv** [comment]
Updated doc @ https://github.com/honojs/website/pull/544

**Pull request closed without merging**
