### PR TITLE
feat(helper/streaming): Support Promise<string> or (async) JSX.Element in streamSSE

### PR DESCRIPTION
**Pull request by usualoma**
#3319

This change allows you to use "hono/jsx" to write the following in streamSSE. I don't think there are many use cases, but the changes on the `helper/streaming/sse.ts` side are also small and could be added to the implementation.

```tsx
streamSSE(c, async (stream) => {
  await stream.writeSSE({ data: <div>Hello</div> })
})
```

```tsx
streamSSE(c, async (stream) => {
  await stream.writeSSE({
    data: (
      <ErrorBoundary fallback={<div>Error</div>}>
        <AsyncComponent />
      </ErrorBoundary>
    ),
  })
})
```

### The author should do the following, if applicable

- [x] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code

### CODE REVIEW

**Comment by usualoma** [comment]
@yusukebe @watany-dev @sor4chi 
What do you think?

**Comment by yusukebe** [comment]
Hey @usualoma 

It is interesting that JSX can be written in SSE's `data` property. With [the HTMX SSE extension](https://github.com/bigskysoftware/htmx-extensions/blob/main/src/sse/README.md), the `data` property will be rendered as HTML. We can write the following code.

```tsx
import { Hono } from 'hono'
import { streamSSE } from 'hono/streaming'

const app = new Hono()

app.get('/', (c) => {
  return c.html(
    <html>
      <head>
        <script src="https://unpkg.com/htmx.org@2.0.2"></script>
        <script src="https://unpkg.com/htmx-ext-sse@2.2.2/sse.js"></script>
      </head>
      <body>
        <div hx-ext="sse" sse-connect="/event-source" sse-swap="EventName"></div>
      </body>
    </html>
  )
})

app.get('/event-source', (c) => {
  return streamSSE(c, async (stream) => {
    while (true) {
      await stream.writeSSE({
        data: (
          <div>
            <b>It's</b> {new Date().toISOString()}
          </div>
        ),
        event: 'EventName'
      })
      await stream.sleep(1000)
    }
  })
})

export default app
```

I like this feature.

**Comment by sor4chi** [comment]
Hello, @yusukebe and @usualoma.

https://github.com/honojs/hono/pull/1913

I think when I proposed something similar in this PR before, the conclusion was that it was not necessary because it could be done by piping with `renderToReadableStream`, but what is the difference between this PR and that one?
I'm sorry I haven't fully understood it :)

Is it because you can't use `renderToReadableStream` with SSE?

**Comment by usualoma** [comment]
@sor4chi  Thank youuu.
Maybe it's time to re-evaluate #1913!

### SSE

> Is it because you can't use renderToReadableStream with SSE?

Yes, the main reason is as you pointed out, SSE cannot simply use `renderToReadableStream` to output. Also, in order to execute the `script` element output by `Suspense`, code like the following comment may also be required, and I believe there are many environments where `renderToReadableStream` is not suitable.

### stream

As for the stream referenced in #1913, it can be simply piped with renderToReadableStream. And in general, script elements output by Suspense are also executed without any additional implementation.

However, there are some APPs that can be written more simply by #1913, and considering the consistency with SSE, I feel that it would be better to reopen #1913 and merge it.



(Sorry, I'm submitting this in the middle of a bit of a children's event, but that's the way I see it)

**Comment by usualoma** [comment]
We should consider whether or not to re-evaluate #1913, but for now, in this pull request, I refactored the duplicated parts in context.ts and sse.ts so that one line of resolveCallback is all that is needed.

I think this refactoring will also simplify the implementation of #1913.

**Comment by sor4chi** [comment]
Thank you for your answer, I see what you mean.
Let's discuss [#1913](https://github.com/honojs/hono/pull/1913) after this has been merged!

In the meantime, I'm all for this idea.

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@usualoma @sor4chi Thank you!

I'll create a `next` branch for the next new minor release `v4.6.0` later. After that, I'll merg this into it!

**Pull request merged**
