### PR TITLE
feat(timing): allow crossOrigin in TimingOptions to be a function

### PR DESCRIPTION
**Pull request by jonahsnider**
Currently, `hono/timing` allows you to specify a value for `crossOrigin` in `TimingOptions` which is used to define the `Timing-Allow-Origin` header. In one of my apps, I wanted to change what origins are allowed programmatically (similar to how you might want to set different CORS headers depending on what route is triggered). This PR support for that.

### Author should do the followings, if applicable

- [ ] Add tests
- [ ] Run tests
- [x] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @jonahsnider !

This is a good feature! However, we must add a test. Can you add it?

**Comment by jonahsnider** [comment]
Yes, I'll try and add a test some time this weekend

**Comment by jonahsnider** [comment]
@yusukebe apologies for the big delay! I just added a test for the previously existing `crossOrigin` functionality, as well as the new behavior this PR adds. Please let me know if I should structure the test differently or make any other modifications.

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
Hi @jonahsnider

> @yusukebe apologies for the big delay!

No worry! I've rebased this into the next branch for the next minor release, v4.3.0. I'll merge now. Thanks!

**Comment by jonahsnider** [comment]
Sounds good, thanks!

**Pull request merged**
