### PR TITLE
feat(validator): support `v.queries`

### LINKED ISSUE #622: [Validator] Support `queries`
We have to support multiple queries with `c.queries()`.

### PR DESCRIPTION
**Pull request by yusukebe**
Close #622

### CODE REVIEW

**Comment by ThatOneBro** [comment]
Looks good so far! I want to test it a bit more though, so I will let you know my full feedback after trying to use it and break it 😆

**Comment by yusukebe** [comment]
Hi @ThatOneBro !

I want to merge, do you have something to do?

**Comment by ThatOneBro** [comment]
Hi @yusukebe ! Sorry for the late reply! Looks good to me. Good job. I'll be using it some more soon and will open an issue if anything comes up 👍

**Comment by yusukebe** [comment]
Alright! I'll merge this!

**Pull request merged**
