### PR TITLE
refactor(utils/body): minor cleanup

### PR DESCRIPTION
**Pull request by MathurAditya724**
Some minor changes I suggested @fzn0x in this #2675. He might have forgotten to include these

### The author should do the following, if applicable

- [x] Add tests
- [x] Run tests
- [ ] `bun denoify` to generate files for Deno
- [x] `bun run format:fix && bun run lint:fix` to format the code

### CODE REVIEW

**Comment by MathurAditya724** [comment]
Here is the comment for reference - https://github.com/honojs/hono/pull/2675#discussion_r1603802350

**Review by fzn0x — APPROVED** [review]
Thanks!

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@MathurAditya724 

Thanks! Merging now.

**Pull request merged**
