### PR TITLE
chore: remove rimraf and use bun shell

### PR DESCRIPTION
**Pull request by nakasyou**
I replaced rimraf with Bun shell.
Bun has OS-independent `rm -rf`, so we can delete rimraf as a dependency.
### The author should do the following, if applicable

- [ ] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code
- [ ] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
Hey @nakasyou 

Interesting! It's good to reduce dependencies and actively use Bun features. Thanks. I will merge it now.

**Comment by mountainash** [comment]
If you are making this change, can I suggest changing `"node": ">=16.0.0"` to bun with a version number greater than when the shell commands were enabled?

**Comment by yusukebe** [comment]
Hi @mountainash 

What specific changes would you like to add?

**Comment by mountainash** [comment]
While [it's not supported yet](https://github.com/oven-sh/bun/issues/5846) I'd consider adding something like, to hint to future devs that you'll need bun to run this project (not Node.JS).

```
	"engines": {
		"bun": ">>=1.1.5"
	}
```

**Comment by yusukebe** [comment]
@mountainash 

Ah, it's interesting. We don't have to add it into `package.json` right now, but when Bun supports it, we should do that.

**Pull request merged**
