### PR TITLE
feat(req): introduce `c.req.path`

### PR DESCRIPTION
**Pull request by yusukebe**
This PR introduces the property `path` for HonoRequest.

This simple feature allows you to get the URL's path by accessing `c.req.path`.

```ts
app.get('/search', (c) => c.text(c.req.path)) // "search"
```

This feature is what many users wanted. This is good because there is no performance degradation, only a slight increase in file size. There are some API changes, but they are used internally, so there are no problems.

### CODE REVIEW

**Comment by usualoma** [comment]
Hi @yusukebe!

I think `c.req.path` is a nice feature!

As I mentioned in my comment below, I believe that "usually clients do not send fragments" and "even if an evil client sends them, there is no need to cut them," but should we cut them?
https://github.com/honojs/hono/pull/498#pullrequestreview-1096123598

**Comment by yusukebe** [comment]
@usualoma 

Thanks for your comment.

You are right! We don't have to cut fragments, and we can remove `removeFragment` from `url.ts`. Great!

**Comment by yusukebe** [comment]
PS.

Previously `getQueryParam()` cut fragments, but there is no need for that, and `URLSearchParams` does not cut fragments either.

**Comment by yusukebe** [comment]
I'll merge it.

**Comment by usualoma** [comment]
👍

**Pull request merged**
