### PR TITLE
feat(utils/color): support cloudflare workers (edge)

### PR DESCRIPTION
**Pull request by EdamAme-x**
Closes: https://github.com/honojs/hono/issues/3751

### The author should do the following, if applicable

- [x] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code
- [x] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @EdamAme-x 

Thank you for the PR. But I can't agree on this way using `NO_COLOR` in `c.env`. It will be confusing if someone uses `NO_COLOR` in `c.env` for another purpose. I think the better way is to create `colorized` option for the Logger middleware and write it like this:

```ts
const app = new Hono<{
  Bindings: {
    NO_COLOR: boolean
  }
}>()

app.use(async (c, next) => {
  return logger(undefined, {
    colorized: !c.env.NO_COLOR,
  })
})
```

But, I'm not sure it is best to add options for the second arg of `logger`.

**Comment by yusukebe** [comment]
We use `NO_COLOR` variable in `process.env` since it's de facto standard on the Node.js environment:

https://no-color.org/

But, I think we don't have the manner in Cloudflare Workers.

**Comment by EdamAme-x** [comment]
@kingmesel
What do you think?

**Comment by kingmesal** [comment]
My perspective is that the simpler and more consistent, the solution the better.

I think if it were on the `c.env` it is the simplest, but I can understand the argument that it is possible (albeit highly unlikely) that someone has used an `c.env.NO_COLOR` somewhere.

Passing in options is useful as it makes it pretty easy for people to find and alter the logger functionality, which I think is probably the better reason to use that approach over the `c.env` directly.

**Comment by StuartMoncrieff** [comment]
I have created a PR to update the website with a tip on using the `NO_COLOR` environment variable to disable ANSI escape codes in the output from the build-in logger middleware (<https://github.com/honojs/website/pull/553>).

@kingmesal has [noted](https://github.com/honojs/hono/issues/3751) that the default logging behaviour on CloudFlare Workers is to _not_ have colored log output, which makes this PR unnecessary (sorry @EdamAme-x!).

Note that the default behavior of the logger on CloudFlare Workers is different to Node/Bun/Deno, which default to colored status codes.

**Comment by EdamAme-x** [comment]
okay, I will close this

**Comment by yusukebe** [comment]
@StuartMoncrieff @EdamAme-x Thanks!

**Pull request closed without merging**
