### PR TITLE
feat(jsx): Support async component.

### PR DESCRIPTION
**Pull request by usualoma**
### Author should do the followings, if applicable

- [x] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @usualoma!

It's awesome to support async components. My concern is adding the additional code to `context.ts`. However, the advantage of supporting async may outweigh the increase in code. I'll consider this matter for a while. Thanks!

**Comment by usualoma** [comment]
@yusukebe 
Thanks for the comment.

I have also added support for nested async components in a15cb21. I also think other modifications would need to be made to merge it into the "main" branch.

**Comment by yusukebe** [comment]
This PR is related to #1552

**Comment by usualoma** [comment]
Close this PR since it is included in #1630 and has already been merged into next.

**Pull request closed without merging**
