### PR TITLE
fix: streamSSE's doesn't trigger `onAbort` correctly

### PR DESCRIPTION
**Pull request by sor4chi**
### Author should do the followings, if applicable

- [x] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

#1902

### CODE REVIEW

**Comment by sor4chi** [comment]
Hi, @watany-dev. cc: @yusukebe 
I have changed streamSSE from the traditional implementation method to something similar to the original stream helper one, can you review it once as I am not familiar with this implementation?

**Comment by watany-dev** [comment]
@sor4chi 
Thank you. I was also able to confirm that onAbort stops normally when I actually run it. I think this is the way to go.

**Comment by sor4chi** [comment]
@watany-dev Thanks for reviewing!

@yusukebe This PR is review ready, please take a look this!

**Review by yusukebe — CHANGES_REQUESTED** [review]
Please remove this line to fix a lint error:

https://github.com/honojs/hono/pull/1920/files#diff-35853a74efb002a0669842bb8113731d2614c7036b8f3867317aa65b093fa406R3

**Comment by yusukebe** [comment]
Hi @sor4chi 

Looks good! I've left one comment. Check it please!

**Comment by sor4chi** [comment]
fixed!

**Review by yusukebe — APPROVED** [review]

**Comment by yusukebe** [comment]
@sor4chi @watany-dev 

Thanks! Merging now.

**Pull request merged**
