### PR TITLE
Lightweight RegExpRouter reborn

### PR DESCRIPTION
**Pull request by usualoma**
### What is this?

I have attempted to reduce code size by removing some features from RegExpRouter.

I would like to demonstrate the following with this PR.

* Smaller bundle size.
* No performance degradation.
* Existing tests for supporting path patterns should be green

After demonstrating, I would like to replace the old one by https://github.com/usualoma/hono/pull/2.
While the old RegExpRouter implementation is a good one, it is expensive to maintain a large number of routers and should be removed.

### Routing no longer supported

The RegExpLiteRouter does not handle routing that is even slightly complicated.
Throw UnsupportedPathError with the following routing.

```
app.get('/app/static', handler1);
app.get('/app/:label', handler2);
```

```
app.get('/:type/:id', handler1)
app.get('/:class/:id', handler2)
```

```
app.get('/:id/:action{create|update}', handler1)
app.get('/:id/:action{delete}', handler2)
```

### bundle size

Size comparison of a small example project using the hono.

before

```
> esbuild --bundle --sourcemap --minify --outdir=dist ./src/index.ts


  dist/index.js      21.4kb
  dist/index.js.map  85.1kb
```

It is still large, but much smaller.

after

```
> esbuild --bundle --sourcemap --minify --outdir=dist ./src/index.ts


  dist/index.js      18.5kb
  dist/index.js.map  71.9kb
```

### banchmark

```diff
diff --git a/benchmarks/handle-event/index.js b/benchmarks/handle-event/index.js
index 4ef367b..ab27ee4 100644
--- a/benchmarks/handle-event/index.js
+++ b/benchmarks/handle-event/index.js
@@ -6,7 +6,9 @@ import { Request, Response } from 'node-fetch'
 import { Router as SunderRouter, Sunder } from 'sunder'
 import { Router as WorktopRouter } from 'worktop'
 import { Hono } from '../../dist/hono'
+import { RegExpLiteRouter } from '../../dist/router/reg-exp-lite-router'
 import { RegExpRouter } from '../../dist/router/reg-exp-router'
+import { TrieRouter } from '../../dist/router/trie-router'
 
 globalThis.Request = Request
 globalThis.Response = Response
@@ -27,8 +29,9 @@ const initHono = (hono) => {
   return hono
 }
 
-const hono = initHono(new Hono())
+const hono = initHono(new Hono({ router: new TrieRouter() }))
 const honoWithRegExpRouter = initHono(new Hono({ router: new RegExpRouter() }))
+const honoWithRegExpLiteRouter = initHono(new Hono({ router: new RegExpLiteRouter() }))
 
 // itty-router
 const ittyRouter = IttyRouter()
@@ -120,6 +123,8 @@ const fn = async () => {
   console.log(await res.text())
   res = await honoWithRegExpRouter.handleEvent(event)
   console.log(await res.text())
+  res = await honoWithRegExpLiteRouter.handleEvent(event)
+  console.log(await res.text())
   res = await ittyRouter.handle(event.request)
   console.log(await res.text())
   res = await sunderApp.handle(event)
@@ -138,6 +143,9 @@ suite
   .add('hono - regexp-router', async () => {
     await honoWithRegExpRouter.handleEvent(event)
   })
+  .add('hono - regexp-lite-router', async () => {
+    await honoWithRegExpLiteRouter.handleEvent(event)
+  })
   .add('itty-router', async () => {
     await ittyRouter.handle(event.request)
   })
```

There is no performance degradation.

```
hono - trie-router(default) x 222,450 ops/sec ±5.45% (81 runs sampled)
hono - regexp-router x 260,434 ops/sec ±6.22% (79 runs sampled)
hono - regexp-lite-router x 266,024 ops/sec ±6.36% (79 runs sampled)
itty-router x 83,505 ops/sec ±3.57% (85 runs sampled)
sunder x 110,506 ops/sec ±4.74% (78 runs sampled)
worktop x 68,916 ops/sec ±2.40% (85 runs sampled)
Fastest is hono - regexp-lite-router,hono - regexp-router
```

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @usualoma !

Diet is a good thing! I also checked the bundle sizes with `wrangler dev index.ts` command. `index.ts` is just "Hello World" program.

```
SmartRouter with RegExpRouter
Total Upload: 51.58 KiB / gzip: 10.49 KiB

This PR / SmartRouter with RegExpLiteRouter
Total Upload: 43.94 KiB / gzip: 9.00 KiB

This PR / built as "ESNext"
Total Upload: 31.37 KiB / gzip: 7.65 KiB
```

```
Hono v2.1.4 / with default router
Total Upload: 27.04 KiB / gzip: 6.09 KiB

Sunder
Total Upload: 47.21 KiB / gzip: 11.08 KiB

Worktop
Total Upload: 7.02 KiB / gzip: 2.70 KiB
```

It has become very smaller! 

> After demonstrating, I would like to replace the old one by https://github.com/usualoma/hono/pull/2.

Okay, let's go!!

**Comment by usualoma** [comment]
@yusukebe 
Merged https://github.com/usualoma/hono/pull/2 and updated the benchmark script with 586711a!

**Comment by yusukebe** [comment]
@usualoma 

Thank you! It's so nice to have reduced codes.

Is it OK to merge?

**Comment by usualoma** [comment]
@yusukebe Sorry, please merge!

**Comment by yusukebe** [comment]
OK, I'll merge it!

**Pull request merged**
