### PR TITLE
feat: improve `ToSchema` & `WebSocket Helper` types

### PR DESCRIPTION
**Pull request by NamesMT**
A reimplement of #2562, using refactored types flow of #2581

**UPDATE:** All commits follows conventional syntax, recommended to merge without squashing.

### Author should do the followings, if applicable

- [x] ~~Add tests~~ Adjusted tests
- [x] Run tests
- [x] `bun denoify` to generate files for Deno

### CODE REVIEW

**Comment by NamesMT** [comment]
@nakasyou @yusukebe FYI

**Comment by yusukebe** [comment]
@NamesMT 

Can you rebase this PR on the latest "next"?

**Comment by NamesMT** [comment]
Hi @yusukebe, it's done.

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@NamesMT @nakasyou 

Thanks! Merging now.

**Pull request merged**
