### PR TITLE
fix(ssg): fix path parser bug & refactor code

### PR DESCRIPTION
**Pull request by EdamAme-x**
### Author should do the followings, if applicable

- [x] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by EdamAme-x** [comment]
I have improved the code to make it easier to understand and faster.
and i noticed before code (https://github.com/honojs/hono/pull/1965) has bug :(

Specifically, the triple dots should have been valid but were poorly parsed with the following use.
```ts
path = path.replace(/^\./g, '')
```

`.`, `..` and string without dot are operates normally.

but, `...`, `....`, (dotLength >= 3) or ex. `.hello`
these strings out to be "..", "...", and "hello", respectively.
It is a normal directory name to start with dot or to have multiple dots.

And i fixed this problem by improving the regular expression.
```ts
path = path.replace(/^\.(?!\.)/g, '')
```

**Comment by EdamAme-x** [comment]
sry
I found a few problems.
I will fix it later.

**Comment by EdamAme-x** [comment]
I checked and it was fine.
Test case is passed

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@EdamAme-x Thanks! Merge now.

**Pull request merged**
