### PR TITLE
Refactor(test): update vitest settings

### PR DESCRIPTION
**Pull request by watany-dev**
I have made these settings. 

~~1. Handling Vitest's type checking. This makes tsc --no-emit unnecessary.
https://vitest.dev/config/#typecheck~~
2. I don't think the Vitest configuration file is needed in tsconfig.build. I have listed similar items that I think are unnecessary, but please point out if I am mistaken.
3.  Update from Vitest 1.04 to 1.10.

### Author should do the followings, if applicable

- [ ] Add tests
- [ ] Run tests
- [ ] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @watany-dev 

Thanks!

I've tried Vite's type checking before, but it did not work well, and also, with this PR, it doesn't catch the type errors.

Screenshot 2023-12-24 at 15 52 19

I don't know if this setting is right or not. Anyway, if it can not check types, we have to keep using `tsc`.

**Comment by watany-dev** [comment]
@yusukebe 
Thank you for the review. Upon rechecking the typecheck tests for Vitest, it appears that '*.test-d.ts' is the scope, and it's not a complete substitute for tsc. I have reverted the changes.

**Comment by yusukebe** [comment]
> 2. I don't think the Vitest configuration file is needed in tsconfig.build. I have listed similar items that I think are unnecessary, but please point out if I am mistaken.

We don't have to modify `tsconfig.build.json` because it is just for the build phase used in `build.ts`. Vitest uses `tsconfig.json`.

**Comment by yusukebe** [comment]
@watany-dev 

Thanks. We can merge this!

**Pull request merged**
