### PR TITLE
fix(client): show type error if `$get()` needs args

### PR DESCRIPTION
**Pull request by yusukebe**
Made it throws the type error if `client.path.$method()` needs arguments:

SS

This fix will make the Client more type-safety.

### CODE REVIEW

**Comment by yudai-nkt** [comment]
This is what I found inconvenient but I haven't filed an issue yet, thanks! I'll check later.

**Comment by yusukebe** [comment]
Hi @yudai-nkt !

Have you done check it? I want to merge it.

**Comment by yudai-nkt** [comment]
I'm afraid I won't have check this on my local machine anytime soon, but basically LGTM!

**Comment by yusukebe** [comment]
Okay, I'll merge it!

**Pull request merged**
