### PR TITLE
chore: automatically close issues marked as “not bug” over time

### PR DESCRIPTION
**Pull request by EdamAme-x**
Closes: https://github.com/honojs/hono/issues/3607

The filename is from dart.  
Labels are automatically assigned after 7 days and automatically closed after two days.

### CODE REVIEW

**Comment by yusukebe** [comment]
Thanks @EdamAme-x !

I think it's good to show the comments you suggested in [the issue comment](https://github.com/honojs/hono/issues/3607#issue-2628157702).

And how about specifying the label text as `stale,` which is all lowercase?

```yaml
stale-issue-label: 'stale'
```

**Comment by EdamAme-x** [comment]
nice idea

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@EdamAme-x 

Thanks. Let's go with this.

**Pull request merged**
