### PR TITLE
feat(compress): improve compress middleware

### PR DESCRIPTION
**Pull request by nitedani**
Improvements:

- Content-Length threshold for compression
- Handling of already compressed responses
- Cache-Control: no-transform handling
- Handling of custom Content-Type headers

Fixes:
- https://github.com/honojs/hono/issues/3262

- [x] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code
- [x] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

**Review by usualoma — COMMENTED** [review]
Thanks for making the pull request! I think this pull request will greatly improve the "compress" middleware.

I've made some comments and hoped you could check them.

**Comment by nitedani** [comment]
Thank you too :) Pushed the changes.

**Review by usualoma — APPROVED** [review]
Thank you!

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
Hi @nitedani 

Awesome improvement! I'll merge this into the main and include it in the next patch release. Thank you!

**Pull request merged**
