### PR TITLE
fix(devcontainer): remove unknown flag on docker-compose

### LINKED ISSUE #3581: devcontainer build error on codespaces
log

```llvm
[92184 ms] Stop: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.68.0-1730178235355/Dockerfile-with-features -t vsc-hono-8b5783b9078e8a8c2a64865f0c1967473f79c74d5f7c1e9dabae1246cc08195c --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/hono/.devcontainer
[93033 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,src=/var/lib/docker/codespacemount/workspace,dst=/workspaces --mount source=/root/.codespaces/shared,target=/workspaces/.codespaces/shared,type=bind --mount source=/var/lib/docker/codespacemount/.persistedshare,target=/workspaces/.codespaces/.persistedshare,type=bind --mount source=/.codespaces/agent/mount,target=/.codespaces/bin,type=bind --mount source=/mnt/containerTmp,target=/tmp,type=bind --mount type=bind,src=/.codespaces/agent/mount/cache,dst=/vscode -l Type=codespaces -e HOME=/home/node -e CODESPACES=******** -e ContainerVersion=13 -e RepositoryName=hono --userns=keep-id --label ContainerVersion=13 --hostname codespaces-32c65a --add-host codespaces-32c65a:127.0.0.1 --cap-add sys_nice --network host --entrypoint /bin/sh vsc-hono-8b5783b9078e8a8c2a64865f0c1967473f79c74d5f7c1e9dabae1246cc08195c -c echo Container started
docker: --userns: invalid USER mode.
See 'docker run --help'.
[30 ms] Stop: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,src=/var/lib/docker/codespacemount/workspace,dst=/workspaces --mount source=/root/.codespaces/shared,target=/workspaces/.codespaces/shared,type=bind --mount source=/var/lib/docker/codespacemount/.persistedshare,target=/workspaces/.codespaces/.persistedshare,type=bind --mount source=/.codespaces/agent/mount,target=/.codespaces/bin,type=bind --mount source=/mnt/containerTmp,target=/tmp,type=bind --mount type=bind,src=/.codespaces/agent/mount/cache,dst=/vscode -l Type=codespaces -e HOME=/home/node -e CODESPACES=******** -e ContainerVersion=13 -e RepositoryName=hono --userns=keep-id --label ContainerVersion=13 --hostname codespaces-32c65a --add-host codespaces-32c65a:127.0.0.1 --cap-add sys_nice --network host --entrypoint /bin/sh vsc-hono-8b5783b9078e8a8c2a64865f0c1967473f79c74d5f7c1e9dabae1246cc08195c -c echo Container started
Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,src=/var/lib/docker/codespacemount/workspace,dst=/workspaces --mount source=/root/.codespaces/shared,target=/workspaces/.codespaces/shared,type=bind --mount source=/var/lib/docker/codespacemount/.persistedshare,target=/workspaces/.codespaces/.persistedshare,type=bind --mount source=/.codespaces/agent/mount,target=/.codespaces/bin,type=bind --mount source=/mnt/containerTmp,target=/tmp,type=bind --mount type=bind,src=/.codespaces/agent/mount/cache,dst=/vscode -l Type=codespaces -e HOME=/home/node -e CODESPACES=true -e ContainerVersion=13 -e RepositoryName=hono --userns=keep-id --label ContainerVersion=13 --hostname codespaces-32c65a --add-host codespaces-32c65a:127.0.0.1 --cap-add sys_nice --network host --entrypoint /bin/sh vsc-hono-8b5783b9078e8a8c2a64865f0c1967473f79c74d5f7c1e9dabae1246cc08195c -c echo Container started
{"outcome":"error","message":"Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,src=/var/lib/docker/codespacemount/workspace,dst=/workspaces --mount source=/root/.codespaces/shared,target=/workspaces/.codespaces/shared,type=bind --mount source=/var/lib/docker/codespacemount/.persistedshare,target=/workspaces/.codespaces/.persistedshare,type=bind --mount source=/.codespaces/agent/mount,target=/.codespaces/bin,type=bind --mount source=/mnt/containerTmp,target=/tmp,type=bind --mount type=bind,src=/.codespaces/agent/mount/cache,dst=/vscode -l Type=codespaces -e HOME=/home/node -e CODESPACES=true -e ContainerVersion=13 -e RepositoryName=hono --userns=keep-id --label ContainerVersion=13 --hostname codespaces-32c65a --add-host codespaces-32c65a:127.0.0.1 --cap-add sys_nice --network host --entrypoint /bin/sh vsc-hono-8b5783b9078e8a8c2a64865f0c1967473f79c74d5f7c1e9dabae1246cc08195c -c echo Container started\ntrap \"exit 0\" 15\n\nexec \"$@\"\nwhile sleep 1 & wait $!; do :; done -","description":"An error occurred setting up the container."}
trap "exit 0" 15
exec "$@"
while sleep 1 & wait $!; do :; done -
    at wtA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:465:1260)
    at NH (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:465:1002)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async YtA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:482:3771)
    at async eB (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:482:4886)
    at async prA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:663:200)
    at async drA (/.codespaces/agent/bin/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:662:14706)
devcontainer process exited with exit code 1
Failed to create container.
Error: Command failed: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,src=/var/lib/docker/codespacemount/workspace,dst=/workspaces --mount source=/root/.codespaces/shared,target=/workspaces/.codespaces/shared,type=bind --mount source=/var/lib/docker/codespacemount/.persistedshare,target=/workspaces/.codespaces/.persistedshare,type=bind --mount source=/.codespaces/agent/mount,target=/.codespaces/bin,type=bind --mount source=/mnt/containerTmp,target=/tmp,type=bind --mount type=bind,src=/.codespaces/agent/mount/cache,dst=/vscode -l Type=codespaces -e HOME=/home/node -e CODESPACES=true -e ContainerVersion=13 -e RepositoryName=hono --userns=keep-id --label ContainerVersion=13 --hostname codespaces-32c65a --add-host codespaces-32c65a:127.0.0.1 --cap-add sys_nice --network host --entrypoint /bin/sh vsc-hono-8b5783b9078e8a8c2a64865f0c1967473f79c74d5f7c1e9dabae1246cc08195c -c echo Container started
                                                          trap "exit 0" 15

                                                                          exec "$@"
                                                                                   while sleep 1 & wait $!; do :; done -
Error code: 1302 (UnifiedContainersErrorFatalCreatingContainer)
Container creation failed.

Creating recovery container.
```

### PR DESCRIPTION
**Pull request by EdamAme-x**
Closes #3581

### The author should do the following, if applicable

- [ ] Add tests
- [ ] Run tests
- [ ] `bun run format:fix && bun run lint:fix` to format the code
- [ ] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

**Comment by EdamAme-x** [comment]
What do you think about this how fix it?
@marcomuser

**Comment by marcomuser** [comment]
Oh sorry about that. I had not tested the new config with workspaces. The additional config values are coming straight from the devcontainer docs: https://code.visualstudio.com/remote/advancedcontainers/docker-options#_podman

**Comment by EdamAme-x** [comment]
Thanks for your reply.
This change made it work.
image

**Comment by yusukebe** [comment]
I'm not familiar with the dev container, but it looks good. @EdamAme-x Is this okay to merge?

**Comment by EdamAme-x** [comment]
I think it will be fine!

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@EdamAme-x Thanks! Let's go.

**Comment by marcomuser** [comment]
I tried out your branch locally with Podman and I can still build the container image and run all tests. Seems to work with Podman as well!

**Comment by EdamAme-x** [comment]
Thanks for testing it.

**Pull request merged**
