### PR TITLE
Custom fetch method for Hono Client options

### PR DESCRIPTION
**Pull request by JonasHiltl**
As described in my issue https://github.com/honojs/hono/issues/917 it would be great to be able to pass a custom fetch method to Hono Client to be able to call Service Bindings through Hono Client.

I have just added an optional `fetch` method to the `RequestOptions` so that the `fetch` method of a Service Binding can be used instead of the default `fetch` API when it's set in the options.

See this example on how it would be used:
```
services = [
  { binding = "AUTH", service = "auth-service" },
]
```
```typescript
const client = hc<CreateProfileType>('/', { fetch: c.env. AUTH.fetch });
...
// use client normally
```

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @JonasHiltl !

Great work! Now I fully understand what you want to do.

I'd like to accept this PR, but there is one request. Could you do `yarn denoify` and `git add` the generated file & git commit & push? The file is needed for the Deno. Thanks.

**Comment by JonasHiltl** [comment]
@yusukebe Done!

**Comment by yusukebe** [comment]
Thanks. I'll merge it!

**Comment by yusukebe** [comment]
Hi @ronkeiser 

This is caused by a type mismatch. The Request object referred to differs between Hono's and `@cloudflare/workers-types`. I think resolving this is complex or impossible. The best workaround is ignoring the type check.

**Comment by ronkeiser** [comment]
@yusukebe Sounds good. Thank you for your responsiveness and your work on this wonderful project!

**Pull request merged**
