### PR TITLE
fix(types): remove `any` and fix types of adapter/deno

### PR DESCRIPTION
**Pull request by EdamAme-x**
### The author should do the following, if applicable

- [ ] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code
- [x] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

**Comment by EdamAme-x** [comment]
Hi @yusukebe 
Could you review this?

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by EdamAme-x** [comment]
,,

**Comment by EdamAme-x** [comment]
All checks passed

**Comment by yusukebe** [comment]
Okay! Let's go!

**Pull request merged**
