### PR TITLE
fix: add return types of void function

### PR DESCRIPTION
**Pull request by EdamAme-x**
JSR was throwing an error because some functions had return types that were not set. This has been fixed.

### CODE REVIEW

**Comment by EdamAme-x** [comment]
hmm...

**Comment by EdamAme-x** [comment]
@yusukebe I resolved JSR errors.

**Comment by yusukebe** [comment]
@EdamAme-x 

Sorry. I don't want to merge the PR that the description is only `test`.

**Comment by EdamAme-x** [comment]
sorry, I'll rewrite

**Comment by EdamAme-x** [comment]
@yusukebe ready

**Comment by yusukebe** [comment]
@EdamAme-x 

I've deleted the unnecessary commit on the branch. This can be merged. Thanks!

**Pull request merged**
