### PR TITLE
feat(context): infer `TypedResponse` for `TextRespond`

### PR DESCRIPTION
**Pull request by NamesMT**
### Author should do the followings, if applicable

- [x] ~~Add tests~~ Adjusted tests
- [x] Run tests - Ran all tests except for deno and wrangler because I don't have them
- [x] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @NamesMT 

This is awesome. I'd like to merge it into the "next" branch for the next minor release will be shipped soon.

I've fixed that `res.text()` and `res.json()` on the client side did not return the correct types with 9d690a6d1f8caefb49fcb207e5ed82edeeaebf86. Now, these are correct:

CleanShot 2024-05-01 at 08 04 16@2x

CleanShot 2024-05-01 at 08 04 28@2x

I think this is good. How about you?

**Comment by NamesMT** [comment]
Thanks @yusukebe, that's great.

But please wait a bit before merging, I found an untested regression, will document and add tests for it maybe tonight, urgent have to go now.

**Comment by yusukebe** [comment]
@NamesMT Okay!

**Comment by NamesMT** [comment]
Hi @yusukebe, I've done the updates to fix the regression and improve the type inferring for the `Response`.

The regression is: `c.json()` is able to return `string` JSONPrimitive, in the latest update to `res.json()` they were broken and always typed as `never`.

The final scope of work to get everything perfectly working was much bigger than I thought and I don't know if I did it the best way, so I will create a new draft PR for it to discuss if it's good or not.

It's an un-splitted commit but heres the readable updates that I've made:
- Switch from `InterfaceToType` to `Simplify` for better performance + easier working with types, InterfaceToType was yelling `Type instantiation is excessively deep and possibly infinite.`
- `TypedResponse`: add `ResponseFormat` generic (`'json' | 'text'`)
- `ClientResponse`: accept `ResponseFormat` generic to properly return the correct type
- `Endpoint` (and related interfaces): now includes outputFormat: `ResponseFormat`

Bonus:
- `ClientResponse` now properly extends `globalThis.Response` for better experience when working with functions that expects a fetch's Response

+ update tests

New PR: #2581

**Comment by yusukebe** [comment]
Hi @NamesMT 

That's super great. Anyway, I want to go with #2581 though we may have improvements. Let's talk on #2581

**Comment by NamesMT** [comment]
Close to continue in #2581

**Pull request closed without merging**
