### PR TITLE
chore(build): fix progress of log

### PR DESCRIPTION
**Pull request by EdamAme-x**
Before
`Removing private fields(0/170): dist\types\types.d.ts`

After
`Removing private fields(1/170): dist\types\types.d.ts`

Progress should start at 1

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @EdamAme-x 

Indeed, we can fix it. How about this implementation?

```diff
diff --git a/build/build.ts b/build/build.ts
index 34285bb7..7e31934e 100644
--- a/build/build.ts
+++ b/build/build.ts
@@ -102,7 +102,7 @@ const dtsEntries = glob.globSync('./dist/types/**/*.d.ts')
 const writer = stdout.writer()
 writer.write('\n')
 let lastOutputLength = 0
-for (let i = 0; i < dtsEntries.length; i++) {
+for (let i = 1; i < dtsEntries.length + 1; i++) {
   const entry = dtsEntries[i]

   const message = `Removing private fields(${i}/${dtsEntries.length}): ${entry}`
```

**Comment by EdamAme-x** [comment]
okay, more clear

**Comment by EdamAme-x** [comment]
I was try it, I think the code is a little redundant.

```ts
for (let i = 1; i < dtsEntries.length + 1; i++) {
  const entry = dtsEntries[i - 1]
```

**Review by yusukebe — APPROVED** [review]
LGTM!

**Pull request merged**
