### PR TITLE
chore: fix linter

### PR DESCRIPTION
**Pull request by watany-dev**
Fix the reasons that the linter did not notice.

### CODE REVIEW

**Comment by watany-dev** [comment]
wait #1305

**Comment by yusukebe** [comment]
Hi @watany-dev !

#1305  has been merged. So, could you merge it into this branch, fix the errors, and commit?

**Comment by watany-dev** [comment]
@yusukebe @y
Yes! We also fetch the latest commit and confirm that the test passes successfully!

**Comment by yusukebe** [comment]
Great!! Let's go!

**Pull request merged**
