### PR TITLE
feat(css): add CSP nonce to hono/css related style and script tags

### LINKED ISSUE #3694: CSP support for CSS Helper
### What is the feature you are proposing?

First of all, thanks a lot for you're awesome work on Hono. I really enjoy using it. 

I've been using the CSS helper. It works well 🚀 But in combination with nonce-based CSP i.e. if inline script and style tags are only allowed, if a random nonce is set on each render (e.g., `<style id="hono-css" nonce="1234">` or `<script nonce="1234">`, it doesn't work yet. Currently, there is no way to pass the nonce to the style and script tag. 

For example, I'd like to be able to add the nonce to the `<Style nonce="{c.get("secureHeadersNonce")}" />` to ensure the inline CSS is not ignored by the browser. 

For example, a test could look as follows:
```tsx
it('Should render CSS styles with CSP nonce', async () => {
  const headerClass = css`
    background-color: blue;
  `
  const template = (
    <>
      <Style nonce='1234' />
      <h1 class={headerClass}>Hello!</h1>
    </>
  )
  expect(await toString(template)).toBe(
    '<style id="hono-css" nonce="1234">.css-2458908649{background-color:blue}</style><h1 class="css-2458908649">Hello!</h1>'
  )
})
```

I'd like to help and contribute this feature and have started a possible implementation here: https://github.com/honojs/hono/pull/3685 -> happy for feedback! thanks!

### Related to 
- https://github.com/honojs/hono/pull/1858
- https://github.com/honojs/hono/pull/2577

### PR DESCRIPTION
**Pull request by meck93**
closes #3694

This PR extends upon the work of https://github.com/honojs/hono/pull/2577 with the goal to bring the CSS nonce to the inline `style` and `script` tags created by the usage of `hono/css`. The goal is to be able to add `<Style nonce={nonce} />` in order to comply with strict CSP rules.

### The author should do the following, if applicable

- [x] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code

### To Do
- [ ]  There are still two test failures related to `<script nonce="1234">document.querySelector('#hono-css').textContent+="..."</script>` being added to the snapshot which should end up there. One should test if this is only due to the test setup and the `<script>` tag not being executed in the test environment.

@usualoma could you provide me with some pointers on where to start further debugging these test failures? I see that you've implemented most code around CSP and CSS. 

```bash
 FAIL  src/helper/css/index.test.tsx > CSS Helper > render css > Booleans, Null, and Undefined Are Ignored > Should render CSS styles with CSP nonce
AssertionError: expected '<script nonce="1234">document.querySe…' to be '<style id="hono-css" nonce="1234">.cs…' // Object.is equality

Expected: "<style id="hono-css" nonce="1234">.css-2458908649{background-color:blue}</style><h1 class="css-2458908649">Hello!</h1>"
Received: "<script nonce="1234">document.querySelector('#hono-css').textContent+=".css-2458908649{background-color:blue}"</script><style id="hono-css" nonce="1234"></style><h1 class="css-2458908649">Hello!</h1>"

 ❯ src/helper/css/common.case.test.tsx:502:42
    500|           </>
    501|         )
    502|         expect(await toString(template)).toBe(
       |                                          ^
    503|           '<style id="hono-css" nonce="1234">.css-2458908649{background-color:blue}</style><h1 class="css-2458908649">Hello!</h1>'
    504|         )

 FAIL  src/helper/css/index.test.tsx > CSS Helper > with `html` tag function > Should render CSS styles with `html` tag function and CSP nonce
AssertionError: expected '<script nonce="1234">document.querySe…' to be '<style id="hono-css" nonce="1234">.cs…' // Object.is equality

- Expected
+ Received

- <style id="hono-css" nonce="1234">.css-2458908649{background-color:blue}</style>
+ <script nonce="1234">document.querySelector('#hono-css').textContent+=".css-2458908649{background-color:blue}"</script><style id="hono-css" nonce="1234"></style>
          <h1 class="css-2458908649">Hello!</h1>

 ❯ src/helper/css/index.test.tsx:68:40
     66|       const template = html`${Style({ nonce: '1234' })}
     67|         <h1 class="${headerClass}">Hello!</h1>`
     68|       expect(await toString(template)).toBe(
       |                                        ^
     69|         `<style id="hono-css" nonce="1234">.css-2458908649{background-color:blue}</style>
     70|         <h1 class="css-2458908649">Hello!</h1>`
```

- [ ] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

**Comment by usualoma** [comment]
Hi @meck93 , sorry to keep you waiting.

I've created a pull request, so please check it out.
https://github.com/meck93/hono/pull/1

The test failure is fixed in the following commit.
https://github.com/meck93/hono/pull/1/commits/2f06776d418a77c42b0d9e0956b9b0d97b35a7c4

Also, `context` is an arbitrary object, but the internal specification does not allow its updating, so I have changed the code to use it as a key in a WeakMap.

Thank you.

**Comment by meck93** [comment]
> Hi @meck93 , sorry to keep you waiting.
> 
> I've created a pull request, so please check it out. [meck93#1](https://github.com/meck93/hono/pull/1)
> 
> The test failure is fixed in the following commit. [meck93@2f06776](https://github.com/meck93/hono/commit/2f06776d418a77c42b0d9e0956b9b0d97b35a7c4)
> 
> Also, `context` is an arbitrary object, but the internal specification does not allow its updating, so I have changed the code to use it as a key in a WeakMap.
> 
> Thank you.

Thanks a lot for the feedback and the pull request. I like your approach using the `nonceMap` (really clean and easy to understand also if you're unfamiliar with the rest of the hono code). I've merged your PR ✅

**Comment by usualoma** [comment]
Hi @meck93, Thank you.
LGTM!

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by meck93** [comment]
> * https://hono.dev/docs/helpers/css

@yusukebe Sure. Here you go: https://github.com/honojs/website/pull/536
Let me know if you want something changed. Thanks!

**Pull request merged**
