### PR TITLE
fix(helper/ssg): fix bug of joinPaths

### PR DESCRIPTION
**Pull request by EdamAme-x**
### The author should do the following, if applicable

- [x] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code

### CODE REVIEW

**Comment by EdamAme-x** [comment]
based by https://github.com/honojs/hono/pull/2798

**Comment by yusukebe** [comment]
Thanks @EdamAme-x !

@nakasyou Can you review this?

**Review by nakasyou — APPROVED** [review]
It looks good! I think there was a bug.

**Comment by yusukebe** [comment]
@EdamAme-x @nakasyou Thanks! Merging now.

**Pull request merged**
