### PR TITLE
feat(dev): support `NO_COLOR`

### PR DESCRIPTION
**Pull request by ryuapp**
Many frameworks support `NO_COLOR` because color libraries like ~chalk~, [kleur](https://github.com/lukeed/kleur) and [picocolors](https://github.com/alexeyraspopov/picocolors) support the env.
This helps disabling colored text output for some developers.
https://no-color.org/

### Author should do the followings, if applicable

- [x] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by yusukebe** [comment]
@ryuapp 

Thanks! This is good.

Can you write the test, although that will be very simple?

**Comment by ryuapp** [comment]
@yusukebe 
I need to add an environment variable before running test because [vi.stubEnv](https://vitest.dev/api/vi.html#vi-stubenv-0-26-0) cannot be used in this test due to the initialization timing of `isNoColor`.

Do you have any comments about this test?

**Comment by yusukebe** [comment]
@ryuapp 

How about this?

```diff
diff --git a/src/helper/dev/index.test.ts b/src/helper/dev/index.test.ts
index 65d2480..84fd24f 100644
--- a/src/helper/dev/index.test.ts
+++ b/src/helper/dev/index.test.ts
@@ -3,7 +3,6 @@ import { RegExpRouter } from '../../router/reg-exp-router'
 import type { Handler, MiddlewareHandler } from '../../types'
 import { inspectRoutes, showRoutes, getRouterName } from '.'
 
-const isNoColor = 'NO_COLOR' in process.env
 const namedMiddleware: MiddlewareHandler = (_, next) => next()
 const namedHandler: Handler = (c) => c.text('hi')
 const app = new Hono()
@@ -57,11 +56,12 @@ describe('inspectRoutes()', () => {
   })
 })
 
-describe.runIf(!isNoColor)('showRoutes()', () => {
+describe('showRoutes()', () => {
   let logs: string[] = []
 
   let originalLog: typeof console.log
   beforeAll(() => {
+    vi.stubEnv('NO_COLOR', '')
     originalLog = console.log
     console.log = (...args) => logs.push(...args)
   })
@@ -127,11 +127,12 @@ describe.runIf(!isNoColor)('showRoutes()', () => {
   })
 })
 
-describe.runIf(isNoColor)('showRoutes() in NO_COLOR', () => {
+describe('showRoutes() in NO_COLOR', () => {
   let logs: string[] = []
 
   let originalLog: typeof console.log
   beforeAll(() => {
+    vi.stubEnv('NO_COLOR', 'true')
     originalLog = console.log
     console.log = (...args) => logs.push(...args)
   })
diff --git a/src/helper/dev/index.ts b/src/helper/dev/index.ts
index bcaa001..f303ba9 100644
--- a/src/helper/dev/index.ts
+++ b/src/helper/dev/index.ts
@@ -14,15 +14,6 @@ interface RouteData {
   isMiddleware: boolean
 }
 
-// eslint-disable-next-line @typescript-eslint/no-explicit-any
-const { process, Deno } = globalThis as any
-const isNoColor =
-  typeof process !== 'undefined'
-    ? // eslint-disable-next-line no-unsafe-optional-chaining
-      'NO_COLOR' in process?.env
-    : typeof Deno?.noColor === 'boolean'
-    ? (Deno.noColor as boolean)
-    : false
 const isMiddleware = (handler: Function) => handler.length > 1
 const handlerName = (handler: Function) => {
   return handler.name || (isMiddleware(handler) ? '[middleware]' : '[handler]')
@@ -48,6 +39,15 @@ export const inspectRoutes = <E extends Env>(hono: Hono<E>): RouteData[] => {
 }
 
 export const showRoutes = <E extends Env>(hono: Hono<E>, opts?: ShowRoutesOptions) => {
+  // eslint-disable-next-line @typescript-eslint/no-explicit-any
+  const { process, Deno } = globalThis as any
+  const isNoColor =
+    typeof process !== 'undefined'
+      ? !!process?.env.NO_COLOR
+      : typeof Deno?.noColor === 'boolean'
+      ? (Deno.noColor as boolean)
+      : false
+
   const colorEnabled = opts?.colorize ?? !isNoColor
   const routeData: Record<string, RouteData[]> = {}
   let maxMethodLength = 0
```

If this works, the `test:no-color` command will no longer be necessary.

**Comment by ryuapp** [comment]
@yusukebe 
Thank you for the comment.
It works well. I avoided that implementation because it reads the environment variable every time the function is executed.
But, I reconsidered that this feature does not require performance at the expense of test complexity.
I'll fix that later.

**Review by yusukebe — APPROVED** [review]

**Comment by yusukebe** [comment]
@ryuapp 

Thanks! This is a minor feat, so I'll include this in the next patch release.

**Pull request merged**
