### PR TITLE
chore: benchmark of routers

### PR DESCRIPTION
**Pull request by yusukebe**
Added benchmark scripts for measuring the speed of HTTP routers on Node.js and Bun.

In conclusion, in my environment, RegExpRouter is the third fastest on Node.js and the first or second fastest on Bun. Unfortunately, TrieRouter is slow (It's unavoidable because it has a sorting process). The difference in results between Bun and Node.js is probably due to Bun's regular expressions being faster.

`@medley/router` used in [Elysia](https://elysiajs.com) and `koa-tree-router` are fast. Our advantage is that the file sizes are smaller than anywhere else. And routings are also flexible for users' use-cases. So it is not a comparison in general, but the result is the result.

## Node.js

```
---------------------------------------------------------------------------- -----------------------------
• short static - GET /user
---------------------------------------------------------------------------- -----------------------------
Hono RegExpRouter                     140.13 ns/iter (127.78 ns … 204.16 ns) 141.62 ns  191.8 ns 204.08 ns
Hono TrieRouter                       212.64 ns/iter (208.33 ns … 287.68 ns) 212.97 ns 268.56 ns 271.18 ns
@medley/router                        102.52 ns/iter   (97.63 ns … 165.8 ns) 105.03 ns 148.52 ns 152.68 ns
find-my-way                            92.51 ns/iter  (85.26 ns … 105.31 ns)  95.32 ns 100.29 ns 102.32 ns
koa-tree-router                        89.93 ns/iter    (83.4 ns … 105.3 ns)  92.71 ns 101.17 ns 101.98 ns
trek-router                           118.23 ns/iter  (109.71 ns … 129.4 ns) 121.31 ns 126.18 ns 127.26 ns
express (WARNING: includes handling)  650.04 ns/iter  (639.19 ns … 708.6 ns) 652.52 ns  708.6 ns  708.6 ns
koa-router                                 2 µs/iter     (1.92 µs … 2.07 µs)   2.04 µs   2.07 µs   2.07 µs

summary for short static - GET /user
  koa-tree-router
   1.03x faster than find-my-way
   1.14x faster than @medley/router
   1.31x faster than trek-router
   1.56x faster than Hono RegExpRouter
   2.36x faster than Hono TrieRouter
   7.23x faster than express (WARNING: includes handling)
   22.23x faster than koa-router
```

```
• static with same radix - GET /user/comments
---------------------------------------------------------------------------- -----------------------------
Hono RegExpRouter                     142.34 ns/iter (138.05 ns … 167.55 ns) 147.97 ns 155.47 ns 159.52 ns
Hono TrieRouter                       228.57 ns/iter (220.69 ns … 245.82 ns) 232.03 ns 238.06 ns 238.82 ns
@medley/router                        147.26 ns/iter (138.96 ns … 165.74 ns) 146.72 ns 158.76 ns 161.97 ns
find-my-way                           160.25 ns/iter (156.06 ns … 178.38 ns) 166.26 ns 175.93 ns 177.41 ns
koa-tree-router                       125.24 ns/iter (121.52 ns … 147.05 ns)  130.7 ns 136.93 ns 138.42 ns
trek-router                           174.28 ns/iter (170.04 ns … 193.75 ns) 179.93 ns  189.7 ns 190.02 ns
express (WARNING: includes handling)  649.44 ns/iter (643.57 ns … 677.34 ns) 650.24 ns 677.34 ns 677.34 ns
koa-router                              1.93 µs/iter     (1.93 µs … 1.96 µs)   1.94 µs   1.96 µs   1.96 µs

summary for static with same radix - GET /user/comments
  koa-tree-router
   1.14x faster than Hono RegExpRouter
   1.18x faster than @medley/router
   1.28x faster than find-my-way
   1.39x faster than trek-router
   1.83x faster than Hono TrieRouter
   5.19x faster than express (WARNING: includes handling)
   15.44x faster than koa-router
```

```
• dynamic route - GET /user/lookup/username/hey
---------------------------------------------------------------------------- -----------------------------
Hono RegExpRouter                     177.13 ns/iter (171.65 ns … 205.41 ns) 181.94 ns  191.4 ns 197.01 ns
Hono TrieRouter                       346.78 ns/iter (335.76 ns … 370.08 ns) 347.71 ns  367.4 ns 370.08 ns
@medley/router                        197.79 ns/iter (193.47 ns … 212.85 ns) 200.01 ns 210.51 ns 212.78 ns
find-my-way                            232.1 ns/iter (226.94 ns … 249.44 ns) 237.56 ns  244.4 ns 245.99 ns
koa-tree-router                       184.69 ns/iter (179.14 ns … 205.31 ns) 188.95 ns 195.54 ns 195.56 ns
trek-router                           274.84 ns/iter  (268.82 ns … 300.5 ns) 279.72 ns 292.21 ns  300.5 ns
express (WARNING: includes handling)    1.24 µs/iter     (1.22 µs … 1.34 µs)   1.25 µs   1.34 µs   1.34 µs
koa-router                              1.94 µs/iter     (1.93 µs … 1.97 µs)   1.95 µs   1.97 µs   1.97 µs

summary for dynamic route - GET /user/lookup/username/hey
  Hono RegExpRouter
   1.04x faster than koa-tree-router
   1.12x faster than @medley/router
   1.31x faster than find-my-way
   1.55x faster than trek-router
   1.96x faster than Hono TrieRouter
   6.99x faster than express (WARNING: includes handling)
   10.97x faster than koa-router
```

```
• mixed static dynamic - GET /event/abcd1234/comments
---------------------------------------------------------------------------- -----------------------------
Hono RegExpRouter                     170.34 ns/iter (165.74 ns … 194.03 ns) 175.47 ns 181.81 ns 183.15 ns
Hono TrieRouter                       343.89 ns/iter (333.45 ns … 361.15 ns) 345.72 ns 360.02 ns 361.15 ns
@medley/router                        163.86 ns/iter  (160.07 ns … 192.6 ns) 163.96 ns 175.24 ns 179.88 ns
find-my-way                           204.68 ns/iter (199.88 ns … 224.42 ns) 209.68 ns 219.07 ns 222.63 ns
koa-tree-router                        154.1 ns/iter (148.82 ns … 177.18 ns) 159.07 ns 164.34 ns 166.34 ns
trek-router                           242.45 ns/iter    (237 ns … 269.24 ns) 247.57 ns  256.9 ns 261.64 ns
express (WARNING: includes handling)    1.37 µs/iter     (1.36 µs … 1.39 µs)   1.37 µs   1.39 µs   1.39 µs
koa-router                              1.96 µs/iter     (1.96 µs … 1.99 µs)   1.97 µs   1.99 µs   1.99 µs

summary for mixed static dynamic - GET /event/abcd1234/comments
  koa-tree-router
   1.06x faster than @medley/router
   1.11x faster than Hono RegExpRouter
   1.33x faster than find-my-way
   1.57x faster than trek-router
   2.23x faster than Hono TrieRouter
   8.87x faster than express (WARNING: includes handling)
   12.75x faster than koa-router
```

```
• post - POST /event/abcd1234/comment
---------------------------------------------------------------------------- -----------------------------
Hono RegExpRouter                     144.05 ns/iter (139.87 ns … 167.19 ns) 149.78 ns 156.18 ns    158 ns
Hono TrieRouter                       348.78 ns/iter (338.37 ns … 370.21 ns) 350.56 ns 368.32 ns 370.21 ns
@medley/router                        143.85 ns/iter (140.32 ns … 165.14 ns) 145.48 ns 156.71 ns 162.33 ns
find-my-way                           201.54 ns/iter (189.71 ns … 218.24 ns) 207.03 ns 211.65 ns 213.17 ns
koa-tree-router                       143.99 ns/iter (139.08 ns … 160.36 ns) 149.27 ns 157.24 ns 157.63 ns
trek-router                           208.32 ns/iter (203.03 ns … 234.24 ns) 213.88 ns 217.34 ns 223.78 ns
express (WARNING: includes handling)     1.4 µs/iter     (1.39 µs … 1.43 µs)   1.41 µs   1.43 µs   1.43 µs
koa-router                              1.98 µs/iter     (1.95 µs … 2.09 µs)   1.97 µs   2.09 µs   2.09 µs

summary for post - POST /event/abcd1234/comment
  @medley/router
   1x faster than koa-tree-router
   1x faster than Hono RegExpRouter
   1.4x faster than find-my-way
   1.45x faster than trek-router
   2.42x faster than Hono TrieRouter
   9.77x faster than express (WARNING: includes handling)
   13.76x faster than koa-router
```

```
• long static - GET /very/deeply/nested/route/hello/there
---------------------------------------------------------------------------- -----------------------------
Hono RegExpRouter                     157.36 ns/iter (153.27 ns … 171.93 ns) 163.09 ns 169.76 ns 169.88 ns
Hono TrieRouter                       330.73 ns/iter (327.63 ns … 348.84 ns) 330.72 ns 340.64 ns 348.84 ns
@medley/router                        119.18 ns/iter (116.12 ns … 137.22 ns) 120.24 ns 129.64 ns 135.63 ns
find-my-way                           202.87 ns/iter (197.88 ns … 227.67 ns) 208.79 ns 215.96 ns 220.36 ns
koa-tree-router                       118.05 ns/iter (114.83 ns … 132.02 ns) 118.89 ns 129.57 ns 131.43 ns
trek-router                           137.67 ns/iter (133.75 ns … 159.65 ns) 138.97 ns 148.92 ns 150.93 ns
express (WARNING: includes handling)  946.79 ns/iter  (936.7 ns … 978.62 ns) 952.38 ns 978.62 ns 978.62 ns
koa-router                              1.97 µs/iter     (1.93 µs … 3.07 µs)   1.94 µs   3.07 µs   3.07 µs

summary for long static - GET /very/deeply/nested/route/hello/there
  koa-tree-router
   1.01x faster than @medley/router
   1.17x faster than trek-router
   1.33x faster than Hono RegExpRouter
   1.72x faster than find-my-way
   2.8x faster than Hono TrieRouter
   8.02x faster than express (WARNING: includes handling)
   16.69x faster than koa-router
```

```
• wildcard - GET /static/index.html
---------------------------------------------------------------------------- -----------------------------
Hono RegExpRouter                     151.54 ns/iter (147.36 ns … 170.38 ns) 157.15 ns 161.79 ns 164.05 ns
Hono TrieRouter                       251.79 ns/iter (241.96 ns … 263.23 ns) 254.75 ns 261.34 ns 262.23 ns
@medley/router                        112.59 ns/iter (109.32 ns … 128.28 ns) 113.77 ns 123.61 ns 126.79 ns
find-my-way                           178.03 ns/iter  (170.61 ns … 197.7 ns)  183.5 ns 189.43 ns  191.6 ns
koa-tree-router                       155.66 ns/iter (149.68 ns … 170.77 ns) 160.97 ns    165 ns 165.39 ns
trek-router                           183.27 ns/iter (176.93 ns … 217.39 ns) 187.99 ns 203.07 ns 210.88 ns
express (WARNING: includes handling)    1.59 µs/iter     (1.57 µs … 1.62 µs)   1.59 µs   1.62 µs   1.62 µs
koa-router                              1.94 µs/iter     (1.93 µs … 1.96 µs)   1.94 µs   1.96 µs   1.96 µs

summary for wildcard - GET /static/index.html
  @medley/router
   1.35x faster than Hono RegExpRouter
   1.38x faster than koa-tree-router
   1.58x faster than find-my-way
   1.63x faster than trek-router
   2.24x faster than Hono TrieRouter
   14.08x faster than express (WARNING: includes handling)
   17.21x faster than koa-router
```

```
• all together
---------------------------------------------------------------------------- -----------------------------
Hono RegExpRouter                     718.63 ns/iter  (714.32 ns … 731.9 ns) 718.27 ns  731.9 ns  731.9 ns
Hono TrieRouter                         1.81 µs/iter     (1.78 µs … 1.93 µs)   1.81 µs   1.93 µs   1.93 µs
@medley/router                        636.27 ns/iter (616.76 ns … 658.81 ns) 643.83 ns 658.81 ns 658.81 ns
find-my-way                             1.04 µs/iter     (1.03 µs … 1.06 µs)   1.04 µs   1.06 µs   1.06 µs
koa-tree-router                       664.27 ns/iter (656.67 ns … 698.83 ns) 668.99 ns 698.83 ns 698.83 ns
trek-router                             1.03 µs/iter     (1.02 µs … 1.05 µs)   1.03 µs   1.05 µs   1.05 µs
express (WARNING: includes handling)     7.8 µs/iter   (7.46 µs … 180.96 µs)   7.71 µs   8.25 µs   8.46 µs
koa-router                             13.62 µs/iter  (13.04 µs … 168.54 µs)  13.33 µs  14.25 µs  14.71 µs

summary for all together
  @medley/router
   1.04x faster than koa-tree-router
   1.13x faster than Hono RegExpRouter
   1.62x faster than trek-router
   1.63x faster than find-my-way
   2.84x faster than Hono TrieRouter
   12.27x faster than express (WARNING: includes handling)
   21.4x faster than koa-router
```

## Bun

```
---------------------------------------------------------------------------- -----------------------------
• short static - GET /user
---------------------------------------------------------------------------- -----------------------------
Hono RegExpRouter                     168.73 ns/iter (155.26 ns … 529.23 ns) 160.26 ns 300.99 ns 442.68 ns
Hono TrieRouter                       299.78 ns/iter (283.41 ns … 566.59 ns) 292.11 ns 392.59 ns 566.59 ns
@medley/router                        138.87 ns/iter (130.71 ns … 456.34 ns) 135.23 ns 214.85 ns 339.99 ns
find-my-way                           144.66 ns/iter (133.18 ns … 540.48 ns) 136.62 ns 214.69 ns 269.18 ns
koa-tree-router                       145.17 ns/iter (136.34 ns … 319.57 ns) 143.15 ns 209.65 ns 228.62 ns
trek-router                           202.52 ns/iter  (195.13 ns … 297.4 ns) 198.32 ns 274.77 ns 286.13 ns
express (WARNING: includes handling)  484.38 ns/iter (426.34 ns … 627.66 ns) 514.05 ns 587.09 ns 627.66 ns
koa-router                            243.78 ns/iter (237.05 ns … 368.07 ns) 238.96 ns 311.95 ns 314.21 ns

summary for short static - GET /user
  @medley/router
   1.04x faster than find-my-way
   1.05x faster than koa-tree-router
   1.22x faster than Hono RegExpRouter
   1.46x faster than trek-router
   1.76x faster than koa-router
   2.16x faster than Hono TrieRouter
   3.49x faster than express (WARNING: includes handling)
```

```
• static with same radix - GET /user/comments
---------------------------------------------------------------------------- -----------------------------
Hono RegExpRouter                     171.63 ns/iter (163.48 ns … 265.79 ns)  166.2 ns 248.03 ns 257.31 ns
Hono TrieRouter                       347.94 ns/iter (331.75 ns … 415.75 ns) 346.66 ns 408.46 ns 415.75 ns
@medley/router                        183.44 ns/iter (177.56 ns … 326.72 ns) 179.72 ns 256.21 ns  266.2 ns
find-my-way                           179.22 ns/iter (169.39 ns … 310.33 ns) 172.55 ns 245.25 ns 259.35 ns
koa-tree-router                       219.69 ns/iter (202.87 ns … 545.36 ns) 212.75 ns 391.11 ns 414.03 ns
trek-router                           323.44 ns/iter (311.88 ns … 490.22 ns) 317.66 ns 468.47 ns 490.22 ns
express (WARNING: includes handling)  514.78 ns/iter (464.45 ns … 887.69 ns) 540.96 ns 792.68 ns 887.69 ns
koa-router                            247.07 ns/iter (240.22 ns … 324.99 ns) 242.82 ns 308.39 ns 313.53 ns

summary for static with same radix - GET /user/comments
  Hono RegExpRouter
   1.04x faster than find-my-way
   1.07x faster than @medley/router
   1.28x faster than koa-tree-router
   1.44x faster than koa-router
   1.88x faster than trek-router
   2.03x faster than Hono TrieRouter
   3x faster than express (WARNING: includes handling)
```

```
• dynamic route - GET /user/lookup/username/hey
---------------------------------------------------------------------------- -----------------------------
Hono RegExpRouter                     200.52 ns/iter (187.81 ns … 815.73 ns) 191.07 ns 283.99 ns  319.7 ns
Hono TrieRouter                       537.26 ns/iter (504.63 ns … 743.42 ns) 558.99 ns 625.86 ns 743.42 ns
@medley/router                        232.64 ns/iter (224.27 ns … 397.93 ns) 228.27 ns  302.4 ns 304.69 ns
find-my-way                            255.5 ns/iter    (243 ns … 394.65 ns) 248.55 ns 353.18 ns 374.52 ns
koa-tree-router                       317.31 ns/iter (296.53 ns … 695.05 ns) 309.98 ns 616.73 ns 695.05 ns
trek-router                           477.65 ns/iter (459.42 ns … 599.56 ns) 474.82 ns 552.95 ns 599.56 ns
express (WARNING: includes handling)  680.13 ns/iter (622.32 ns … 989.88 ns) 705.92 ns 989.88 ns 989.88 ns
koa-router                            260.56 ns/iter (245.98 ns … 405.98 ns) 259.22 ns 356.82 ns 401.38 ns

summary for dynamic route - GET /user/lookup/username/hey
  Hono RegExpRouter
   1.16x faster than @medley/router
   1.27x faster than find-my-way
   1.3x faster than koa-router
   1.58x faster than koa-tree-router
   2.38x faster than trek-router
   2.68x faster than Hono TrieRouter
   3.39x faster than express (WARNING: includes handling)
```

```
• mixed static dynamic - GET /event/abcd1234/comments
---------------------------------------------------------------------------- -----------------------------
Hono RegExpRouter                     185.69 ns/iter (174.91 ns … 350.57 ns) 178.87 ns 248.85 ns 250.18 ns
Hono TrieRouter                       495.27 ns/iter (467.85 ns … 693.42 ns) 517.84 ns 669.43 ns 693.42 ns
@medley/router                         204.9 ns/iter (196.53 ns … 435.48 ns) 201.86 ns 268.48 ns 271.07 ns
find-my-way                           231.49 ns/iter (218.18 ns … 651.66 ns) 224.91 ns 303.14 ns 422.08 ns
koa-tree-router                       232.55 ns/iter (213.71 ns … 642.89 ns) 231.68 ns 335.15 ns  457.5 ns
trek-router                           375.87 ns/iter (357.45 ns … 453.71 ns) 371.06 ns 452.52 ns 453.71 ns
express (WARNING: includes handling)  744.96 ns/iter (690.56 ns … 874.35 ns) 778.95 ns 874.35 ns 874.35 ns
koa-router                            280.95 ns/iter (273.88 ns … 354.77 ns) 277.15 ns 354.35 ns 354.77 ns

summary for mixed static dynamic - GET /event/abcd1234/comments
  Hono RegExpRouter
   1.1x faster than @medley/router
   1.25x faster than find-my-way
   1.25x faster than koa-tree-router
   1.51x faster than koa-router
   2.02x faster than trek-router
   2.67x faster than Hono TrieRouter
   4.01x faster than express (WARNING: includes handling)
```

```
• post - POST /event/abcd1234/comment
---------------------------------------------------------------------------- -----------------------------
Hono RegExpRouter                      176.4 ns/iter (165.13 ns … 399.69 ns) 170.03 ns 340.78 ns 343.89 ns
Hono TrieRouter                        481.9 ns/iter  (459.2 ns … 709.09 ns) 497.73 ns 544.45 ns 709.09 ns
@medley/router                        196.83 ns/iter (190.49 ns … 276.23 ns) 193.87 ns 257.18 ns 258.75 ns
find-my-way                           230.39 ns/iter (216.49 ns … 432.98 ns) 225.69 ns 362.38 ns 396.37 ns
koa-tree-router                       197.11 ns/iter  (185.3 ns … 409.62 ns) 189.76 ns 339.91 ns  369.8 ns
trek-router                           342.75 ns/iter (320.11 ns … 482.31 ns) 338.26 ns  424.3 ns 482.31 ns
express (WARNING: includes handling)  771.15 ns/iter (719.96 ns … 868.24 ns)  801.8 ns 868.24 ns 868.24 ns
koa-router                            281.43 ns/iter    (270 ns … 845.24 ns)  273.8 ns 431.55 ns 845.24 ns

summary for post - POST /event/abcd1234/comment
  Hono RegExpRouter
   1.12x faster than @medley/router
   1.12x faster than koa-tree-router
   1.31x faster than find-my-way
   1.6x faster than koa-router
   1.94x faster than trek-router
   2.73x faster than Hono TrieRouter
   4.37x faster than express (WARNING: includes handling)
```

```
• long static - GET /very/deeply/nested/route/hello/there
---------------------------------------------------------------------------- -----------------------------
Hono RegExpRouter                     186.33 ns/iter (173.07 ns … 471.34 ns) 176.23 ns 423.24 ns  447.8 ns
Hono TrieRouter                       596.31 ns/iter (552.77 ns … 885.07 ns) 622.17 ns 885.07 ns 885.07 ns
@medley/router                         153.5 ns/iter (146.78 ns … 276.27 ns) 150.01 ns 228.09 ns 233.19 ns
find-my-way                           225.42 ns/iter (211.88 ns … 470.68 ns) 216.22 ns  368.7 ns 374.38 ns
koa-tree-router                       149.99 ns/iter  (138.15 ns … 267.1 ns) 145.84 ns 238.43 ns 257.82 ns
trek-router                           223.83 ns/iter (214.91 ns … 438.52 ns)  219.3 ns 294.52 ns 384.65 ns
express (WARNING: includes handling)  704.11 ns/iter  (654.1 ns … 871.75 ns) 731.77 ns 871.75 ns 871.75 ns
koa-router                            249.48 ns/iter (240.57 ns … 461.07 ns) 243.83 ns 328.85 ns 430.88 ns

summary for long static - GET /very/deeply/nested/route/hello/there
  koa-tree-router
   1.02x faster than @medley/router
   1.24x faster than Hono RegExpRouter
   1.49x faster than trek-router
   1.5x faster than find-my-way
   1.66x faster than koa-router
   3.98x faster than Hono TrieRouter
   4.69x faster than express (WARNING: includes handling)
```

```
• wildcard - GET /static/index.html
---------------------------------------------------------------------------- -----------------------------
Hono RegExpRouter                     179.74 ns/iter  (168.36 ns … 505.2 ns)  172.1 ns 301.09 ns 429.03 ns
Hono TrieRouter                       380.33 ns/iter (356.47 ns … 660.87 ns)  379.8 ns 593.38 ns 660.87 ns
@medley/router                        170.49 ns/iter (161.83 ns … 295.87 ns) 167.55 ns 232.78 ns 261.57 ns
find-my-way                           204.86 ns/iter (191.16 ns … 339.58 ns) 199.85 ns 288.19 ns 301.88 ns
koa-tree-router                       246.26 ns/iter (232.76 ns … 343.84 ns) 239.21 ns 317.59 ns 323.75 ns
trek-router                           336.63 ns/iter (324.76 ns … 511.53 ns) 329.93 ns 421.44 ns 511.53 ns
express (WARNING: includes handling)  835.68 ns/iter (786.98 ns … 921.52 ns) 865.44 ns 921.52 ns 921.52 ns
koa-router                            254.61 ns/iter    (247 ns … 444.44 ns) 250.19 ns 319.26 ns 320.58 ns

summary for wildcard - GET /static/index.html
  @medley/router
   1.05x faster than Hono RegExpRouter
   1.2x faster than find-my-way
   1.44x faster than koa-tree-router
   1.49x faster than koa-router
   1.97x faster than trek-router
   2.23x faster than Hono TrieRouter
   4.9x faster than express (WARNING: includes handling)
```

```
• all together
---------------------------------------------------------------------------- -----------------------------
Hono RegExpRouter                     704.36 ns/iter (642.59 ns … 840.34 ns) 727.19 ns 840.34 ns 840.34 ns
Hono TrieRouter                         2.61 µs/iter     (2.53 µs … 2.89 µs)   2.63 µs   2.89 µs   2.89 µs
@medley/router                        706.27 ns/iter (680.35 ns … 813.39 ns) 729.65 ns 813.39 ns 813.39 ns
find-my-way                             1.05 µs/iter   (987.37 ns … 1.38 µs)   1.07 µs   1.38 µs   1.38 µs
koa-tree-router                       951.36 ns/iter     (894.3 ns … 1.1 µs) 978.63 ns    1.1 µs    1.1 µs
trek-router                             1.79 µs/iter     (1.74 µs … 1.86 µs)   1.82 µs   1.86 µs   1.86 µs
express (WARNING: includes handling)    4.37 µs/iter     (4.26 µs … 5.09 µs)   4.36 µs   5.09 µs   5.09 µs
koa-router                              1.37 µs/iter     (1.33 µs … 1.56 µs)    1.4 µs   1.56 µs   1.56 µs

summary for all together
  Hono RegExpRouter
   1x faster than @medley/router
   1.35x faster than koa-tree-router
   1.5x faster than find-my-way
   1.94x faster than koa-router
   2.54x faster than trek-router
   3.71x faster than Hono TrieRouter
   6.2x faster than express (WARNING: includes handling)
```

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @usualoma !

How about these benchmark scripts and the results? If you like, you can run the scripts in your environment. And, we don't have to force to do it, but perhaps there is a point where we can improve it?

**Comment by usualoma** [comment]
@yusukebe 

#845 resulted in the following in my environment

```
% npm run bench:node

...

summary for all together
  Hono RegExpRouter
   1.25x faster than koa-tree-router
   1.26x faster than @medley/router
   1.89x faster than trek-router
   2.21x faster than find-my-way
   4.18x faster than Hono TrieRouter
   20.84x faster than express (WARNING: includes handling)
   27.52x faster than koa-router
```

What do you think?

**Comment by yusukebe** [comment]
@usualoma 

Thanks. I'll check it later.

**Comment by yusukebe** [comment]
Thanks for #845 .

This benchmark is very useful.

For example, benchmarks that handle HTTP requests such as these are also important. Of these, Hono is the fastest or second fastest.

* https://github.com/denosaurs/benc
* https://github.com/SaltyAom/bun-http-framework-benchmark

However, these can be advantageous or disadvantageous depending on the features of each framework. For example, in the case of Hono, using header values is convenient for the users, but their handling is complicated inside the core.

So it is very important to have a benchmark that is less dependent on the specifications. With this, we can say that Hono is Ultra-fast.

Then, you can use this benchmark script!

**Pull request merged**
