### PR TITLE
feat: implement stream.onAbort

### PR DESCRIPTION
**Pull request by sor4chi**
### Author should do the followings, if applicable

- [x] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

related: #1795 #1770

### CODE REVIEW

**Comment by sor4chi** [comment]
Happy new year @yusukebe.
Yes, please.

**Comment by yusukebe** [comment]
@sor4chi 

Happy New Year!

I've checked it and tried to use it in some environment. But is this expected behavior?

https://github.com/honojs/hono/assets/10682/63ce4840-8c8e-45c9-bb81-28a6eb8a4985

The code:

```ts
import { serve } from '@hono/node-server'
import { Hono } from '../../src'
import { streamText } from '../../src/helper/streaming'

export const app = new Hono()

app.get('/', async (c) => {
  return streamText(c, async (stream) => {
    stream.onAbort(async () => {
      console.log('Aborted!')
      await stream.close()
    })
    for (;;) {
      stream.writeln('Hello World!')
      console.log('Hello World!')
      await new Promise((r) => setTimeout(r, 1000))
    }
  })
})

serve(app)
```

**Comment by HeyITGuyFixIt** [comment]
@yusukebe in your example, the loop still goes on, but there is no logic to stop the loop after the stream is aborted. You could make it a while loop instead of a for loop, and check for a variable (e.g. `while (!aborted)`) that is set by the event handler.

**Comment by yusukebe** [comment]
Hi @HeyITGuyFixIt 

So you are saying that it should be code like this? I understand!

```ts
app.get('/', async (c) => {
  let aborted = false
  return streamText(c, async (stream) => {
    stream.onAbort(async () => {
      console.log('Aborted!')
      aborted = true
    })
    while (!aborted) {
      stream.writeln('Hello World!')
      console.log('Hello World!')
      await new Promise((r) => setTimeout(r, 1000))
    }
  })
})
```

**Comment by HeyITGuyFixIt** [comment]
@yusukebe yeah. Give it a try to make sure that works

**Comment by yusukebe** [comment]
@HeyITGuyFixIt 

It works well! What do you think of this PR? Looks good for you?

If @sor4chi can check again, I'd like to merge this into the next branch.

**Comment by sor4chi** [comment]
@yusukebe 
I have noticed this behavior, but since the purpose is to take an abort hook in the first place and not to close the stream.

So I'd like to leave it as it is since I think I can handle it by implementing it myself if I want to do it as @HeyITGuyFixIt has presented it.

**Comment by HeyITGuyFixIt** [comment]
@yusukebe it looks good to me

**Comment by yusukebe** [comment]
@sor4chi @HeyITGuyFixIt Thanks! Merge now.

**Pull request merged**
