### PR TITLE
feat(adaptor): Enhance AWS Lambda Event Handling and Interface

### PR DESCRIPTION
**Pull request by watany-dev**
fixed https://github.com/honojs/hono/issues/1620

To provide full access to the Event, which is the input for AWS Lambda, the following modifications have been made:

## 1. Review of the Event
- Confirmed that having API Gateway versions 1.0 and 2.0 is sufficient after reviewing the specifications. The official documentation states that the Event for the traditional Lambda URL is same to version 2.0.
  - [APIgw event](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html)
  - [Lambda URL event](https://docs.aws.amazon.com/lambda/latest/dg/urls-invocation.html#urls-payloads)

- Added missing properties in the Event Interface.

- Renamed the externally exported `LambdaFunctionUrlRequestContext` to `ApiGatewayRequestContextV2` for name alignment with Event.
  - This is a breaking change, so concurrently using the old name's copied Type for a certain period might be beneficial.

## 2. Access to the Event
- Defined as `export type LambdaEvent = APIGatewayProxyEvent | APIGatewayProxyEventV2` and exported in the index.
  - Allows users to specify using Bindings.

## 3. Discontinuation of requestContext (Not Yet Implemented)
- Currently obtained as follows, which is cumbersome as it requires users to choose between v1 and v2 for the request context.

```typescript
import { Hono } from 'hono'
import type { ApiGatewayRequestContext } from 'hono/aws-lambda'
import { handle } from 'hono/aws-lambda'

type Bindings = {
  requestContext: ApiGatewayRequestContext 
}

const app = new Hono<{ Bindings: Bindings }>()

app.get('/custom-context/', (c) => {
  const lambdaContext = c.env.requestContext
  return c.json(lambdaContext)
})

export const handler = handle(app)
```

With access to the event now available, this can be rewritten simply. Also, the internal unnecessary logic getRequestContext(event) can be removed.

```typescript
import { Hono } from 'hono'
// import type { ApiGatewayRequestContext } from 'hono/aws-lambda'
import type { LambdaEvent } from 'hono/aws-lambda'
import { handle } from 'hono/aws-lambda'

type Bindings = {
  event: LambdaEvent 
//   requestContext: ApiGatewayRequestContext 
}

const app = new Hono<{ Bindings: Bindings }>()

app.get('/custom-context/', (c) => {
//   const lambdaContext = c.env.requestContext
  const lambdaContext = c.env.event.requestContext
  return c.json(lambdaContext)
})

export const handler = handle(app)

```
If the removal of requestContext is approved, a comment like "Remove in Hono V4" can be added.

### Author should do the followings, if applicable

- [x] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @watany-dev 

I'll review this later. It will be merged into a "next" branch because this will be new feature.

**Comment by yusukebe** [comment]
Hi @watany-dev !

Could you fix the conflict? After fixing it, I'll merge this into a "next" branch for `v3.11.0.

**Comment by watany-dev** [comment]
@yusukebe 
Thanks. I fixed it.

**Review by yusukebe — APPROVED** [review]

**Review by yusukebe — COMMENTED** [review]
@watany-dev 

Sorry, one thing.

> This is a breaking change, so concurrently using the old name's copied Type for a certain period might be beneficial.

I think we should do that.  Let's make `LambdaFunctionUrlRequestContext` available and mark it as `deprecated`.

**Comment by watany-dev** [comment]
@yusukebe 
Yes, the conflicts should have been resolved.

**Comment by watany-dev** [comment]
After fully supporting the API Gateway V1 event, we found that the traditional support for ALB was no longer possible. Therefore, we have defined a new schema.

**Comment by yusukebe** [comment]
Hi @watany-dev 

Sorry for the late reply. I am sick in bed right now. Will review when I'm better. Thanks.

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@watany-dev 

I'm back. This great! Let's go with it.

**Comment by yusukebe** [comment]
Hi @watany-dev 

I'll release the new version `v3.11.0` soon. If there are any descriptions on the website that need updating, could you please create a PR for them?

**Pull request merged**
