### PR TITLE
feat(reg-exp-router): Lookup static path by using Object

### PR DESCRIPTION
**Pull request by usualoma**
Optimize paths that do not contain variables by doing a lookup via Object.
This optimization will also reduce the size of the regular expression generated when static paths are included, so there will be no negative impact on the overall result.

### CODE REVIEW

**Comment by usualoma** [comment]
### TODO

* [ ] Need to check for ambiguous paths. (does not affect performance)

**Comment by usualoma** [comment]
Completed.

* [x] static path ambiguous check
* [x] merge next branch
* [x] denoify

**Comment by yusukebe** [comment]
@usualoma 

Looks good! It becomes really ultra fast! You already know this, but for reference, here are the results in my environment with the changes. It is the fastest not only in "all together" but in most others.

SS

SS

`find-my-way` is used in Fastify, and the other routers are all top-class among the many JavaScript routers. So, winning them means that RegExpRouter is now the fastest router in the JavaScript world!! You can be proud of this work.

Great!! Thanks!!

**Comment by usualoma** [comment]
@yusukebe Thanks!

Thanks to Router::Boom, thanks to hono's project, thanks to the points made by the benchmark script in #843, I think we got this result.
I too am happy to be involved with the hono's RegExpRouter that is the fastest in the world.

**Pull request merged**
