### PR TITLE
feat(context): c.redirect support punycode and URL object

### PR DESCRIPTION
**Pull request by EdamAme-x**
### The author should do the following, if applicable

- [x] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code

### CODE REVIEW

**Comment by EdamAme-x** [comment]
The performance side-effect caused by this change is under 300 μs.

**Comment by EdamAme-x** [comment]
## We can
`c.redirect(new URL("https://hono.dev"))`
`c.redirect("https://🔥.hono.dev")`

**Comment by yusukebe** [comment]
@EdamAme-x 

I'm sorry! Your PRs are closed because the `next` branch was merged and deleted. Can you create the PRs if you want me to review them again?

**Comment by EdamAme-x** [comment]
ok @yusukebe 
I'll change target to the main branch.

**Pull request closed without merging**
