### PR TITLE
Aws lambda cookies fix

### PR DESCRIPTION
**Pull request by OJ217**
### Issue: Unable to set multiple cookies when using aws-lambda adapter
The `getCookie`  and `setCookie` helpers don't work properly when handling multiple cookies with aws-lambda adapter because of different versions of request and response payload in `API Gateway Proxy Event`.

### Fix implementation: 
I created two functions `getCookies` and `setCookies` in src/adapter/aws-lambda/handler.ts file to get and set cookies payload/header corresponding to the version of the `API Gateway Proxy Event`. Additionally, two tests for this implementation are added in the lambda runtime test file.

### Author should do the followings, if applicable

- [ ] Add tests
- [ ] Run tests
- [ ] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @OJ217 !

Thank for the PR. Looks good for me.

@watany-dev  Can you review this?

**Comment by watany-dev** [comment]
@OJ217 
It generally seems fine, but it would be good to consider that the Lambda Function URL also has cookies, similar to API Gateway V2.
https://docs.aws.amazon.com/ja_jp/lambda/latest/dg/urls-invocation.html

**Comment by OJ217** [comment]
Hi @watany-dev!
I have checked the documentation for Lambda Function URL. It says *The request and response event formats follow the same schema as the [Amazon API Gateway payload format version 2.0](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.proxy-format).* Since the way of getting and setting cookies is determined by checking the payload version using the existing **isProxyEventV2**, I think it will also work for Lambda Function URL.

**Comment by yusukebe** [comment]
Thanks both.

@OJ217 Is this ready for merging?

**Comment by OJ217** [comment]
@yusukebe Sure!

**Comment by yusukebe** [comment]
Okay! Merging now.

**Pull request merged**
