### PR TITLE
feat: `parseBody()` for multi values' field

### PR DESCRIPTION
**Pull request by sor4chi**
### Author should do the followings, if applicable

Hi @yusukebe 
This is an implemention of the suggesion in #1018
As you mention, this changes have backward compatible.

- [x] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by rafaell-lycan** [comment]
That's quite specific but it might be useful. 👏

**Comment by yusukebe** [comment]
Hi @sor4chi 

Thanks for a great PR!

One thing. How do we treat an object with a single value? In the following example, it is about the value of `message`.

```ts
const data = new FormData()
data.append('file', 'aaa')
data.append('file', 'bbb')
data.append('message', 'hello')
```

In the current implementation, it returns the value of `message` as an array `['hello']`. But, I think the user would expect a `hello` to be returned in this case.

**Comment by sor4chi** [comment]
Hi, @yusukebe 

Indeed it is.
I completely forgot about the test case so I added it and reimplemented it, thanks.

**Review by yusukebe — APPROVED** [review]
Looks good! Let's go with this.

**Comment by yusukebe** [comment]
@sor4chi 

Thanks for fixing. I'd like to merge this, but this is a new feature, so will merge it into "next" branch for a next minor release "v3.8.0" later.

**Comment by sor4chi** [comment]
I look forward to using it at Hono Storage, thank you!

**Pull request merged**
