### PR TITLE
feat(types): Support types until 10 handlers

### PR DESCRIPTION
**Pull request by gabrielDonnantuoni**
Handle until 10 handlers on `app.method([path], ...handlers)` by simple adding more overloads.

This is not optimal by far. I'm compromised to find a better and beautiful solution, but until then I think this will cover more use cases, like I'm personally facing now.

### Author should do the followings, if applicable

- [X] Add tests
- [X] Run tests
- [X] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @gabrielDonnantuoni !

Thank you for this PR. As you mentioned, while it may not be the best solution, it seems to be the only way available. It looks good, and I'll review the details later.

**Review by yusukebe — COMMENTED** [review]
@gabrielDonnantuoni

I would like to extend the `OnHandlerInterface` to also support 10 handlers:

https://github.com/honojs/hono/blob/c3275eebf051b7f3ba9ab11264334ed31f7a98b0/src/types.ts#L337

Could you add the necessary code for this?

**Comment by gabrielDonnantuoni** [comment]
`OnHandlerInterface` updated, @yusukebe 🤝

**Comment by yusukebe** [comment]
@gabrielDonnantuoni

Great work!

Since this is a new feature, I'll merge it into the "[next](https://github.com/honojs/hono/tree/next)" branch for the upcoming minor release `v3.11.0`. It will be released later.

Thank you very much.

**Pull request merged**
