### PR TITLE
feat(jsx/dom): support getServerSnapshot in useSyncExternalStore

### LINKED ISSUE #2640: [jsx/dom] Support `getServerSnapshot`
### What is the feature you are proposing?

It would be great if `getServerSnapshot` is supported. If so, my favorite library [`swr`](https://swr.vercel.app) will work!

Like this code:

```tsx
import { render } from 'hono/jsx/dom'
import { hc } from 'hono/client'
import api from './api'

import useSWR from 'swr'

const client = hc<typeof api>('/api')

function App() {
  const $get = client.index.$get
  const fetcher = async () => {
    const res = await $get()
    return await res.json()
  }

  const { data, error, isLoading } = useSWR('api', fetcher)

  if (isLoading) return <h1>Loading...</h1>
  if (error) return <h1>Error: {error.message}</h1>
  return <h1>Hello {data?.name}</h1>
}

const domNode = document.getElementById('root')!
render(<App />, domNode)
```

### PR DESCRIPTION
**Pull request by usualoma**
Fixes #2640

### Author should do the followings, if applicable

- [x] Add tests
- [x] Run tests
- [x] `bun denoify` to generate files for Deno

### CODE REVIEW

**Comment by usualoma** [comment]
@yusukebe 
I haven't tried it with `swr`, but I think this implementation satisfies the external specification of `getServerSnapshot`. May I try it in your environment? If it works well, you can have it merged with the current contents.

**Comment by yusukebe** [comment]
@usualoma 

> I haven't tried it with `swr`, but I think this implementation satisfies the external specification of `getServerSnapshot`. May I try it in your environment? If it works well, you can have it merged with the current contents.

I've tried it with `swr` but it did not work. You can see and try the code:

https://github.com/yusukebe/hono-jsx-spa/tree/swr

The screen cast - showing only `loading...`: 

https://github.com/honojs/hono/assets/10682/30dd76a6-6cad-4eea-aba3-d3b07a77222a

**Comment by usualoma** [comment]
@yusukebe 

Ah ok, it looks like swr is loading useSyncExternalStore from a separate package. I added the following configuration to your app and now I get "Hello Hono!"

```diff
diff --git a/vite.config.ts b/vite.config.ts
index 993a823..67c6421 100644
--- a/vite.config.ts
+++ b/vite.config.ts
@@ -8,7 +8,8 @@ export default defineConfig(({ mode }) => {
     resolve: {
       alias: {
         react: 'hono/jsx/dom',
-        'react-dom': 'hono/jsx/dom'
+        'react-dom': 'hono/jsx/dom',
+        'use-sync-external-store/shim/index.js': 'hono/jsx/dom',
       }
     }
   }
```

**Comment by yusukebe** [comment]
@usualoma Ooooooh great!!

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@usualoma 

Thank you! I'll merge this right now and ship a **patch** release that includes this change because it's a small `feat` (it may be a huge thing for us!).

**Pull request merged**
