### PR TITLE
fix(serveStatic): support serving file from absolute path for Deno and Bun

### PR DESCRIPTION
**Pull request by oon00b**
fix: #3107 

This PR may be related to issue #2200 .

### The author should do the following, if applicable

- [x] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code
- [ ] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

**Comment by oon00b** [comment]
Sorry, the simular PR already existed in [`honojs/node-sever`](https://github.com/honojs/node-server/pull/78). I was missing it because I have never used Node.js.

May I close my PR?

**Comment by yusukebe** [comment]
Hi @oon00b 

We're not sure we will accept this PR, but regarding supporting the absolute path, this will be a new feature. There are some concerns, so please give us a time.

**Comment by schettn** [comment]
If anyone has this error, this is my workaround:

```ts
 const relativePathToScript = path.relative(process.cwd(), __dirname)

  app.get(
    '/__studio/*',
    serveStatic({
      root: `${relativePathToScript}/../studio/dist`,

      rewriteRequestPath: path => {
        return path.replace('/__studio', '')
      },
      onNotFound: (path, c) => {
        console.log('not found', path, c.req.url)
      }
    })
```

**Comment by cj-1010-1414** [comment]
I think I have fixed the bug. It can now detect absolute and relative path without creating additional options or properties like `isAbsolutePath`, without creating additional test. How do I pull request?

**Comment by oon00b** [comment]
completed in #3420

**Pull request closed without merging**
