### PR TITLE
feat: pass context to onNotFound callback in serveStatic

### PR DESCRIPTION
**Pull request by sor4chi**
#1810 

### Author should do the followings, if applicable

- [x] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by sor4chi** [comment]
I have no idea to infer Middleware Handler's Context and pass it to onNotFound argument's context.

**Comment by yusukebe** [comment]
@sor4chi 

> I had no idea how to infer Middleware Handler's Context and pass it to onNotFound argument's context.

Please tell us along with specific examples.

**Comment by sor4chi** [comment]
```ts
export type ServeStaticOptions<E extends Env> = {
  root?: string
  path?: string
  rewriteRequestPath?: (path: string) => string
  onNotFound?: (path: string, c: Context<E>) => void | Promise<void>
}

const DEFAULT_DOCUMENT = 'index.html'

export const serveStatic = <E extends Env = Env>(options: ServeStaticOptions<E> = { root: '' }): MiddlewareHandler<E> => {
```

If we could do something like this, we should be able to access envs type-safely from the callback context, but is this impossible with the current design?

**Comment by yusukebe** [comment]
@sor4chi 

I struggled for hours to implement it, but I can't. Maybe it's impossible. I'll make more time to try.

**Comment by sor4chi** [comment]
Okay, Thank you so much!
Even if this is not possible, it might help users just to be able to put Env Generics in `serveStatic`. If this is not possible, I will do so.

**Comment by yusukebe** [comment]
@sor4chi 

Are you imagining the following code? If so, please implement that to make it true!

```ts
const app = new Hono<Env>()

app.get(
  '/static/*',
  serveStatic<Env>({
    onNotFound: (path, c) => {},
  })
)
```

**Comment by sor4chi** [comment]
Hi, @yusukebe.
I finished supporting Env support for context.

**Comment by yusukebe** [comment]
@sor4chi 

Thanks! But, also please change the `adapter/cloudflare-workers/server-static-module.ts`.

**Comment by sor4chi** [comment]
@yusukebe fixed! thanks for finding it!

**Comment by yusukebe** [comment]
@sor4chi 

Thanks! I'll merge this into "next" now.

**Pull request merged**
