### PR TITLE
feat: use added app's errorHandler

### PR DESCRIPTION
**Pull request by usualoma**
Derived from #866, version for errorHandler only

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @usualoma 

Using `compose`! This is a good idea!

It is not we should do usually, but how about changing the order of the `compose` arguments?

```ts
const compose = (
  middleware: Function[],
  onNotFound?: NotFoundHandler,
  onError?: ErrorHandler
) => Function
```

To:

```ts
const compose = (
  middleware: Function[],
  onError?: ErrorHandler, 
  onNotFound?: NotFoundHandler
) => Function
```

By doing so, we can remove the following `notFoundHandler`:

https://github.com/honojs/hono/pull/871/commits/0707d87d0e5b4b662e6b7bf258d5c7f61477e9c4#diff-a6d396782ec1222678901e1d0ac0bf9bb5b63f6560fd26fd81694dc2b4de5a89R129

`compose` is only used in `hono.ts` and it is not difficult to rewrite `compose.test.ts`. I think it's good to keep code short.

**Comment by usualoma** [comment]
> It is not we should do usually, but how about changing the order of the compose arguments?

Yes, I agree.

Swapped and pushed.
ec3a21b

**Comment by yusukebe** [comment]
Thanks! I'll merge it.

**Comment by yusukebe** [comment]
Ah, wait. The following tests "one handler pattern" will fail:

```ts
describe('onError', () => {
  const app = new Hono()
  const sub = new Hono()

  sub.get('/ok', (c) => c.text('OK'))

  sub.get('/error', () => {
    throw new Error('This is Error')
  })

  sub.onError((err, c) => {
    return c.text('onError by sub', 500)
  })

  app.route('/sub', sub)

  it('handled by app', async () => {
    const res = await app.request('https://example.com/sub/ok')
    expect(res.status).toBe(200)
  })
})
```

SS

Using the `compose` is a good idea, but it does not support "one handler pattern".

**Comment by usualoma** [comment]
@yusukebe Oh, sorry, you're right. I'll reconsider.

**Pull request merged**
