### PR TITLE
feat: `hc` - Hono Client

### PR DESCRIPTION
**Pull request by yusukebe**
This PR introduces a new feature, "Hono Client". "hc" for the same purpose was built as `@hono/hc`, but making it obsolete, includes it in the core package.

## Usage

First, create the API server. Write the endpoint and export the type of route:

```ts
// server.ts
import { Hono } from 'hono'
import { z } from 'zod'
import { zValidator } from '@hono/zod-validator'

const app = new Hono()

const route = app.post(
  '/api/v2/posts',
  zValidator(
    'json',
    z.object({
      id: z.number(),
      title: z.string(),
    })
  ),
  (c) => {
    const { id, title } = c.req.valid('json')
   // Use `c.jsonT()` to emit types
    return c.jsonT({
      message: `${id} is ${title}`,
      success: true,
    })
  }
)

export type AppType = typeof route // export the type
```

Second, start writing the `client.ts`, import the type from `server.ts` and pass it to the `hc` function as Generics:

```ts
import { hc } from 'hono/client'

import type { AppType } from './server'

const client = hc<AppType>('http://localhost:8787/')
```

Then, time for magic:

https://user-images.githubusercontent.com/10682/216456881-7c9d4bad-e669-4cfb-a027-86ce98074973.mov

It will suggest the code based on the path and schema of the API server endpoint.

And handle the response:

https://user-images.githubusercontent.com/10682/216457919-1484ed48-b1d3-4428-b6be-565f7a9ee879.mov

`data` has the appropriate type. Great!

The final code is here:

```ts
const res = await client.api.v2.posts.$post({
  json: {
    id: 123,
    title: 'Hello!!',
  },
})

const data = await res.json()

console.log(data.message)
```

### Don't you use `@hono/hc`?

Separating core packages and `hc` is good, but it makes development difficult. For example, if we want to refer to the same `Hono` or `ValidationTypes` types, but the projects are separated, it is difficult to do so, and type errors occur frequently. Even if we include it in the core package, it is independent of `hono`, so the bundle size will not change unless we use it. In addition, it is very small and does not depend on an external library.

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi, @usualoma @ThatOneBro @cleaton and others!

How about this? You don't have to do a detailed review, I'd like to hear your brief thoughts.

**Comment by cleaton** [comment]
@yusukebe over all I think it looks good, the client api is easy to use and I like that it's possible to pass additional request parameters. 

I think hiding the typed result behind a `json()` method togeter with all the existing `Response` methods makes it difficult to discover (Result has so many methods/attributes...). I would suggest giving another name than `json` maybe `ht()` for `HonoType` or something else. Can also consider using an interface to split the `Result` methods, ex:
```ts
interface HonoResponse<T> {
   response(): Response
   ht(): TypedResponse<T>
```

This kind of interface could also help make the client composable with server endpoints in a way where it's possible to forward responses from nested Hono Servers without unwrapping the response. For example in Cloudflare, have endpoint defined in a worker, inside the endpoint use hono client to call DurableObject instance and directly return the result (making the worker endpoint and DO endpoint return type identical). Current implementation which requires returning `c.jsonT()` requires extracting the DO response in the worker endpoint.

not directly related to this PR, but i happened to see
```ts
 export type TypeResponse<T = unknown> = {
   response: Response | Promise<Response>
   data: T
   format: 'json' // Currently, support only `json` with `c.jsonT()`
 }
 ```
 it does not look like `data` is used anywhere so I think it can be removed (it's already encoded inside `response`). A typescript type can contain type parameters that are not used in any field/value (very useful for passing type info forward without incuring runtime cost of passing the actual object)

**Comment by yusukebe** [comment]
Hi @cleaton ! 

> I think hiding the typed result behind a json() method togeter with all the existing Response methods makes it difficult to discover (Result has so many methods/attributes...).

Is this referring to the client's `res.json()`?

```ts
const res = await client.api.v2.posts.$get()

const data = await res.json() // <--- this?
```

You are right `json()` is a hard keyword to discover. But, this is because I want to keep compatibility with the `Response` object, which is the return value of the `fetch`. I thought about wrapping the `fetch`'s `Response` like `HonoResponse`, but decided against it because it would be too complicated.

**Comment by ThatOneBro** [comment]
@yusukebe I think this is great! Everything looks really nice to me. I haven't used it yet but once I use it I will be sure to give more feedback. For now, I think this is a great decision 😄

**Comment by usualoma** [comment]
@yusukebe
This is some really great magic!
I think this PR is well implemented with lean and less code, and is highly maintainable.

**Comment by yusukebe** [comment]
Hi @cleaton !

I'll merge this PR soon.


This feature - Hono Client - is 
Yoru comment https://github.com/honojs/hono/issues/582#issuecomment-1279598527 
https://github.com/honojs/hono/issues/582#issuecomment-1279598527

**Comment by cleaton** [comment]
@yusukebe thanks for your hard work! Looking forward to using it ~

**Comment by yusukebe** [comment]
I'll merge it now!

**Pull request merged**
