### PR TITLE
feat(jwt): add support for different date formats

### PR DESCRIPTION
**Pull request by NicoPlyley**
A draft PR for #1501 

### Author should do the followings, if applicable

- [ ] Add tests
- [ ] Run tests
- [ ] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @NicoPlyley 

Thanks for this PR. Looks good for me. But I want to know the opinion of @Code-Hex .

cc: @Code-Hex 
What do you think about this? And if it's OK, could you review this?

**Comment by Code-Hex** [comment]
Hi @NicoPlyley and @yusukebe 

According to RFC 7519, it is stated that [exp](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.4), [nbf](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.5), and [iat](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.6) must always be NumericDate values.

NumericDate is the last definition in [Section 2. Terminology](https://datatracker.ietf.org/doc/html/rfc7519#section-2), and is defined as the number of seconds (not milliseconds) since Epoch:
> A JSON numeric value representing the number of seconds from 1970-01-01T00:00:00Z UTC until the specified UTC date/time, ignoring leap seconds.  This is equivalent to the IEEE Std 1003.1, 2013 Edition [[POSIX.1](https://datatracker.ietf.org/doc/html/rfc7519#ref-POSIX.1)] definition "Seconds Since the Epoch", in which each day is accounted for by exactly 86400 seconds, other than that non-integer values can be represented.  See [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339) [[RFC3339](https://datatracker.ietf.org/doc/html/rfc3339)] for details regarding date/times in general and UTC in particular.

I think it is desirable for a widely adopted library that provides a JWT package to be strict in its specifications. This is because users sometimes prioritize strictness over convenience.

**Comment by yusukebe** [comment]
Thanks @Code-Hex 

It is certainly important to follow the Spec and I agree with you.

@NicoPlyley :

What do you think about this?

**Comment by NicoPlyley** [comment]
I am okay with any decision you make. I got the idea from other popular packages like json-web-token and jose which do allow different types of input. But I understand if it's not in the realm.

**Comment by yusukebe** [comment]
Hi @NicoPlyley 

Thank you for your understanding. We will not accept and close this PR at this time. Thank you and contribute again.

**Pull request closed without merging**
