### PR TITLE
fix: `createHandler` Response Types (handler x1)

### PR DESCRIPTION
**Pull request by nakasyou**
I tried to resolve https://github.com/honojs/honox/issues/24.
But I can't resolve it because HonoX's `createRoute` is missing response type.
`createRoute` is using Hono's`createFactory`
So I search it, I found cause.

`createHandler` is missing response type when there is **one** handler.
We can solve this bug if this PR merged.
### Author should do the followings, if applicable

- [ ] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by nakasyou** [comment]
@yusukebe Could you review it?

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@nakasyou 

Thanks. That was a bug!

**Comment by nakasyou** [comment]
Thank you!

**Pull request merged**
