### PR TITLE
fix: Dot-containing paths do not correctly receive extension completion.

### PR DESCRIPTION
**Pull request by watany-dev**
fixes: https://github.com/honojs/hono/pull/2236

### Author should do the followings, if applicable

- [x] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by watany-dev** [comment]
This partially resolves this issue, and allows the "." except for the extension completion accuracy.
https://github.com/honojs/hono/issues/2239

**Comment by watany-dev** [comment]
@usualoma 
Can I have it reviewed?

**Comment by usualoma** [comment]
@watany-dev Thank you!

First, in response to your comment in #2239, I think your point below is spot on.

> For those who want to use extensions like .html.html, they can simply specify it explicitly in the Route :)

We can write as follows

```ts
app.get(
  '/shops/:id.html',.
  async (c) => { ... }
)
```

Thus, I think the question I raised in #2239 will be answered by this PR.

I have no objection to this PR test case, but I think `.endsWith()` would be sufficient for `getPathWithExpectedExtension()`. No?

```ts
const generateFilePath = (routePath: string, outDir: string, mimeType: string) => {
  const extension = determineExtension(mimeType)

  if (routePath.endsWith(`.${extension}`)) {
    return joinPaths(outDir, routePath)
  }

  if (routePath === '/') {
    return joinPaths(outDir, `index.${extension}`)
  }
  if (routePath.endsWith('/')) {
    return joinPaths(outDir, routePath, `index.${extension}`)
  }
  return joinPaths(outDir, `${routePath}.${extension}`)
}
```

**Comment by watany-dev** [comment]
Thanks for reviewing this!
I didn't know there was an endWith in the standard API. This one is great.
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith

**Comment by usualoma** [comment]
Oh, sorry, not quite right, the following doesn't work good. It would be a variable `id.html`

```ts
app.get(
  '/shops/:id.html',.
  async (c) => { ... }
)
```

Well, okay, that's a separate issue, so let's consider it in other issue 🙇

**Comment by watany-dev** [comment]
> I have no objection to this PR test case, but I think .endsWith() would be sufficient for getPathWithExpectedExtension(). No?
This has been fixed.

**Review by yusukebe — APPROVED** [review]
Looks good to me! I'll merge.

**Pull request merged**
