### PR TITLE
feat(jwt): Use Signed Cookie in JWT Middleware

### PR DESCRIPTION
**Pull request by newarifrh**
Continuing from #2403 & fixing for #2398 where there was no update, and slightly fixed the use/non-use of prefixOptions

### The author should do the following, if applicable
- [x] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code
- [x] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

**Comment by yusukebe** [comment]
HI @newarifrh 

Thank you for the PR. Could you add tests not to take down the test coverage?

**Comment by newarifrh** [comment]
> HI @newarifrh
> 
> Thank you for the PR. Could you add tests not to take down the test coverage?

Hi @yusukebe,
I just added a few tests for codes that have not been covered

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@newarifrh 

Looks good to me! I'll merge this into the `next` branch for the next minor version, `v4.5.0` now. It will be released during July. Thank you!

**Pull request merged**
