### PR TITLE
fix(utils/crypto): fix types of crypto utility

### PR DESCRIPTION
**Pull request by EdamAme-x**
Related: https://github.com/honojs/hono/pull/3604#discussion_r1825781670

### The author should do the following, if applicable

- [ ] Add tests
- [ ] Run tests
- [ ] `bun run format:fix && bun run lint:fix` to format the code
- [ ] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

**Comment by EdamAme-x** [comment]
The test will pass when the associated PRs are merged

**Comment by yusukebe** [comment]
@EdamAme-x 

Can you update this?

**Comment by EdamAme-x** [comment]
@yusukebe Ready

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@EdamAme-x 

Thank you!

**Pull request merged**
