### PR TITLE
feat: Allow multiple routing paths to be configured for a single middleware (handler).

### PR DESCRIPTION
**Pull request by EdamAme-x**
### Author should do the followings, if applicable

- [x] Add tests
- [ ] Run tests (Type errors occur in several independent places.
The function itself works.)
- [x] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by EdamAme-x** [comment]
`issue` is being prepared...

```
const app = new Hono();

app.get(["/a", "/b"], (c)  => {
  retrun c.text("d"):
})
```

**Comment by EdamAme-x** [comment]
There was a misunderstanding in the title.

In fact, user can set multiple passes for handlers and middleware.

You can easily express places that cannot be expressed with regular expressions alone and difficult places. Actually, I thought I wanted this function during development.

**Comment by yusukebe** [comment]
Hi @EdamAme-x,

This feature is valuable; however, I think it's too difficult to maintain correct type inference. It might become too complex or even impossible.

**Comment by yusukebe** [comment]
Hi @EdamAme-x 

I'll close this PR. If you have any idea to contribute, feel free to create your PR again. Thanks.

**Comment by EdamAme-x** [comment]
Agreed.

**Pull request closed without merging**
