### PR TITLE
Adding support to absolute path. Tested on Bun.

### PR DESCRIPTION
**Pull request by cj-1010-1414**
### The author should do the following, if applicable

- [X] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code
- [x] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @cj-1010-1414 

It is not a bug that the serve static does not support an absolute path. It's intended. Regarding supporting the absolute path, we are considering how we should support it. Either way, this will affect current user who uses this feature as a breaking change.

**Comment by cj-1010-1414** [comment]
Hope soon Hono support both relative and absolute path

**Comment by yusukebe** [comment]
@cj-1010-1414 

Okay. I'll work on it after releasing the next minor version.

**Comment by yusukebe** [comment]
This feature is implemented in #3420. Thanks!

**Pull request closed without merging**
