### PR TITLE
Handler stuck when awaiting aborted SSE stream

### PR DESCRIPTION
**Pull request by abhi12299**
Fixes: #2068
In the current version of Hono, the `stream.writeSSE` method was getting blocked indefinitely when the user disconnects from the SSE stream prematurely. Consider this example (taken from #2068):

```typescript
import { serve } from "@hono/node-server";
import { Hono } from "hono";
import { streamSSE } from "hono/streaming";

const app = new Hono();

let testId = 0;

app.get("/sse", (c) =>
  streamSSE(c, async (stream) => {
    try {
      const currentTestId = ++testId;
      let aborted = false;
      stream.onAbort(() => {
        aborted = true;
      });

      for (let i = 0; i < 10; i++) {
        console.log(currentTestId, "Iteration", i, aborted ? "(aborted)" : "");
        // If I await the writeSSE like this, it sometimes never returns when the stream is aborted
        await stream.writeSSE({ data: JSON.stringify({ iteration: i }) });
        await stream.sleep(1000);
      }
      console.log("Done");
    } catch (error) {
      console.error("Error", error);
    }
  })
);

const port = 8000;
console.log(`Server is running on port ${port}`);

serve({
  fetch: app.fetch,
  port,
});
```

When the client disconnects from the stream while the loop is still going on, the following things happen:
In the file `src/utils/stream.ts`:
```typescript
this.responseReadable = new ReadableStream({
  async pull(controller) {
    const { done, value } = await reader.read()
    done ? controller.close() : controller.enqueue(value)
  },
  cancel: () => {
    this.abortSubscribers.forEach((subscriber) => subscriber())
  },
})
```

`cancel` function runs, thereby running all the abort subscribers, but due to the loop in the test code provided above, the `pull` function still receives `done` as `false` and some value from the `reader`, and gets blocked indefinitely because the `controller` enqueued it.

It is difficult to reproduce this behaviour in the test suites, because aborting the request from code works fine. This is not the case when using a client such as `curl` or postman.

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @abhi12299 !

Thanks. Seems to be good. However, I want to hear the options from @watany-dev and @sor4chi .

**Comment by abhi12299** [comment]
Adding a suggestion here: we should also add a `connected` property on the `stream` object to let the user know if the client is still connected. As of now, there's no way to do that (as per my understanding).

**Comment by watany-dev** [comment]
Thanks. This is the event I saw when I reproduced some issue. Glad we were able to resolve it.

I think it is better to discuss stream.connected in another PR. As far as the use case is concerned, connected may be sufficient to be implemented only in streamSSE.

**Comment by sor4chi** [comment]
Thank you for this feature, I never thought of blocking readable. I agree.

**Comment by yusukebe** [comment]
@abhi12299 @watany-dev @sor4chi Thanks!

We will discuss `connected` in other PRs, but this PR will be merged!

**Pull request merged**
