### PR TITLE
fix: Remove `charset` parameter from MIME type of `application/json`

### LINKED ISSUE #3739: `charaset` parameter is not required for JSON MIME type
### What version of Hono are you using?

4.6.13

### What runtime/platform is your app running on? (with version if possible)

Node.js 22

### What steps can reproduce the bug?

When a static JSON file is displayed with `serveStatic()`, `application/json; charset=utf-8` is returned.

### What is the expected behavior?

The `charset` parameter is not required for the MIME type of a JSON.

The current JSON specification (RFC 8259) does not allow anything other than UTF-8 to begin with.

In IANA, `application/json` is “Optional parameters: n/a”.

- [RFC 8259 – Section 11](https://www.rfc-editor.org/rfc/rfc8259.html#section-11)
- [Media Types – application/json](https://www.iana.org/assignments/media-types/application/json)

Therefore, the MIME type should be only `application/json`.

### What do you see instead?

_No response_

### Additional information

I am ready to do PR !

### PR DESCRIPTION
**Pull request by SaekiTominaga**
fix #3739 

### The author should do the following, if applicable

- [ ] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code
- [ ] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @SaekiTominaga 

Thank you for the PR! I think you should change this line too:

https://github.com/honojs/hono/blob/8886320499fd1860f65107b6075914d9221b729e/src/context.ts#L780

**Comment by EdamAme-x** [comment]
https://github.com/honojs/hono/blob/47bb23c575a93d5fed4721935481a6a4cbf5cf1a/src/middleware/basic-auth/index.ts#L123
https://github.com/honojs/hono/blob/47bb23c575a93d5fed4721935481a6a4cbf5cf1a/src/context.ts#L780
https://github.com/honojs/hono/blob/47bb23c575a93d5fed4721935481a6a4cbf5cf1a/src/middleware/bearer-auth/index.ts#L106
https://github.com/honojs/hono/blob/47bb23c575a93d5fed4721935481a6a4cbf5cf1a/src/context.test.ts#L54
https://github.com/honojs/hono/blob/47bb23c575a93d5fed4721935481a6a4cbf5cf1a/src/adapter/aws-lambda/handler.test.ts#L16
https://github.com/honojs/hono/blob/47bb23c575a93d5fed4721935481a6a4cbf5cf1a/runtime-tests/lambda/index.test.ts#L540
https://github.com/honojs/hono/blob/47bb23c575a93d5fed4721935481a6a4cbf5cf1a/src/middleware/bearer-auth/index.test.ts#L403
https://github.com/honojs/hono/blob/47bb23c575a93d5fed4721935481a6a4cbf5cf1a/src/validator/validator.test.ts#L132
https://github.com/honojs/hono/blob/47bb23c575a93d5fed4721935481a6a4cbf5cf1a/src/adapter/lambda-edge/handler.test.ts#L16
https://github.com/honojs/hono/blob/47bb23c575a93d5fed4721935481a6a4cbf5cf1a/src/middleware/basic-auth/index.test.ts#L298

**Comment by SaekiTominaga** [comment]
Thanks for pointing that out!

@yusukebe I have addressed it.
@EdamAme-x I have removed `charset` parameter or deleted unnecessary test cases.

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
Thanks @SaekiTominaga ! Looks good. I'll merge it now.

**Pull request merged**
