### PR TITLE
refactor(request): show user-friendly type for `c.req.param()`

### PR DESCRIPTION
**Pull request by usualoma**
### Before

CleanShot 2024-05-24 at 17 46 31@2x

### After

CleanShot 2024-05-24 at 17 46 49@2x

### The author should do the following, if applicable

- <del>Add tests</del>
    - The [tests](https://github.com/honojs/hono/blob/main/src/hono.test.ts#L2342-L2352) we have now are sufficient.
- [x] Run tests
- [x] `bun denoify` to generate files for Deno
- [x] `bun run format:fix && bun run lint:fix` to format the code

### CODE REVIEW

**Comment by usualoma** [comment]
@yusukebe How about this?

**Comment by yusukebe** [comment]
@usualoma 

Looks good to me!

Let's merge. But right now, shall we merge it into the `next`?

**Comment by usualoma** [comment]
@yusukebe  Understood!
Merged next into this branch.

**Comment by yusukebe** [comment]
@usualoma 

Yeah. `denoify` is no longer needed! Merging.

**Pull request merged**
