### PR TITLE
docs: Add TSDoc comments to improve code documentation and readability

### PR DESCRIPTION
**Pull request by fzn0x**
This PR will takes a long time, I wouldn't finish it in a day.

But this is a good start, anyone can contribute in my repository https://github.com/fzn0x/hono/tree/fzn0x/tsdoc

### The author should do the following, if applicable

- [ ] Add tests
- [ ] Run tests
- [ ] `bun denoify` to generate files for Deno
- [ ] `bun run format:fix && bun run lint:fix` to format the code

### CODE REVIEW

**Comment by fzn0x** [comment]
This will close https://github.com/honojs/hono/issues/1338

**Comment by fzn0x** [comment]
https://hono.dev/api/request

TODO: add `blob()` and `formData()`

**Comment by fzn0x** [comment]
https://github.com/honojs/hono/pull/2677/commits/56f1e1f703873d63c212afdcd32270e2b9b8e582 TSDoc comments are generally not as necessary in file that only contains modules export, but for completeness, it should be necessary

**Comment by yusukebe** [comment]
@fzn0x 

`mod.ts`, `middleware.ts`, and `help.ts` will be remove in #2662

**Comment by fzn0x** [comment]
Okay, lets skip those files @yusukebe

**Comment by fzn0x** [comment]
`src/*.ts` tsdoc is done, i will continue with `src/adapter`

**Comment by fzn0x** [comment]
I will continue this on weekend, have a lot of works recently, can't spend my time for open source make me sad

**Comment by yusukebe** [comment]
Hi @fzn0x 

I've merged other PRs to the `next`. I'll release the RC version for `v4.4`. And will release `v4.4.0` in the next week.

I'd like to use the documents you wrote in this PR, but you don't need to hurry. It can be merged after releasing the `v4.4.0`.

And, we have to refer to the JSDoc format that @goisaki wrote in the PRs #2680.

**Comment by yusukebe** [comment]
Hey @fzn0x 

For now, shall we merge the current PR which added docs to `src/*.ts`?

**Comment by yusukebe** [comment]
@fzn0x 

I'll release `v4.4.0` today. This PR is good, but it differs widely from the current `next` branch. So, after releasing `v4.4.0`, let's update and merge!

**Comment by fzn0x** [comment]
Hi @yusukebe sure, lets do it :)

**Pull request closed without merging**
