### PR TITLE
acceptable CryptoKey in JWT sign and verify

### PR DESCRIPTION
**Pull request by Code-Hex**
This is the last PR for https://github.com/honojs/hono/pull/2368

### What I did

- acceptable private key to verify jwt
- fixed code to accept CryptoKey object
- To clarify the responsibilities of jwa and jws, we have added files that refer to each and moved the logic to them.

### Author should do the followings, if applicable

- [x] Add tests
- [x] Run tests
- [x] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by Code-Hex** [comment]
I'm not sure why this is failed 😇 

https://github.com/honojs/hono/actions/runs/8317154739/job/22757563983?pr=2373

**Comment by Code-Hex** [comment]
There seemed to be a difference in bun.lockb because the local bun version was different from the CI version 😢

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
Good job @Code-Hex !

@metrue Can you review this too?

**Review by metrue — APPROVED** [review]
LGTM

**Comment by yusukebe** [comment]
Thanks @Code-Hex @metrue 

I'll merge this into the `jwt-algorithms` branch and ship it in the next minor release "v4.2". May be it will not so far!

**Pull request merged**
