### PR TITLE
feat(middleware/csrf): add csrf protection middleware

### PR DESCRIPTION
**Pull request by htunnicliff**
Closes honojs/hono#1688

### Author should do the followings, if applicable

- [ ] Add tests
- [ ] Run tests
- [x] `yarn denoify` to generate files for Deno

### CODE REVIEW

**Comment by usualoma** [comment]
Thank you, @htunnicliff.
I read the code.
It works well enough as a "Signed Double Submit Cookie".
To me, the current implementation seems to have some redundancies and would need to be rewritten in case of a merge, but anyway, I am sure the current code works correctly. It is excellent.

As for us, I think we (hono community) should first consider whether "Verifying Origin With Standard Headers" is enough as Sveltekit is doing or whether it is better to do up to "Signed Double Submit Cookie" as this PR does.

As I mentioned in https://github.com/honojs/hono/issues/1688#issuecomment-1836019924, I think "Verifying Origin With Standard Headers" is sufficient in hono's core, but if there seems to be more opinions that "Signed Double Submit Cookie" is needed, I think we can proceed with this PR.

**Comment by htunnicliff** [comment]
Thanks @usualoma! Feel free to modify this PR however you like!

**Comment by usualoma** [comment]
Hi @yusukebe.

My opinion is what I wrote in my comment above.

> As for us, I think we (hono community) should first consider whether "Verifying Origin With Standard Headers" is enough as Sveltekit is doing or whether it is better to do up to "Signed Double Submit Cookie" as this PR does.

What do you think? There is no need to rush to conclusions, and I don't see anything wrong with taking some time to think about it.

**Comment by htunnicliff** [comment]
Hi @yusukebe,

I think that makes sense. 

> The reasons are that this PR's approach is more complex compared to the "Origin Header" approach and is dependent on cookies

However, this might be important to clarify. If an application is not using cookies, my understanding is that there would not be a CSRF vulnerability. CSRF attacks are only possible if an app is using cookies for authentication.

**Comment by yusukebe** [comment]
@htunnicliff 

> CSRF attacks are only possible if an app is using cookies for authentication.

Indeed, you are right! But, strictly, there might be situations where an application, like a mobile app, stores a token or something similar without using cookies. In such cases, we can say that there is a CSRF vulnerability. But the "Origin Header" method might not support these scenarios too, and I think we don't need to focus on them.

**Comment by yusukebe** [comment]
I think if we go with "Original Header" method, basically @usualoma 's implementation as mentioned in the comment is great:

https://github.com/honojs/hono/issues/1688#issuecomment-1836019924

**Comment by usualoma** [comment]
Once, here to get a common understanding within the project about CSRF.
I understand the following.

### When does a CSRF problem occur?

CSRF occurs with submissions from form elements. A typical simple example is as follows

```html
<form action="https://target-site.example.com/admin/update-password" method="POST">
  <input name="new-password" value="P@ssw0rd"/>
</form>
<script>
document.querySelector("form").submit();
</script>
```

When we access this page, even if it is an external site, your browser will send a POST request to https://target-site.example.com with the cookie value. (although it depends on the SameSite attribute).

```html
<script>
fetch('https://target-site.example.com/admin/update-password', {
    method: 'POST',
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
    },
    body: 'password=p@ssw0rd',
    credentials: 'include'
})
</script>
```

This problem also occurs with "fetch() with exactly the same content as submitted from a form element" specifying x-www-form-urlencoded or application/multipart-form-data.

### What is not CSRF?

Suppose we have a request that cannot be generated by a form element submit, such as the following, which authenticates with its an application specific request header. This will generate a preflight request, and if the attack succeeds with this, it is a CORS misconfiguration. This is not a CSRF vulnerability.

```html
<script>
fetch('https://target-site.example.com/admin/update-password', {
    method: 'POST',
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        'X-session-id': 'a9f0dcb0-ef1f-11e9-81b4-2a2ae2dbcce4',
    },
    body: 'password=p@ssw0rd',
})
</script>
```

Similarly, even if an attack from a mobile application is successful, it is a matter of session management for that application. This is not a CSRF vulnerability.


### Don't we need to think about applications that are not using sessions?

As seen in the example above, a serious problem occurs in applications that use cookies for session management. However, even simple inquiry forms without session management should be CSRF-protected if possible.

```html
<form action="https://target-site.example.com/inquiry" method="POST">
  <input name="content" value="Text of the criminal threat"/>
</form>
<script>
document.querySelector("form").submit();
</script>
```

Even for applications that do not use session management, there are cases where it is a good idea to take measures against CSRF vulnerabilities, if possible, as a countermeasure against "DDoS" and "spoofing".

https://stackoverflow.com/questions/65236474/does-public-contact-form-require-a-csrf-token

### Is this PR middleware effective against these?

I think this PR middleware works fine, including applications that do not use session management.

However, I still think that the middleware provided by hono’s core should be a simpler "Original Header" validation method. The "Original Header" validation method is also effective for applications that do not use session management, and the procedure for applying it is simple.

**Comment by rafaell-lycan** [comment]
@htunnicliff you can simply use the [csrf](https://www.npmjs.com/package/csrf) instead.

**Comment by yusukebe** [comment]
@usualoma

Thanks for the clear summary.

Therefore, I'd like to proceed with the 'Origin Header' approach for the 'CSRF Protection Middleware'.

@usualoma would you be willing to create the PR? There's no rush for the implementation. And, even though you've already written some code, someone else, including @htunnicliff, could write the code and credit @usualoma  as a co-author.

**Comment by usualoma** [comment]
Sorry for the delay.
Please take a moment as I would like to proceed with the following PR.
https://github.com/honojs/hono/pull/1823

**Pull request closed without merging**
