### PR TITLE
feat(adapter): AWS Lambda Adapter supports requests via Lambda@edge

### PR DESCRIPTION
**Pull request by watany-dev**
I'm a little unsure, but I made it.
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-event-structure.html#lambda-event-structure-response

### CODE REVIEW

**Comment by watany-dev** [comment]
Please let me know if I should separate this commit from the API and make it as adaptor/aws-lambda-edge :)

**Comment by yusukebe** [comment]
Hi @watany-dev !

Thanks for the PR. Supporting Lambda@Edge is indeed something we are interested in.

> Please let me know if I should separate this commit from the API and make it as `adaptor/aws-lambda-edge` :)

Yes, it would be best to separate the adapter from `adapter/aws-lambda` and make this standalone. I believe naming it `adapter/lambda-edge` would be appropriate:

Screenshot 2023-07-01 at 17 25 00

Screenshot 2023-07-01 at 17 25 07

**Comment by yusukebe** [comment]
Hi @watany-dev 

Is this still working proggress?

**Comment by watany-dev** [comment]
@yusukebe 
Yes, I have fetched the latest materials and am in the process of working on it. Since I haven't been able to write the tests yet, I think it will take a few more days.

**Comment by yusukebe** [comment]
@watany-dev 

Okay!

**Comment by watany-dev** [comment]
@yusukebe 
Thanks for waiting. We were able to create it successfully.

**Comment by yusukebe** [comment]
@watany-dev 

Finally, you did it. Thank you! I'll merge now!!

**Comment by yusukebe** [comment]
@watany-dev 

If you feel up to it, could you write the document like ["AWS Lambda"](https://hono.dev/getting-started/aws-lambda) on website? Repository is [here](https://github.com/honojs/website). But, you don't have to do it.

**Comment by watany-dev** [comment]
@yusukebe 
Thank you for the wonderful offer. My writing might not be able to start until after July 14th. If that's okay, please allow me to contribute.

**Comment by yusukebe** [comment]
@watany-dev 

That's OK! Thanks.

**Pull request merged**
