### PR TITLE
feat(request): Make request.ts available throught JSR for frameworks that need to instantiate HonoRequest

### PR DESCRIPTION
**Pull request by Sorikairox**
### The author should do the following, if applicable

- [ ] Add tests
- [ ] Run tests
- [ ] `bun run format:fix && bun run lint:fix` to format the code
- [ ] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

**Comment by yusukebe** [comment]
Hey @Sorikairox 

Thank you for the PR! The `request.ts` is not exported for the npm package, not only for Deno. I want to know the situation if you want to use the `HonoRequest` class. Can you share the use case for using the `HonoRequest` class?

**Comment by Sorikairox** [comment]
@yusukebe 

Thanks for your answer !

The context is for our framework Danet (https://github.com/savory/Danet).

For the past 12 months or so until last week, we were using Hono's deno.land/x/ version, where everything was accessible. 
I decided to migrate to JSR, which is why I noticed that the class was not accessible.

To keep it simple, in order to allow our internal logic and our users to use the same code with either HTTP request or Websocket message, we instantiate a HonoRequest for the latter.

**Review by yusukebe — COMMENTED** [review]
LGTM!

**Comment by yusukebe** [comment]
@Sorikairox 

Thank you for your explanation! I understood well. I'll merge this into `main` later and include it in the next patch release. In the npm package, the `request.ts` also may be exported.

**Pull request merged**
