### PR TITLE
feat: 3346 customized response messages

### PR DESCRIPTION
**Pull request by marceloverdijk**
As discussed with @yusukebe here https://github.com/orgs/honojs/discussions/3346

### The author should do the following, if applicable

- [x] Add tests
- [x] Run tests
- [x] `bun run format:fix && bun run lint:fix` to format the code
- [x] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @marceloverdijk 

Thank you for creating the PR. I have some requests:

* I think the changes of `src/context.ts` and `src/utils/mime.ts` are not necessary in this feature. Please remove them.
* Can you separate this PR for Basic Auth and Bearer Auth?  This means you will close this PR and create new two PRs.

**Comment by marceloverdijk** [comment]
No problem, I will update (and separate) the PR this evening.

**Comment by yusukebe** [comment]
@marceloverdijk 

Thank you!

**Comment by yusukebe** [comment]
@marceloverdijk 

Making strings as constant like `APPLICATION_JSON_UTF_8` is good idea. But, it does not depends this feature and we can do it another PR.

**Comment by marceloverdijk** [comment]
@yusukebe I created the following (separated) PR's:

- https://github.com/honojs/hono/pull/3371
- https://github.com/honojs/hono/pull/3372
- https://github.com/honojs/hono/pull/3370

**Pull request closed without merging**
